#pragma once
#include "CoreMinimal.h"
#include "EIGS_AIMontageSOVariant.generated.h"

UENUM(BlueprintType)
enum class EIGS_AIMontageSOVariant : uint8 {
    SO_Unknown = 255,
    SO_Yawn = 0,
    SO_WatchTime,
    SO_Adjust,
    SO_Stretch,
    SO_EnterCode,
    SO_PressButton,
    SO_SwipeCard,
    SO_UseWaterDispence,
    SO_PickingUpFloor,
    SO_PaintingAlign,
    SO_DoorUnlock_Left,
    SO_DoorUnlock_Right,
    SO_WaveHand_ComeOn,
    SO_WaveHand_Angry,
    SO_WaveHand_Hello,
    SO_MeetingPresenter,
    SO_IDLE_Female,
    SO_Use_Phone_Wall,
    SO_Use_Phone_Table,
    SO_Press_Button_On_Table,
    SO_Press_Button_Under_Table,
    SO_Surprise,
    SO_TakeDown,
    SO_BeignTakenDown,
    SO_Throw,
    SO_Pickup,
    SO_L_Idle = 127,
    SO_L_WalkieTalkie,
    SO_L_HoldButton,
    SO_L_HoldingButtonOnTable = 144,
    SO_L_HoldingButtonUnderTable,
    SO_L_LookOut_Left = 131,
    SO_L_LookOut_Right,
    SO_L_LookOut_Front,
    SO_L_LookOut_Ground,
    SO_L_LookOut_Up,
    SO_L_LookOut_Up_Slightly,
    SO_L_LookOut_Corner_Left,
    SO_L_LookOut_Corner_Right,
    SO_L_LookOut_Under_Table,
    SO_L_LookOut_Under_Car,
    SO_L_SitFloor_Beggar = 150,
    SO_L_SitChair_Reading,
    SO_L_Sit_Bench_Center = 172,
    SO_L_Sit_Table_FeetOn = 154,
    SO_L_Sit_Table,
    SO_L_Sit_Table_2 = 161,
    SO_L_Sit_Desk,
    SO_L_Sit_Table_FeetOn_Right = 164,
    SO_L_Sit_Sofa_Center = 167,
    SO_L_Sit_Sofa_Left,
    SO_L_Sit_Sofa_Right,
    SO_L_FixingWall = 141,
    SO_L_FixingFloor = 147,
    SO_L_CleaningWindowStand = 142,
    SO_L_CleaningWindowCrouch,
    SO_L_CleaningFloorCrouch = 146,
    SO_L_LeanWall_Back = 148,
    SO_L_LeanWall_Left,
    SO_L_Lean_Fence_Front = 163,
    SO_L_LeanFence_Back = 152,
    SO_L_LeanTable_Front,
    SO_L_UsePrinter = 130,
    SO_L_UseATM = 156,
    SO_L_UseVendingMachine,
    SO_L_UseCoffeeMachine,
    SO_L_UseDryer,
    SO_L_UseTicketDispencer = 165,
    SO_L_UseUrinal = 171,
    SO_L_WashHand = 160,
    SO_L_SearchTable = 166,
    SO_L_Discussion = 170,
};

