#pragma once
#include "CoreMinimal.h"
#include "EIGS_ObjectiveComponentType.generated.h"

UENUM(BlueprintType)
enum class EIGS_ObjectiveComponentType : uint8 {
    Default,
    Populator,
    EntryTrigger,
    EmployeeTrigger,
    SecurityTrigger,
    VaultTrigger,
    Trigger1,
    Trigger2,
    Trigger3,
    Trigger4,
    Trigger5,
    Trigger6,
    Trigger7,
    Trigger8,
    Trigger9,
    Trigger10,
    Item1,
    Item2,
    Item3,
    Item4,
    Item5,
    Item6,
    Item7,
    Item8,
    Item9,
    Item10,
    NPC1,
    NPC2,
    NPC3,
    NPC4,
    NPC5,
    NPC6,
    NPC7,
    NPC8,
    NPC9,
    NPC10,
    Universal1,
    Universal2,
    Universal3,
    Universal4,
    Universal5,
    VaultItem1,
    VaultItem2,
    VaultItem3,
    VaultItem4,
    VaultItem5,
    VaultItem6,
    VaultItem7,
    VaultItem8,
    VaultItem9,
    VaultItem10,
    Finish,
    AlarmDisable,
};

