#include "HoudiniStaticMeshGenerationProperties.h"
#include "PhysicsEngine/BodyInstance.h"
#include "Chaos/ChaosEngineInterface.h"

FHoudiniStaticMeshGenerationProperties::FHoudiniStaticMeshGenerationProperties() {
    (*this).bGeneratedDoubleSidedGeometry = false;
    (*this).GeneratedPhysMaterial = nullptr;
    (*TBaseStructure<FBodyInstance>::Get()->FindPropertyByName("ObjectType")->ContainerPtrToValuePtr<TEnumAsByte<ECollisionChannel>>(&(*this).DefaultBodyInstance, 0)) = ECC_WorldStatic;
    (*TBaseStructure<FBodyInstance>::Get()->FindPropertyByName("CollisionEnabled")->ContainerPtrToValuePtr<TEnumAsByte<ECollisionEnabled::Type>>(&(*this).DefaultBodyInstance, 0)) = ECollisionEnabled::QueryAndPhysics;
    (*this).DefaultBodyInstance.SleepFamily = ESleepFamily::Normal;
    (*this).DefaultBodyInstance.DOFMode = EDOFMode::Default;
    (*this).DefaultBodyInstance.bUseCCD = false;
    (*this).DefaultBodyInstance.bIgnoreAnalyticCollisions = false;
    (*this).DefaultBodyInstance.bNotifyRigidBodyCollision = false;
    (*this).DefaultBodyInstance.bLockTranslation = true;
    (*this).DefaultBodyInstance.bLockRotation = true;
    (*this).DefaultBodyInstance.bLockXTranslation = false;
    (*this).DefaultBodyInstance.bLockYTranslation = false;
    (*this).DefaultBodyInstance.bLockZTranslation = false;
    (*this).DefaultBodyInstance.bLockXRotation = false;
    (*this).DefaultBodyInstance.bLockYRotation = false;
    (*this).DefaultBodyInstance.bLockZRotation = false;
    (*this).DefaultBodyInstance.bOverrideMaxAngularVelocity = false;
    (*TBaseStructure<FBodyInstance>::Get()->FindPropertyByName("CollisionProfileName")->ContainerPtrToValuePtr<FName>(&(*this).DefaultBodyInstance, 0)) = TEXT("BlockAll");
    (*this).DefaultBodyInstance.PositionSolverIterationCount = 8;
    (*this).DefaultBodyInstance.VelocitySolverIterationCount = 1;
    (*TBaseStructure<FCollisionResponse>::Get()->FindPropertyByName("ResponseToChannels")->ContainerPtrToValuePtr<FCollisionResponseContainer>(&(*TBaseStructure<FBodyInstance>::Get()->FindPropertyByName("CollisionResponses")->ContainerPtrToValuePtr<FCollisionResponse>(&(*this).DefaultBodyInstance, 0)), 0)).WorldStatic = ECR_Block;
    (*TBaseStructure<FCollisionResponse>::Get()->FindPropertyByName("ResponseToChannels")->ContainerPtrToValuePtr<FCollisionResponseContainer>(&(*TBaseStructure<FBodyInstance>::Get()->FindPropertyByName("CollisionResponses")->ContainerPtrToValuePtr<FCollisionResponse>(&(*this).DefaultBodyInstance, 0)), 0)).WorldDynamic = ECR_Block;
    (*TBaseStructure<FCollisionResponse>::Get()->FindPropertyByName("ResponseToChannels")->ContainerPtrToValuePtr<FCollisionResponseContainer>(&(*TBaseStructure<FBodyInstance>::Get()->FindPropertyByName("CollisionResponses")->ContainerPtrToValuePtr<FCollisionResponse>(&(*this).DefaultBodyInstance, 0)), 0)).Pawn = ECR_Block;
    (*TBaseStructure<FCollisionResponse>::Get()->FindPropertyByName("ResponseToChannels")->ContainerPtrToValuePtr<FCollisionResponseContainer>(&(*TBaseStructure<FBodyInstance>::Get()->FindPropertyByName("CollisionResponses")->ContainerPtrToValuePtr<FCollisionResponse>(&(*this).DefaultBodyInstance, 0)), 0)).Visibility = ECR_Block;
    (*TBaseStructure<FCollisionResponse>::Get()->FindPropertyByName("ResponseToChannels")->ContainerPtrToValuePtr<FCollisionResponseContainer>(&(*TBaseStructure<FBodyInstance>::Get()->FindPropertyByName("CollisionResponses")->ContainerPtrToValuePtr<FCollisionResponse>(&(*this).DefaultBodyInstance, 0)), 0)).Camera = ECR_Block;
    (*TBaseStructure<FCollisionResponse>::Get()->FindPropertyByName("ResponseToChannels")->ContainerPtrToValuePtr<FCollisionResponseContainer>(&(*TBaseStructure<FBodyInstance>::Get()->FindPropertyByName("CollisionResponses")->ContainerPtrToValuePtr<FCollisionResponse>(&(*this).DefaultBodyInstance, 0)), 0)).PhysicsBody = ECR_Block;
    (*TBaseStructure<FCollisionResponse>::Get()->FindPropertyByName("ResponseToChannels")->ContainerPtrToValuePtr<FCollisionResponseContainer>(&(*TBaseStructure<FBodyInstance>::Get()->FindPropertyByName("CollisionResponses")->ContainerPtrToValuePtr<FCollisionResponse>(&(*this).DefaultBodyInstance, 0)), 0)).Vehicle = ECR_Block;
    (*TBaseStructure<FCollisionResponse>::Get()->FindPropertyByName("ResponseToChannels")->ContainerPtrToValuePtr<FCollisionResponseContainer>(&(*TBaseStructure<FBodyInstance>::Get()->FindPropertyByName("CollisionResponses")->ContainerPtrToValuePtr<FCollisionResponse>(&(*this).DefaultBodyInstance, 0)), 0)).Destructible = ECR_Block;
    (*TBaseStructure<FCollisionResponse>::Get()->FindPropertyByName("ResponseToChannels")->ContainerPtrToValuePtr<FCollisionResponseContainer>(&(*TBaseStructure<FBodyInstance>::Get()->FindPropertyByName("CollisionResponses")->ContainerPtrToValuePtr<FCollisionResponse>(&(*this).DefaultBodyInstance, 0)), 0)).EngineTraceChannel1 = ECR_Ignore;
    (*TBaseStructure<FCollisionResponse>::Get()->FindPropertyByName("ResponseToChannels")->ContainerPtrToValuePtr<FCollisionResponseContainer>(&(*TBaseStructure<FBodyInstance>::Get()->FindPropertyByName("CollisionResponses")->ContainerPtrToValuePtr<FCollisionResponse>(&(*this).DefaultBodyInstance, 0)), 0)).EngineTraceChannel2 = ECR_Block;
    (*TBaseStructure<FCollisionResponse>::Get()->FindPropertyByName("ResponseToChannels")->ContainerPtrToValuePtr<FCollisionResponseContainer>(&(*TBaseStructure<FBodyInstance>::Get()->FindPropertyByName("CollisionResponses")->ContainerPtrToValuePtr<FCollisionResponse>(&(*this).DefaultBodyInstance, 0)), 0)).EngineTraceChannel3 = ECR_Block;
    (*TBaseStructure<FCollisionResponse>::Get()->FindPropertyByName("ResponseToChannels")->ContainerPtrToValuePtr<FCollisionResponseContainer>(&(*TBaseStructure<FBodyInstance>::Get()->FindPropertyByName("CollisionResponses")->ContainerPtrToValuePtr<FCollisionResponse>(&(*this).DefaultBodyInstance, 0)), 0)).EngineTraceChannel4 = ECR_Block;
    (*TBaseStructure<FCollisionResponse>::Get()->FindPropertyByName("ResponseToChannels")->ContainerPtrToValuePtr<FCollisionResponseContainer>(&(*TBaseStructure<FBodyInstance>::Get()->FindPropertyByName("CollisionResponses")->ContainerPtrToValuePtr<FCollisionResponse>(&(*this).DefaultBodyInstance, 0)), 0)).EngineTraceChannel5 = ECR_Block;
    (*TBaseStructure<FCollisionResponse>::Get()->FindPropertyByName("ResponseToChannels")->ContainerPtrToValuePtr<FCollisionResponseContainer>(&(*TBaseStructure<FBodyInstance>::Get()->FindPropertyByName("CollisionResponses")->ContainerPtrToValuePtr<FCollisionResponse>(&(*this).DefaultBodyInstance, 0)), 0)).EngineTraceChannel6 = ECR_Block;
    (*TBaseStructure<FCollisionResponse>::Get()->FindPropertyByName("ResponseToChannels")->ContainerPtrToValuePtr<FCollisionResponseContainer>(&(*TBaseStructure<FBodyInstance>::Get()->FindPropertyByName("CollisionResponses")->ContainerPtrToValuePtr<FCollisionResponse>(&(*this).DefaultBodyInstance, 0)), 0)).GameTraceChannel1 = ECR_Block;
    (*TBaseStructure<FCollisionResponse>::Get()->FindPropertyByName("ResponseToChannels")->ContainerPtrToValuePtr<FCollisionResponseContainer>(&(*TBaseStructure<FBodyInstance>::Get()->FindPropertyByName("CollisionResponses")->ContainerPtrToValuePtr<FCollisionResponse>(&(*this).DefaultBodyInstance, 0)), 0)).GameTraceChannel2 = ECR_Block;
    (*TBaseStructure<FCollisionResponse>::Get()->FindPropertyByName("ResponseToChannels")->ContainerPtrToValuePtr<FCollisionResponseContainer>(&(*TBaseStructure<FBodyInstance>::Get()->FindPropertyByName("CollisionResponses")->ContainerPtrToValuePtr<FCollisionResponse>(&(*this).DefaultBodyInstance, 0)), 0)).GameTraceChannel3 = ECR_Block;
    (*TBaseStructure<FCollisionResponse>::Get()->FindPropertyByName("ResponseToChannels")->ContainerPtrToValuePtr<FCollisionResponseContainer>(&(*TBaseStructure<FBodyInstance>::Get()->FindPropertyByName("CollisionResponses")->ContainerPtrToValuePtr<FCollisionResponse>(&(*this).DefaultBodyInstance, 0)), 0)).GameTraceChannel4 = ECR_Block;
    (*TBaseStructure<FCollisionResponse>::Get()->FindPropertyByName("ResponseToChannels")->ContainerPtrToValuePtr<FCollisionResponseContainer>(&(*TBaseStructure<FBodyInstance>::Get()->FindPropertyByName("CollisionResponses")->ContainerPtrToValuePtr<FCollisionResponse>(&(*this).DefaultBodyInstance, 0)), 0)).GameTraceChannel5 = ECR_Block;
    (*TBaseStructure<FCollisionResponse>::Get()->FindPropertyByName("ResponseToChannels")->ContainerPtrToValuePtr<FCollisionResponseContainer>(&(*TBaseStructure<FBodyInstance>::Get()->FindPropertyByName("CollisionResponses")->ContainerPtrToValuePtr<FCollisionResponse>(&(*this).DefaultBodyInstance, 0)), 0)).GameTraceChannel6 = ECR_Block;
    (*TBaseStructure<FCollisionResponse>::Get()->FindPropertyByName("ResponseToChannels")->ContainerPtrToValuePtr<FCollisionResponseContainer>(&(*TBaseStructure<FBodyInstance>::Get()->FindPropertyByName("CollisionResponses")->ContainerPtrToValuePtr<FCollisionResponse>(&(*this).DefaultBodyInstance, 0)), 0)).GameTraceChannel7 = ECR_Block;
    (*TBaseStructure<FCollisionResponse>::Get()->FindPropertyByName("ResponseToChannels")->ContainerPtrToValuePtr<FCollisionResponseContainer>(&(*TBaseStructure<FBodyInstance>::Get()->FindPropertyByName("CollisionResponses")->ContainerPtrToValuePtr<FCollisionResponse>(&(*this).DefaultBodyInstance, 0)), 0)).GameTraceChannel8 = ECR_Block;
    (*TBaseStructure<FCollisionResponse>::Get()->FindPropertyByName("ResponseToChannels")->ContainerPtrToValuePtr<FCollisionResponseContainer>(&(*TBaseStructure<FBodyInstance>::Get()->FindPropertyByName("CollisionResponses")->ContainerPtrToValuePtr<FCollisionResponse>(&(*this).DefaultBodyInstance, 0)), 0)).GameTraceChannel9 = ECR_Block;
    (*TBaseStructure<FCollisionResponse>::Get()->FindPropertyByName("ResponseToChannels")->ContainerPtrToValuePtr<FCollisionResponseContainer>(&(*TBaseStructure<FBodyInstance>::Get()->FindPropertyByName("CollisionResponses")->ContainerPtrToValuePtr<FCollisionResponse>(&(*this).DefaultBodyInstance, 0)), 0)).GameTraceChannel10 = ECR_Block;
    (*TBaseStructure<FCollisionResponse>::Get()->FindPropertyByName("ResponseToChannels")->ContainerPtrToValuePtr<FCollisionResponseContainer>(&(*TBaseStructure<FBodyInstance>::Get()->FindPropertyByName("CollisionResponses")->ContainerPtrToValuePtr<FCollisionResponse>(&(*this).DefaultBodyInstance, 0)), 0)).GameTraceChannel11 = ECR_Block;
    (*TBaseStructure<FCollisionResponse>::Get()->FindPropertyByName("ResponseToChannels")->ContainerPtrToValuePtr<FCollisionResponseContainer>(&(*TBaseStructure<FBodyInstance>::Get()->FindPropertyByName("CollisionResponses")->ContainerPtrToValuePtr<FCollisionResponse>(&(*this).DefaultBodyInstance, 0)), 0)).GameTraceChannel12 = ECR_Block;
    (*TBaseStructure<FCollisionResponse>::Get()->FindPropertyByName("ResponseToChannels")->ContainerPtrToValuePtr<FCollisionResponseContainer>(&(*TBaseStructure<FBodyInstance>::Get()->FindPropertyByName("CollisionResponses")->ContainerPtrToValuePtr<FCollisionResponse>(&(*this).DefaultBodyInstance, 0)), 0)).GameTraceChannel13 = ECR_Block;
    (*TBaseStructure<FCollisionResponse>::Get()->FindPropertyByName("ResponseToChannels")->ContainerPtrToValuePtr<FCollisionResponseContainer>(&(*TBaseStructure<FBodyInstance>::Get()->FindPropertyByName("CollisionResponses")->ContainerPtrToValuePtr<FCollisionResponse>(&(*this).DefaultBodyInstance, 0)), 0)).GameTraceChannel14 = ECR_Block;
    (*TBaseStructure<FCollisionResponse>::Get()->FindPropertyByName("ResponseToChannels")->ContainerPtrToValuePtr<FCollisionResponseContainer>(&(*TBaseStructure<FBodyInstance>::Get()->FindPropertyByName("CollisionResponses")->ContainerPtrToValuePtr<FCollisionResponse>(&(*this).DefaultBodyInstance, 0)), 0)).GameTraceChannel15 = ECR_Block;
    (*TBaseStructure<FCollisionResponse>::Get()->FindPropertyByName("ResponseToChannels")->ContainerPtrToValuePtr<FCollisionResponseContainer>(&(*TBaseStructure<FBodyInstance>::Get()->FindPropertyByName("CollisionResponses")->ContainerPtrToValuePtr<FCollisionResponse>(&(*this).DefaultBodyInstance, 0)), 0)).GameTraceChannel16 = ECR_Block;
    (*TBaseStructure<FCollisionResponse>::Get()->FindPropertyByName("ResponseToChannels")->ContainerPtrToValuePtr<FCollisionResponseContainer>(&(*TBaseStructure<FBodyInstance>::Get()->FindPropertyByName("CollisionResponses")->ContainerPtrToValuePtr<FCollisionResponse>(&(*this).DefaultBodyInstance, 0)), 0)).GameTraceChannel17 = ECR_Block;
    (*TBaseStructure<FCollisionResponse>::Get()->FindPropertyByName("ResponseToChannels")->ContainerPtrToValuePtr<FCollisionResponseContainer>(&(*TBaseStructure<FBodyInstance>::Get()->FindPropertyByName("CollisionResponses")->ContainerPtrToValuePtr<FCollisionResponse>(&(*this).DefaultBodyInstance, 0)), 0)).GameTraceChannel18 = ECR_Block;
    auto& gen0 = (*TBaseStructure<FCollisionResponse>::Get()->FindPropertyByName("ResponseArray")->ContainerPtrToValuePtr<TArray<FResponseChannel>>(&(*TBaseStructure<FBodyInstance>::Get()->FindPropertyByName("CollisionResponses")->ContainerPtrToValuePtr<FCollisionResponse>(&(*this).DefaultBodyInstance, 0)), 0));
    gen0.Empty();
    gen0.AddDefaulted(3);
    (*TBaseStructure<FBodyInstance>::Get()->FindPropertyByName("MaxDepenetrationVelocity")->ContainerPtrToValuePtr<float>(&(*this).DefaultBodyInstance, 0)) = 0.000000000e+00f;
    (*TBaseStructure<FBodyInstance>::Get()->FindPropertyByName("MassInKgOverride")->ContainerPtrToValuePtr<float>(&(*this).DefaultBodyInstance, 0)) = 1.000000000e+02f;
    (*this).DefaultBodyInstance.LinearDamping = 9.999999776e-03f;
    (*this).DefaultBodyInstance.AngularDamping = 0.000000000e+00f;
    (*this).DefaultBodyInstance.CustomDOFPlaneNormal.X = 0.000000000e+00f;
    (*this).DefaultBodyInstance.CustomDOFPlaneNormal.Y = 0.000000000e+00f;
    (*this).DefaultBodyInstance.CustomDOFPlaneNormal.Z = 0.000000000e+00f;
    (*this).DefaultBodyInstance.COMNudge.X = 0.000000000e+00f;
    (*this).DefaultBodyInstance.COMNudge.Y = 0.000000000e+00f;
    (*this).DefaultBodyInstance.COMNudge.Z = 0.000000000e+00f;
    (*this).DefaultBodyInstance.MassScale = 1.000000000e+00f;
    (*this).DefaultBodyInstance.InertiaTensorScale.X = 1.000000000e+00f;
    (*this).DefaultBodyInstance.InertiaTensorScale.Y = 1.000000000e+00f;
    (*this).DefaultBodyInstance.InertiaTensorScale.Z = 1.000000000e+00f;
    (*TBaseStructure<FBodyInstance>::Get()->FindPropertyByName("WalkableSlopeOverride")->ContainerPtrToValuePtr<FWalkableSlopeOverride>(&(*this).DefaultBodyInstance, 0)).WalkableSlopeBehavior = WalkableSlope_Default;
    (*TBaseStructure<FBodyInstance>::Get()->FindPropertyByName("WalkableSlopeOverride")->ContainerPtrToValuePtr<FWalkableSlopeOverride>(&(*this).DefaultBodyInstance, 0)).WalkableSlopeAngle = 0.000000000e+00f;
    (*TBaseStructure<FBodyInstance>::Get()->FindPropertyByName("PhysMaterialOverride")->ContainerPtrToValuePtr<UPhysicalMaterial*>(&(*this).DefaultBodyInstance, 0)) = nullptr;
    (*this).DefaultBodyInstance.MaxAngularVelocity = 3.600000000e+03f;
    (*this).DefaultBodyInstance.CustomSleepThresholdMultiplier = 1.000000000e+00f;
    (*this).DefaultBodyInstance.StabilizationThresholdMultiplier = 1.000000000e+00f;
    (*this).DefaultBodyInstance.PhysicsBlendWeight = 0.000000000e+00f;
    (*this).DefaultBodyInstance.bSimulatePhysics = false;
    (*this).DefaultBodyInstance.bOverrideMass = false;
    (*this).DefaultBodyInstance.bEnableGravity = true;
    (*this).DefaultBodyInstance.bAutoWeld = false;
    (*this).DefaultBodyInstance.bStartAwake = true;
    (*this).DefaultBodyInstance.bGenerateWakeEvents = false;
    (*this).DefaultBodyInstance.bUpdateMassWhenScaleChanges = false;
    (*this).GeneratedCollisionTraceFlag = CTF_UseDefault;
    (*this).GeneratedLightMapResolution = 64;
    (*this).GeneratedWalkableSlopeOverride.WalkableSlopeBehavior = WalkableSlope_Default;
    (*this).GeneratedWalkableSlopeOverride.WalkableSlopeAngle = 0.000000000e+00f;
    (*this).GeneratedLightMapCoordinateIndex = 1;
    (*this).bGeneratedUseMaximumStreamingTexelRatio = false;
    (*this).GeneratedStreamingDistanceMultiplier = 1.000000000e+00f;
    (*this).GeneratedFoliageDefaultSettings = nullptr;
    (*this).GeneratedAssetUserData.Empty();
}

