#pragma once
#include "CoreMinimal.h"
#include "EIGS_InputAction.generated.h"

UENUM(BlueprintType)
enum class EIGS_InputAction : uint8 {
    IA_UNKNOWN = 255,
    IA_MoveForward = 0,
    IA_MoveBackwards,
    IA_MoveLeft,
    IA_MoveRight,
    IA_Jump,
    IA_Crouch,
    IA_Sprint,
    IA_Aim,
    IA_Shoot,
    IA_InspectWeapon,
    IA_Reload,
    IA_SwitchFireMode,
    IA_Use,
    IA_Bash,
    IA_CharacterMenu,
    IA_BotMenuPossess,
    IA_BotMenuCancel,
    IA_BotMenuFollow,
    IA_BotMenuStandBy,
    IA_WeaponWheel,
    IA_NextWeapon,
    IA_PreviousWeapon,
    IA_PrimaryWeapon,
    IA_SecondaryWeapon,
    IA_MeleeWeapon,
    IA_SpecialAction1,
    IA_SwitchWeapon,
    IA_Approve,
    IA_EnterChat,
    IA_Ping,
    IA_Walk,
    IA_DropCarryable,
    IA_Holster,
    IA_Shout,
    IA_MenuLeft,
    IA_MenuRight,
    IA_MenuBack,
    IA_MenuAccept,
    IA_MenuMiscAction1,
    IA_MenuMiscAction2,
    IA_MenuCategoryLeft,
    IA_MenuCategoryRight,
    IA_MenuSubcategoryLeft,
    IA_MenuSubcategoryRight,
    IA_MenuPause,
    IA_PartyInvite,
    IA_Skip,
    IA_MenuUp,
    IA_MenuDown,
    IA_MountLeft,
    IA_MountRight,
    IA_MountUp,
    IA_MountDown,
    IA_MountPrimary,
    IA_MountSecondary,
    IA_MountTertiary,
    IA_MountQuaternary,
    IA_Lockpick,
    IA_WheelMenu,
    IA_PushToTalk,
};

