#include "META_MoneyMakingScenariosAdditionalWealthAndProbabilitiesConfiguration.h"

FMETA_MoneyMakingScenariosAdditionalWealthAndProbabilitiesConfiguration::FMETA_MoneyMakingScenariosAdditionalWealthAndProbabilitiesConfiguration() {
}

