#include "IGS_AIBackupTeamDef.h"
#include "GameplayTagContainer.h"
#include "EIGS_CoverPreset.h"
#include "EIGS_TeamSideEnum.h"

FIGS_AIBackupTeamDef::FIGS_AIBackupTeamDef() {
    (*this).Tiers.Tier1.Default.Stats.HP.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier1.Default.Stats.HP.Value = 2.800000000e+02f;
    (*this).Tiers.Tier1.Default.Stats.HP.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier1.Default.Stats.HP.bOverloadValue = false;
    (*this).Tiers.Tier1.Default.Stats.Shield.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier1.Default.Stats.Shield.Value = 0.000000000e+00f;
    (*this).Tiers.Tier1.Default.Stats.Shield.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier1.Default.Stats.Shield.bOverloadValue = false;
    (*this).Tiers.Tier1.Default.Stats.WeaponDamage.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier1.Default.Stats.WeaponDamage.Value = 1.000000000e+00f;
    (*this).Tiers.Tier1.Default.Stats.WeaponDamage.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier1.Default.Stats.WeaponDamage.bOverloadValue = false;
    (*this).Tiers.Tier1.Default.Stats.MeleeDamage.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier1.Default.Stats.MeleeDamage.Value = 1.000000000e+00f;
    (*this).Tiers.Tier1.Default.Stats.MeleeDamage.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier1.Default.Stats.MeleeDamage.bOverloadValue = false;
    (*this).Tiers.Tier1.Default.Stats.WeaponDispersion.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier1.Default.Stats.WeaponDispersion.Value = 1.000000000e+00f;
    (*this).Tiers.Tier1.Default.Stats.WeaponDispersion.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier1.Default.Stats.WeaponDispersion.bOverloadValue = false;
    (*this).Tiers.Tier1.Default.Stats.MovementSpeed.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier1.Default.Stats.MovementSpeed.Value = 1.000000000e+00f;
    (*this).Tiers.Tier1.Default.Stats.MovementSpeed.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier1.Default.Stats.MovementSpeed.bOverloadValue = false;
    (*this).Tiers.Tier1.Default.Stats.CoverStickiness.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier1.Default.Stats.CoverStickiness.Value = 5.000000000e-01f;
    (*this).Tiers.Tier1.Default.Stats.CoverStickiness.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier1.Default.Stats.CoverStickiness.bOverloadValue = false;
    (*this).Tiers.Tier1.Default.Stats.ReactionIntensity.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier1.Default.Stats.ReactionIntensity.Value = 5.000000000e-01f;
    (*this).Tiers.Tier1.Default.Stats.ReactionIntensity.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier1.Default.Stats.ReactionIntensity.bOverloadValue = false;
    (*this).Tiers.Tier1.Default.Enabled = true;
    (*this).Tiers.Tier1.Default.Character.Controller = nullptr;
    (*this).Tiers.Tier1.Default.Character.Pawns.Empty();
    (*this).Tiers.Tier1.Default.Loadout.WeaponPool.PrimaryWeapons.Empty();
    (*this).Tiers.Tier1.Default.Loadout.WeaponPool.SecondaryWeapons.Empty();
    (*this).Tiers.Tier1.Default.Loadout.WeaponPool.MeleeWeapons.Empty();
    (*this).Tiers.Tier1.Default.Loadout.WeaponProbability.Empty();
    (*this).Tiers.Tier1.Default.Loadout.NoThrowableChance = 0;
    (*this).Tiers.Tier1.Default.Loadout.ThrowablePool.Empty();
    (*TBaseStructure<FGameplayTag>::Get()->FindPropertyByName("TagName")->ContainerPtrToValuePtr<FName>(&(*this).Tiers.Tier1.Default.Loadout.EmptyWeaponTag, 0)) = TEXT("Item.Wieldable.Weapon");
    (*this).Tiers.Tier1.Default.Loadout.ShowNoThrowableBool = 0;
    (*TBaseStructure<FGameplayTag>::Get()->FindPropertyByName("TagName")->ContainerPtrToValuePtr<FName>(&(*this).Tiers.Tier1.Default.Specialization, 0)) = TEXT("AI.Specialization.Default");
    (*this).Tiers.Tier1.Heavy.Stats.HP.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier1.Heavy.Stats.HP.Value = 2.800000000e+02f;
    (*this).Tiers.Tier1.Heavy.Stats.HP.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier1.Heavy.Stats.HP.bOverloadValue = false;
    (*this).Tiers.Tier1.Heavy.Stats.Shield.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier1.Heavy.Stats.Shield.Value = 0.000000000e+00f;
    (*this).Tiers.Tier1.Heavy.Stats.Shield.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier1.Heavy.Stats.Shield.bOverloadValue = false;
    (*this).Tiers.Tier1.Heavy.Stats.WeaponDamage.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier1.Heavy.Stats.WeaponDamage.Value = 1.000000000e+00f;
    (*this).Tiers.Tier1.Heavy.Stats.WeaponDamage.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier1.Heavy.Stats.WeaponDamage.bOverloadValue = false;
    (*this).Tiers.Tier1.Heavy.Stats.MeleeDamage.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier1.Heavy.Stats.MeleeDamage.Value = 1.000000000e+00f;
    (*this).Tiers.Tier1.Heavy.Stats.MeleeDamage.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier1.Heavy.Stats.MeleeDamage.bOverloadValue = false;
    (*this).Tiers.Tier1.Heavy.Stats.WeaponDispersion.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier1.Heavy.Stats.WeaponDispersion.Value = 1.000000000e+00f;
    (*this).Tiers.Tier1.Heavy.Stats.WeaponDispersion.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier1.Heavy.Stats.WeaponDispersion.bOverloadValue = false;
    (*this).Tiers.Tier1.Heavy.Stats.MovementSpeed.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier1.Heavy.Stats.MovementSpeed.Value = 1.000000000e+00f;
    (*this).Tiers.Tier1.Heavy.Stats.MovementSpeed.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier1.Heavy.Stats.MovementSpeed.bOverloadValue = false;
    (*this).Tiers.Tier1.Heavy.Stats.CoverStickiness.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier1.Heavy.Stats.CoverStickiness.Value = 5.000000000e-01f;
    (*this).Tiers.Tier1.Heavy.Stats.CoverStickiness.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier1.Heavy.Stats.CoverStickiness.bOverloadValue = false;
    (*this).Tiers.Tier1.Heavy.Stats.ReactionIntensity.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier1.Heavy.Stats.ReactionIntensity.Value = 5.000000000e-01f;
    (*this).Tiers.Tier1.Heavy.Stats.ReactionIntensity.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier1.Heavy.Stats.ReactionIntensity.bOverloadValue = false;
    (*this).Tiers.Tier1.Heavy.Enabled = true;
    (*this).Tiers.Tier1.Heavy.Character.Controller = nullptr;
    (*this).Tiers.Tier1.Heavy.Character.Pawns.Empty();
    (*this).Tiers.Tier1.Heavy.Loadout.WeaponPool.PrimaryWeapons.Empty();
    (*this).Tiers.Tier1.Heavy.Loadout.WeaponPool.SecondaryWeapons.Empty();
    (*this).Tiers.Tier1.Heavy.Loadout.WeaponPool.MeleeWeapons.Empty();
    (*this).Tiers.Tier1.Heavy.Loadout.WeaponProbability.Empty();
    (*this).Tiers.Tier1.Heavy.Loadout.NoThrowableChance = 0;
    (*this).Tiers.Tier1.Heavy.Loadout.ThrowablePool.Empty();
    (*TBaseStructure<FGameplayTag>::Get()->FindPropertyByName("TagName")->ContainerPtrToValuePtr<FName>(&(*this).Tiers.Tier1.Heavy.Loadout.EmptyWeaponTag, 0)) = TEXT("Item.Wieldable.Weapon");
    (*this).Tiers.Tier1.Heavy.Loadout.ShowNoThrowableBool = 0;
    (*TBaseStructure<FGameplayTag>::Get()->FindPropertyByName("TagName")->ContainerPtrToValuePtr<FName>(&(*this).Tiers.Tier1.Heavy.Specialization, 0)) = TEXT("AI.Specialization.Special.Heavy");
    (*this).Tiers.Tier2.Default.Stats.HP.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier2.Default.Stats.HP.Value = 2.800000000e+02f;
    (*this).Tiers.Tier2.Default.Stats.HP.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier2.Default.Stats.HP.bOverloadValue = false;
    (*this).Tiers.Tier2.Default.Stats.Shield.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier2.Default.Stats.Shield.Value = 0.000000000e+00f;
    (*this).Tiers.Tier2.Default.Stats.Shield.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier2.Default.Stats.Shield.bOverloadValue = false;
    (*this).Tiers.Tier2.Default.Stats.WeaponDamage.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier2.Default.Stats.WeaponDamage.Value = 1.000000000e+00f;
    (*this).Tiers.Tier2.Default.Stats.WeaponDamage.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier2.Default.Stats.WeaponDamage.bOverloadValue = false;
    (*this).Tiers.Tier2.Default.Stats.MeleeDamage.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier2.Default.Stats.MeleeDamage.Value = 1.000000000e+00f;
    (*this).Tiers.Tier2.Default.Stats.MeleeDamage.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier2.Default.Stats.MeleeDamage.bOverloadValue = false;
    (*this).Tiers.Tier2.Default.Stats.WeaponDispersion.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier2.Default.Stats.WeaponDispersion.Value = 1.000000000e+00f;
    (*this).Tiers.Tier2.Default.Stats.WeaponDispersion.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier2.Default.Stats.WeaponDispersion.bOverloadValue = false;
    (*this).Tiers.Tier2.Default.Stats.MovementSpeed.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier2.Default.Stats.MovementSpeed.Value = 1.000000000e+00f;
    (*this).Tiers.Tier2.Default.Stats.MovementSpeed.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier2.Default.Stats.MovementSpeed.bOverloadValue = false;
    (*this).Tiers.Tier2.Default.Stats.CoverStickiness.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier2.Default.Stats.CoverStickiness.Value = 5.000000000e-01f;
    (*this).Tiers.Tier2.Default.Stats.CoverStickiness.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier2.Default.Stats.CoverStickiness.bOverloadValue = false;
    (*this).Tiers.Tier2.Default.Stats.ReactionIntensity.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier2.Default.Stats.ReactionIntensity.Value = 5.000000000e-01f;
    (*this).Tiers.Tier2.Default.Stats.ReactionIntensity.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier2.Default.Stats.ReactionIntensity.bOverloadValue = false;
    (*this).Tiers.Tier2.Default.Enabled = true;
    (*this).Tiers.Tier2.Default.Character.Controller = nullptr;
    (*this).Tiers.Tier2.Default.Character.Pawns.Empty();
    (*this).Tiers.Tier2.Default.Loadout.WeaponPool.PrimaryWeapons.Empty();
    (*this).Tiers.Tier2.Default.Loadout.WeaponPool.SecondaryWeapons.Empty();
    (*this).Tiers.Tier2.Default.Loadout.WeaponPool.MeleeWeapons.Empty();
    (*this).Tiers.Tier2.Default.Loadout.WeaponProbability.Empty();
    (*this).Tiers.Tier2.Default.Loadout.NoThrowableChance = 0;
    (*this).Tiers.Tier2.Default.Loadout.ThrowablePool.Empty();
    (*TBaseStructure<FGameplayTag>::Get()->FindPropertyByName("TagName")->ContainerPtrToValuePtr<FName>(&(*this).Tiers.Tier2.Default.Loadout.EmptyWeaponTag, 0)) = TEXT("Item.Wieldable.Weapon");
    (*this).Tiers.Tier2.Default.Loadout.ShowNoThrowableBool = 0;
    (*TBaseStructure<FGameplayTag>::Get()->FindPropertyByName("TagName")->ContainerPtrToValuePtr<FName>(&(*this).Tiers.Tier2.Default.Specialization, 0)) = TEXT("AI.Specialization.Default");
    (*this).Tiers.Tier2.Heavy.Stats.HP.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier2.Heavy.Stats.HP.Value = 2.800000000e+02f;
    (*this).Tiers.Tier2.Heavy.Stats.HP.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier2.Heavy.Stats.HP.bOverloadValue = false;
    (*this).Tiers.Tier2.Heavy.Stats.Shield.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier2.Heavy.Stats.Shield.Value = 0.000000000e+00f;
    (*this).Tiers.Tier2.Heavy.Stats.Shield.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier2.Heavy.Stats.Shield.bOverloadValue = false;
    (*this).Tiers.Tier2.Heavy.Stats.WeaponDamage.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier2.Heavy.Stats.WeaponDamage.Value = 1.000000000e+00f;
    (*this).Tiers.Tier2.Heavy.Stats.WeaponDamage.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier2.Heavy.Stats.WeaponDamage.bOverloadValue = false;
    (*this).Tiers.Tier2.Heavy.Stats.MeleeDamage.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier2.Heavy.Stats.MeleeDamage.Value = 1.000000000e+00f;
    (*this).Tiers.Tier2.Heavy.Stats.MeleeDamage.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier2.Heavy.Stats.MeleeDamage.bOverloadValue = false;
    (*this).Tiers.Tier2.Heavy.Stats.WeaponDispersion.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier2.Heavy.Stats.WeaponDispersion.Value = 1.000000000e+00f;
    (*this).Tiers.Tier2.Heavy.Stats.WeaponDispersion.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier2.Heavy.Stats.WeaponDispersion.bOverloadValue = false;
    (*this).Tiers.Tier2.Heavy.Stats.MovementSpeed.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier2.Heavy.Stats.MovementSpeed.Value = 1.000000000e+00f;
    (*this).Tiers.Tier2.Heavy.Stats.MovementSpeed.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier2.Heavy.Stats.MovementSpeed.bOverloadValue = false;
    (*this).Tiers.Tier2.Heavy.Stats.CoverStickiness.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier2.Heavy.Stats.CoverStickiness.Value = 5.000000000e-01f;
    (*this).Tiers.Tier2.Heavy.Stats.CoverStickiness.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier2.Heavy.Stats.CoverStickiness.bOverloadValue = false;
    (*this).Tiers.Tier2.Heavy.Stats.ReactionIntensity.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier2.Heavy.Stats.ReactionIntensity.Value = 5.000000000e-01f;
    (*this).Tiers.Tier2.Heavy.Stats.ReactionIntensity.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier2.Heavy.Stats.ReactionIntensity.bOverloadValue = false;
    (*this).Tiers.Tier2.Heavy.Enabled = true;
    (*this).Tiers.Tier2.Heavy.Character.Controller = nullptr;
    (*this).Tiers.Tier2.Heavy.Character.Pawns.Empty();
    (*this).Tiers.Tier2.Heavy.Loadout.WeaponPool.PrimaryWeapons.Empty();
    (*this).Tiers.Tier2.Heavy.Loadout.WeaponPool.SecondaryWeapons.Empty();
    (*this).Tiers.Tier2.Heavy.Loadout.WeaponPool.MeleeWeapons.Empty();
    (*this).Tiers.Tier2.Heavy.Loadout.WeaponProbability.Empty();
    (*this).Tiers.Tier2.Heavy.Loadout.NoThrowableChance = 0;
    (*this).Tiers.Tier2.Heavy.Loadout.ThrowablePool.Empty();
    (*TBaseStructure<FGameplayTag>::Get()->FindPropertyByName("TagName")->ContainerPtrToValuePtr<FName>(&(*this).Tiers.Tier2.Heavy.Loadout.EmptyWeaponTag, 0)) = TEXT("Item.Wieldable.Weapon");
    (*this).Tiers.Tier2.Heavy.Loadout.ShowNoThrowableBool = 0;
    (*TBaseStructure<FGameplayTag>::Get()->FindPropertyByName("TagName")->ContainerPtrToValuePtr<FName>(&(*this).Tiers.Tier2.Heavy.Specialization, 0)) = TEXT("AI.Specialization.Special.Heavy");
    (*this).Tiers.Tier3.Default.Stats.HP.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier3.Default.Stats.HP.Value = 2.800000000e+02f;
    (*this).Tiers.Tier3.Default.Stats.HP.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier3.Default.Stats.HP.bOverloadValue = false;
    (*this).Tiers.Tier3.Default.Stats.Shield.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier3.Default.Stats.Shield.Value = 0.000000000e+00f;
    (*this).Tiers.Tier3.Default.Stats.Shield.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier3.Default.Stats.Shield.bOverloadValue = false;
    (*this).Tiers.Tier3.Default.Stats.WeaponDamage.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier3.Default.Stats.WeaponDamage.Value = 1.000000000e+00f;
    (*this).Tiers.Tier3.Default.Stats.WeaponDamage.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier3.Default.Stats.WeaponDamage.bOverloadValue = false;
    (*this).Tiers.Tier3.Default.Stats.MeleeDamage.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier3.Default.Stats.MeleeDamage.Value = 1.000000000e+00f;
    (*this).Tiers.Tier3.Default.Stats.MeleeDamage.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier3.Default.Stats.MeleeDamage.bOverloadValue = false;
    (*this).Tiers.Tier3.Default.Stats.WeaponDispersion.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier3.Default.Stats.WeaponDispersion.Value = 1.000000000e+00f;
    (*this).Tiers.Tier3.Default.Stats.WeaponDispersion.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier3.Default.Stats.WeaponDispersion.bOverloadValue = false;
    (*this).Tiers.Tier3.Default.Stats.MovementSpeed.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier3.Default.Stats.MovementSpeed.Value = 1.000000000e+00f;
    (*this).Tiers.Tier3.Default.Stats.MovementSpeed.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier3.Default.Stats.MovementSpeed.bOverloadValue = false;
    (*this).Tiers.Tier3.Default.Stats.CoverStickiness.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier3.Default.Stats.CoverStickiness.Value = 5.000000000e-01f;
    (*this).Tiers.Tier3.Default.Stats.CoverStickiness.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier3.Default.Stats.CoverStickiness.bOverloadValue = false;
    (*this).Tiers.Tier3.Default.Stats.ReactionIntensity.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier3.Default.Stats.ReactionIntensity.Value = 5.000000000e-01f;
    (*this).Tiers.Tier3.Default.Stats.ReactionIntensity.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier3.Default.Stats.ReactionIntensity.bOverloadValue = false;
    (*this).Tiers.Tier3.Default.Enabled = true;
    (*this).Tiers.Tier3.Default.Character.Controller = nullptr;
    (*this).Tiers.Tier3.Default.Character.Pawns.Empty();
    (*this).Tiers.Tier3.Default.Loadout.WeaponPool.PrimaryWeapons.Empty();
    (*this).Tiers.Tier3.Default.Loadout.WeaponPool.SecondaryWeapons.Empty();
    (*this).Tiers.Tier3.Default.Loadout.WeaponPool.MeleeWeapons.Empty();
    (*this).Tiers.Tier3.Default.Loadout.WeaponProbability.Empty();
    (*this).Tiers.Tier3.Default.Loadout.NoThrowableChance = 0;
    (*this).Tiers.Tier3.Default.Loadout.ThrowablePool.Empty();
    (*TBaseStructure<FGameplayTag>::Get()->FindPropertyByName("TagName")->ContainerPtrToValuePtr<FName>(&(*this).Tiers.Tier3.Default.Loadout.EmptyWeaponTag, 0)) = TEXT("Item.Wieldable.Weapon");
    (*this).Tiers.Tier3.Default.Loadout.ShowNoThrowableBool = 0;
    (*TBaseStructure<FGameplayTag>::Get()->FindPropertyByName("TagName")->ContainerPtrToValuePtr<FName>(&(*this).Tiers.Tier3.Default.Specialization, 0)) = TEXT("AI.Specialization.Default");
    (*this).Tiers.Tier3.Heavy.Stats.HP.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier3.Heavy.Stats.HP.Value = 2.800000000e+02f;
    (*this).Tiers.Tier3.Heavy.Stats.HP.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier3.Heavy.Stats.HP.bOverloadValue = false;
    (*this).Tiers.Tier3.Heavy.Stats.Shield.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier3.Heavy.Stats.Shield.Value = 0.000000000e+00f;
    (*this).Tiers.Tier3.Heavy.Stats.Shield.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier3.Heavy.Stats.Shield.bOverloadValue = false;
    (*this).Tiers.Tier3.Heavy.Stats.WeaponDamage.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier3.Heavy.Stats.WeaponDamage.Value = 1.000000000e+00f;
    (*this).Tiers.Tier3.Heavy.Stats.WeaponDamage.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier3.Heavy.Stats.WeaponDamage.bOverloadValue = false;
    (*this).Tiers.Tier3.Heavy.Stats.MeleeDamage.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier3.Heavy.Stats.MeleeDamage.Value = 1.000000000e+00f;
    (*this).Tiers.Tier3.Heavy.Stats.MeleeDamage.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier3.Heavy.Stats.MeleeDamage.bOverloadValue = false;
    (*this).Tiers.Tier3.Heavy.Stats.WeaponDispersion.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier3.Heavy.Stats.WeaponDispersion.Value = 1.000000000e+00f;
    (*this).Tiers.Tier3.Heavy.Stats.WeaponDispersion.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier3.Heavy.Stats.WeaponDispersion.bOverloadValue = false;
    (*this).Tiers.Tier3.Heavy.Stats.MovementSpeed.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier3.Heavy.Stats.MovementSpeed.Value = 1.000000000e+00f;
    (*this).Tiers.Tier3.Heavy.Stats.MovementSpeed.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier3.Heavy.Stats.MovementSpeed.bOverloadValue = false;
    (*this).Tiers.Tier3.Heavy.Stats.CoverStickiness.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier3.Heavy.Stats.CoverStickiness.Value = 5.000000000e-01f;
    (*this).Tiers.Tier3.Heavy.Stats.CoverStickiness.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier3.Heavy.Stats.CoverStickiness.bOverloadValue = false;
    (*this).Tiers.Tier3.Heavy.Stats.ReactionIntensity.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier3.Heavy.Stats.ReactionIntensity.Value = 5.000000000e-01f;
    (*this).Tiers.Tier3.Heavy.Stats.ReactionIntensity.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier3.Heavy.Stats.ReactionIntensity.bOverloadValue = false;
    (*this).Tiers.Tier3.Heavy.Enabled = true;
    (*this).Tiers.Tier3.Heavy.Character.Controller = nullptr;
    (*this).Tiers.Tier3.Heavy.Character.Pawns.Empty();
    (*this).Tiers.Tier3.Heavy.Loadout.WeaponPool.PrimaryWeapons.Empty();
    (*this).Tiers.Tier3.Heavy.Loadout.WeaponPool.SecondaryWeapons.Empty();
    (*this).Tiers.Tier3.Heavy.Loadout.WeaponPool.MeleeWeapons.Empty();
    (*this).Tiers.Tier3.Heavy.Loadout.WeaponProbability.Empty();
    (*this).Tiers.Tier3.Heavy.Loadout.NoThrowableChance = 0;
    (*this).Tiers.Tier3.Heavy.Loadout.ThrowablePool.Empty();
    (*TBaseStructure<FGameplayTag>::Get()->FindPropertyByName("TagName")->ContainerPtrToValuePtr<FName>(&(*this).Tiers.Tier3.Heavy.Loadout.EmptyWeaponTag, 0)) = TEXT("Item.Wieldable.Weapon");
    (*this).Tiers.Tier3.Heavy.Loadout.ShowNoThrowableBool = 0;
    (*TBaseStructure<FGameplayTag>::Get()->FindPropertyByName("TagName")->ContainerPtrToValuePtr<FName>(&(*this).Tiers.Tier3.Heavy.Specialization, 0)) = TEXT("AI.Specialization.Special.Heavy");
    (*this).Tiers.Special.Default.Stats.HP.Overload = 0.000000000e+00f;
    (*this).Tiers.Special.Default.Stats.HP.Value = 2.800000000e+02f;
    (*this).Tiers.Special.Default.Stats.HP.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Special.Default.Stats.HP.bOverloadValue = false;
    (*this).Tiers.Special.Default.Stats.Shield.Overload = 0.000000000e+00f;
    (*this).Tiers.Special.Default.Stats.Shield.Value = 0.000000000e+00f;
    (*this).Tiers.Special.Default.Stats.Shield.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Special.Default.Stats.Shield.bOverloadValue = false;
    (*this).Tiers.Special.Default.Stats.WeaponDamage.Overload = 0.000000000e+00f;
    (*this).Tiers.Special.Default.Stats.WeaponDamage.Value = 1.000000000e+00f;
    (*this).Tiers.Special.Default.Stats.WeaponDamage.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Special.Default.Stats.WeaponDamage.bOverloadValue = false;
    (*this).Tiers.Special.Default.Stats.MeleeDamage.Overload = 0.000000000e+00f;
    (*this).Tiers.Special.Default.Stats.MeleeDamage.Value = 1.000000000e+00f;
    (*this).Tiers.Special.Default.Stats.MeleeDamage.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Special.Default.Stats.MeleeDamage.bOverloadValue = false;
    (*this).Tiers.Special.Default.Stats.WeaponDispersion.Overload = 0.000000000e+00f;
    (*this).Tiers.Special.Default.Stats.WeaponDispersion.Value = 1.000000000e+00f;
    (*this).Tiers.Special.Default.Stats.WeaponDispersion.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Special.Default.Stats.WeaponDispersion.bOverloadValue = false;
    (*this).Tiers.Special.Default.Stats.MovementSpeed.Overload = 0.000000000e+00f;
    (*this).Tiers.Special.Default.Stats.MovementSpeed.Value = 1.000000000e+00f;
    (*this).Tiers.Special.Default.Stats.MovementSpeed.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Special.Default.Stats.MovementSpeed.bOverloadValue = false;
    (*this).Tiers.Special.Default.Stats.CoverStickiness.Overload = 0.000000000e+00f;
    (*this).Tiers.Special.Default.Stats.CoverStickiness.Value = 5.000000000e-01f;
    (*this).Tiers.Special.Default.Stats.CoverStickiness.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Special.Default.Stats.CoverStickiness.bOverloadValue = false;
    (*this).Tiers.Special.Default.Stats.ReactionIntensity.Overload = 0.000000000e+00f;
    (*this).Tiers.Special.Default.Stats.ReactionIntensity.Value = 5.000000000e-01f;
    (*this).Tiers.Special.Default.Stats.ReactionIntensity.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Special.Default.Stats.ReactionIntensity.bOverloadValue = false;
    (*this).Tiers.Special.Default.Enabled = true;
    (*this).Tiers.Special.Default.Character.Controller = nullptr;
    (*this).Tiers.Special.Default.Character.Pawns.Empty();
    (*this).Tiers.Special.Default.Loadout.WeaponPool.PrimaryWeapons.Empty();
    (*this).Tiers.Special.Default.Loadout.WeaponPool.SecondaryWeapons.Empty();
    (*this).Tiers.Special.Default.Loadout.WeaponPool.MeleeWeapons.Empty();
    (*this).Tiers.Special.Default.Loadout.WeaponProbability.Empty();
    (*this).Tiers.Special.Default.Loadout.NoThrowableChance = 0;
    (*this).Tiers.Special.Default.Loadout.ThrowablePool.Empty();
    (*TBaseStructure<FGameplayTag>::Get()->FindPropertyByName("TagName")->ContainerPtrToValuePtr<FName>(&(*this).Tiers.Special.Default.Loadout.EmptyWeaponTag, 0)) = TEXT("Item.Wieldable.Weapon");
    (*this).Tiers.Special.Default.Loadout.ShowNoThrowableBool = 0;
    (*TBaseStructure<FGameplayTag>::Get()->FindPropertyByName("TagName")->ContainerPtrToValuePtr<FName>(&(*this).Tiers.Special.Default.Specialization, 0)) = TEXT("AI.Specialization.Default");
    (*this).Tiers.Special.Heavy.Stats.HP.Overload = 0.000000000e+00f;
    (*this).Tiers.Special.Heavy.Stats.HP.Value = 2.800000000e+02f;
    (*this).Tiers.Special.Heavy.Stats.HP.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Special.Heavy.Stats.HP.bOverloadValue = false;
    (*this).Tiers.Special.Heavy.Stats.Shield.Overload = 0.000000000e+00f;
    (*this).Tiers.Special.Heavy.Stats.Shield.Value = 0.000000000e+00f;
    (*this).Tiers.Special.Heavy.Stats.Shield.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Special.Heavy.Stats.Shield.bOverloadValue = false;
    (*this).Tiers.Special.Heavy.Stats.WeaponDamage.Overload = 0.000000000e+00f;
    (*this).Tiers.Special.Heavy.Stats.WeaponDamage.Value = 1.000000000e+00f;
    (*this).Tiers.Special.Heavy.Stats.WeaponDamage.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Special.Heavy.Stats.WeaponDamage.bOverloadValue = false;
    (*this).Tiers.Special.Heavy.Stats.MeleeDamage.Overload = 0.000000000e+00f;
    (*this).Tiers.Special.Heavy.Stats.MeleeDamage.Value = 1.000000000e+00f;
    (*this).Tiers.Special.Heavy.Stats.MeleeDamage.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Special.Heavy.Stats.MeleeDamage.bOverloadValue = false;
    (*this).Tiers.Special.Heavy.Stats.WeaponDispersion.Overload = 0.000000000e+00f;
    (*this).Tiers.Special.Heavy.Stats.WeaponDispersion.Value = 1.000000000e+00f;
    (*this).Tiers.Special.Heavy.Stats.WeaponDispersion.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Special.Heavy.Stats.WeaponDispersion.bOverloadValue = false;
    (*this).Tiers.Special.Heavy.Stats.MovementSpeed.Overload = 0.000000000e+00f;
    (*this).Tiers.Special.Heavy.Stats.MovementSpeed.Value = 1.000000000e+00f;
    (*this).Tiers.Special.Heavy.Stats.MovementSpeed.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Special.Heavy.Stats.MovementSpeed.bOverloadValue = false;
    (*this).Tiers.Special.Heavy.Stats.CoverStickiness.Overload = 0.000000000e+00f;
    (*this).Tiers.Special.Heavy.Stats.CoverStickiness.Value = 5.000000000e-01f;
    (*this).Tiers.Special.Heavy.Stats.CoverStickiness.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Special.Heavy.Stats.CoverStickiness.bOverloadValue = false;
    (*this).Tiers.Special.Heavy.Stats.ReactionIntensity.Overload = 0.000000000e+00f;
    (*this).Tiers.Special.Heavy.Stats.ReactionIntensity.Value = 5.000000000e-01f;
    (*this).Tiers.Special.Heavy.Stats.ReactionIntensity.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Special.Heavy.Stats.ReactionIntensity.bOverloadValue = false;
    (*this).Tiers.Special.Heavy.Enabled = true;
    (*this).Tiers.Special.Heavy.Character.Controller = nullptr;
    (*this).Tiers.Special.Heavy.Character.Pawns.Empty();
    (*this).Tiers.Special.Heavy.Loadout.WeaponPool.PrimaryWeapons.Empty();
    (*this).Tiers.Special.Heavy.Loadout.WeaponPool.SecondaryWeapons.Empty();
    (*this).Tiers.Special.Heavy.Loadout.WeaponPool.MeleeWeapons.Empty();
    (*this).Tiers.Special.Heavy.Loadout.WeaponProbability.Empty();
    (*this).Tiers.Special.Heavy.Loadout.NoThrowableChance = 0;
    (*this).Tiers.Special.Heavy.Loadout.ThrowablePool.Empty();
    (*TBaseStructure<FGameplayTag>::Get()->FindPropertyByName("TagName")->ContainerPtrToValuePtr<FName>(&(*this).Tiers.Special.Heavy.Loadout.EmptyWeaponTag, 0)) = TEXT("Item.Wieldable.Weapon");
    (*this).Tiers.Special.Heavy.Loadout.ShowNoThrowableBool = 0;
    (*TBaseStructure<FGameplayTag>::Get()->FindPropertyByName("TagName")->ContainerPtrToValuePtr<FName>(&(*this).Tiers.Special.Heavy.Specialization, 0)) = TEXT("AI.Specialization.Special.Heavy");
    (*this).Tiers.TierSelection = 0;
    (*this).DefaultStats.HP = 2.800000000e+02f;
    (*this).DefaultStats.Shield = 0.000000000e+00f;
    (*this).DefaultStats.WeaponDamage = 1.000000000e+00f;
    (*this).DefaultStats.MeleeDamage = 1.000000000e+00f;
    (*this).DefaultStats.WeaponDispersion = 1.000000000e+00f;
    (*this).DefaultStats.MovementSpeed = 1.000000000e+00f;
    (*this).DefaultStats.CoverPreset = EIGS_CoverPreset::AICS_None;
    (*this).DefaultStats.CoverStickiness = 5.000000000e-01f;
    (*this).DefaultStats.ReactionIntensity = 5.000000000e-01f;
    (*this).TeamSide = EIGS_TeamSideEnum::TS_HeistersBackup;
}

