#include "IGS_AIBackupTiersDef.h"
#include "GameplayTagContainer.h"

FIGS_AIBackupTiersDef::FIGS_AIBackupTiersDef() {
    (*this).Tier1.Default.Stats.HP.Overload = 0.000000000e+00f;
    (*this).Tier1.Default.Stats.HP.Value = 0.000000000e+00f;
    (*this).Tier1.Default.Stats.HP.Multiplier = 1.000000000e+00f;
    (*this).Tier1.Default.Stats.HP.bOverloadValue = false;
    (*this).Tier1.Default.Stats.Shield.Overload = 0.000000000e+00f;
    (*this).Tier1.Default.Stats.Shield.Value = 0.000000000e+00f;
    (*this).Tier1.Default.Stats.Shield.Multiplier = 1.000000000e+00f;
    (*this).Tier1.Default.Stats.Shield.bOverloadValue = false;
    (*this).Tier1.Default.Stats.WeaponDamage.Overload = 0.000000000e+00f;
    (*this).Tier1.Default.Stats.WeaponDamage.Value = 0.000000000e+00f;
    (*this).Tier1.Default.Stats.WeaponDamage.Multiplier = 1.000000000e+00f;
    (*this).Tier1.Default.Stats.WeaponDamage.bOverloadValue = false;
    (*this).Tier1.Default.Stats.MeleeDamage.Overload = 0.000000000e+00f;
    (*this).Tier1.Default.Stats.MeleeDamage.Value = 0.000000000e+00f;
    (*this).Tier1.Default.Stats.MeleeDamage.Multiplier = 1.000000000e+00f;
    (*this).Tier1.Default.Stats.MeleeDamage.bOverloadValue = false;
    (*this).Tier1.Default.Stats.WeaponDispersion.Overload = 0.000000000e+00f;
    (*this).Tier1.Default.Stats.WeaponDispersion.Value = 0.000000000e+00f;
    (*this).Tier1.Default.Stats.WeaponDispersion.Multiplier = 1.000000000e+00f;
    (*this).Tier1.Default.Stats.WeaponDispersion.bOverloadValue = false;
    (*this).Tier1.Default.Stats.MovementSpeed.Overload = 0.000000000e+00f;
    (*this).Tier1.Default.Stats.MovementSpeed.Value = 0.000000000e+00f;
    (*this).Tier1.Default.Stats.MovementSpeed.Multiplier = 1.000000000e+00f;
    (*this).Tier1.Default.Stats.MovementSpeed.bOverloadValue = false;
    (*this).Tier1.Default.Stats.CoverStickiness.Overload = 0.000000000e+00f;
    (*this).Tier1.Default.Stats.CoverStickiness.Value = 0.000000000e+00f;
    (*this).Tier1.Default.Stats.CoverStickiness.Multiplier = 1.000000000e+00f;
    (*this).Tier1.Default.Stats.CoverStickiness.bOverloadValue = false;
    (*this).Tier1.Default.Stats.ReactionIntensity.Overload = 0.000000000e+00f;
    (*this).Tier1.Default.Stats.ReactionIntensity.Value = 0.000000000e+00f;
    (*this).Tier1.Default.Stats.ReactionIntensity.Multiplier = 1.000000000e+00f;
    (*this).Tier1.Default.Stats.ReactionIntensity.bOverloadValue = false;
    (*this).Tier1.Default.Enabled = true;
    (*this).Tier1.Default.Character.Controller = nullptr;
    (*this).Tier1.Default.Character.Pawns.Empty();
    (*this).Tier1.Default.Loadout.WeaponPool.PrimaryWeapons.Empty();
    (*this).Tier1.Default.Loadout.WeaponPool.SecondaryWeapons.Empty();
    (*this).Tier1.Default.Loadout.WeaponPool.MeleeWeapons.Empty();
    (*this).Tier1.Default.Loadout.WeaponProbability.Empty();
    (*this).Tier1.Default.Loadout.NoThrowableChance = 0;
    (*this).Tier1.Default.Loadout.ThrowablePool.Empty();
    (*TBaseStructure<FGameplayTag>::Get()->FindPropertyByName("TagName")->ContainerPtrToValuePtr<FName>(&(*this).Tier1.Default.Loadout.EmptyWeaponTag, 0)) = TEXT("Item.Wieldable.Weapon");
    (*this).Tier1.Default.Loadout.ShowNoThrowableBool = 0;
    (*TBaseStructure<FGameplayTag>::Get()->FindPropertyByName("TagName")->ContainerPtrToValuePtr<FName>(&(*this).Tier1.Default.Specialization, 0)) = TEXT("AI.Specialization.Default");
    (*this).Tier1.Heavy.Stats.HP.Overload = 0.000000000e+00f;
    (*this).Tier1.Heavy.Stats.HP.Value = 0.000000000e+00f;
    (*this).Tier1.Heavy.Stats.HP.Multiplier = 1.000000000e+00f;
    (*this).Tier1.Heavy.Stats.HP.bOverloadValue = false;
    (*this).Tier1.Heavy.Stats.Shield.Overload = 0.000000000e+00f;
    (*this).Tier1.Heavy.Stats.Shield.Value = 0.000000000e+00f;
    (*this).Tier1.Heavy.Stats.Shield.Multiplier = 1.000000000e+00f;
    (*this).Tier1.Heavy.Stats.Shield.bOverloadValue = false;
    (*this).Tier1.Heavy.Stats.WeaponDamage.Overload = 0.000000000e+00f;
    (*this).Tier1.Heavy.Stats.WeaponDamage.Value = 0.000000000e+00f;
    (*this).Tier1.Heavy.Stats.WeaponDamage.Multiplier = 1.000000000e+00f;
    (*this).Tier1.Heavy.Stats.WeaponDamage.bOverloadValue = false;
    (*this).Tier1.Heavy.Stats.MeleeDamage.Overload = 0.000000000e+00f;
    (*this).Tier1.Heavy.Stats.MeleeDamage.Value = 0.000000000e+00f;
    (*this).Tier1.Heavy.Stats.MeleeDamage.Multiplier = 1.000000000e+00f;
    (*this).Tier1.Heavy.Stats.MeleeDamage.bOverloadValue = false;
    (*this).Tier1.Heavy.Stats.WeaponDispersion.Overload = 0.000000000e+00f;
    (*this).Tier1.Heavy.Stats.WeaponDispersion.Value = 0.000000000e+00f;
    (*this).Tier1.Heavy.Stats.WeaponDispersion.Multiplier = 1.000000000e+00f;
    (*this).Tier1.Heavy.Stats.WeaponDispersion.bOverloadValue = false;
    (*this).Tier1.Heavy.Stats.MovementSpeed.Overload = 0.000000000e+00f;
    (*this).Tier1.Heavy.Stats.MovementSpeed.Value = 0.000000000e+00f;
    (*this).Tier1.Heavy.Stats.MovementSpeed.Multiplier = 1.000000000e+00f;
    (*this).Tier1.Heavy.Stats.MovementSpeed.bOverloadValue = false;
    (*this).Tier1.Heavy.Stats.CoverStickiness.Overload = 0.000000000e+00f;
    (*this).Tier1.Heavy.Stats.CoverStickiness.Value = 0.000000000e+00f;
    (*this).Tier1.Heavy.Stats.CoverStickiness.Multiplier = 1.000000000e+00f;
    (*this).Tier1.Heavy.Stats.CoverStickiness.bOverloadValue = false;
    (*this).Tier1.Heavy.Stats.ReactionIntensity.Overload = 0.000000000e+00f;
    (*this).Tier1.Heavy.Stats.ReactionIntensity.Value = 0.000000000e+00f;
    (*this).Tier1.Heavy.Stats.ReactionIntensity.Multiplier = 1.000000000e+00f;
    (*this).Tier1.Heavy.Stats.ReactionIntensity.bOverloadValue = false;
    (*this).Tier1.Heavy.Enabled = true;
    (*this).Tier1.Heavy.Character.Controller = nullptr;
    (*this).Tier1.Heavy.Character.Pawns.Empty();
    (*this).Tier1.Heavy.Loadout.WeaponPool.PrimaryWeapons.Empty();
    (*this).Tier1.Heavy.Loadout.WeaponPool.SecondaryWeapons.Empty();
    (*this).Tier1.Heavy.Loadout.WeaponPool.MeleeWeapons.Empty();
    (*this).Tier1.Heavy.Loadout.WeaponProbability.Empty();
    (*this).Tier1.Heavy.Loadout.NoThrowableChance = 0;
    (*this).Tier1.Heavy.Loadout.ThrowablePool.Empty();
    (*TBaseStructure<FGameplayTag>::Get()->FindPropertyByName("TagName")->ContainerPtrToValuePtr<FName>(&(*this).Tier1.Heavy.Loadout.EmptyWeaponTag, 0)) = TEXT("Item.Wieldable.Weapon");
    (*this).Tier1.Heavy.Loadout.ShowNoThrowableBool = 0;
    (*TBaseStructure<FGameplayTag>::Get()->FindPropertyByName("TagName")->ContainerPtrToValuePtr<FName>(&(*this).Tier1.Heavy.Specialization, 0)) = TEXT("AI.Specialization.Special.Heavy");
    (*this).Tier2.Default.Stats.HP.Overload = 0.000000000e+00f;
    (*this).Tier2.Default.Stats.HP.Value = 0.000000000e+00f;
    (*this).Tier2.Default.Stats.HP.Multiplier = 1.000000000e+00f;
    (*this).Tier2.Default.Stats.HP.bOverloadValue = false;
    (*this).Tier2.Default.Stats.Shield.Overload = 0.000000000e+00f;
    (*this).Tier2.Default.Stats.Shield.Value = 0.000000000e+00f;
    (*this).Tier2.Default.Stats.Shield.Multiplier = 1.000000000e+00f;
    (*this).Tier2.Default.Stats.Shield.bOverloadValue = false;
    (*this).Tier2.Default.Stats.WeaponDamage.Overload = 0.000000000e+00f;
    (*this).Tier2.Default.Stats.WeaponDamage.Value = 0.000000000e+00f;
    (*this).Tier2.Default.Stats.WeaponDamage.Multiplier = 1.000000000e+00f;
    (*this).Tier2.Default.Stats.WeaponDamage.bOverloadValue = false;
    (*this).Tier2.Default.Stats.MeleeDamage.Overload = 0.000000000e+00f;
    (*this).Tier2.Default.Stats.MeleeDamage.Value = 0.000000000e+00f;
    (*this).Tier2.Default.Stats.MeleeDamage.Multiplier = 1.000000000e+00f;
    (*this).Tier2.Default.Stats.MeleeDamage.bOverloadValue = false;
    (*this).Tier2.Default.Stats.WeaponDispersion.Overload = 0.000000000e+00f;
    (*this).Tier2.Default.Stats.WeaponDispersion.Value = 0.000000000e+00f;
    (*this).Tier2.Default.Stats.WeaponDispersion.Multiplier = 1.000000000e+00f;
    (*this).Tier2.Default.Stats.WeaponDispersion.bOverloadValue = false;
    (*this).Tier2.Default.Stats.MovementSpeed.Overload = 0.000000000e+00f;
    (*this).Tier2.Default.Stats.MovementSpeed.Value = 0.000000000e+00f;
    (*this).Tier2.Default.Stats.MovementSpeed.Multiplier = 1.000000000e+00f;
    (*this).Tier2.Default.Stats.MovementSpeed.bOverloadValue = false;
    (*this).Tier2.Default.Stats.CoverStickiness.Overload = 0.000000000e+00f;
    (*this).Tier2.Default.Stats.CoverStickiness.Value = 0.000000000e+00f;
    (*this).Tier2.Default.Stats.CoverStickiness.Multiplier = 1.000000000e+00f;
    (*this).Tier2.Default.Stats.CoverStickiness.bOverloadValue = false;
    (*this).Tier2.Default.Stats.ReactionIntensity.Overload = 0.000000000e+00f;
    (*this).Tier2.Default.Stats.ReactionIntensity.Value = 0.000000000e+00f;
    (*this).Tier2.Default.Stats.ReactionIntensity.Multiplier = 1.000000000e+00f;
    (*this).Tier2.Default.Stats.ReactionIntensity.bOverloadValue = false;
    (*this).Tier2.Default.Enabled = true;
    (*this).Tier2.Default.Character.Controller = nullptr;
    (*this).Tier2.Default.Character.Pawns.Empty();
    (*this).Tier2.Default.Loadout.WeaponPool.PrimaryWeapons.Empty();
    (*this).Tier2.Default.Loadout.WeaponPool.SecondaryWeapons.Empty();
    (*this).Tier2.Default.Loadout.WeaponPool.MeleeWeapons.Empty();
    (*this).Tier2.Default.Loadout.WeaponProbability.Empty();
    (*this).Tier2.Default.Loadout.NoThrowableChance = 0;
    (*this).Tier2.Default.Loadout.ThrowablePool.Empty();
    (*TBaseStructure<FGameplayTag>::Get()->FindPropertyByName("TagName")->ContainerPtrToValuePtr<FName>(&(*this).Tier2.Default.Loadout.EmptyWeaponTag, 0)) = TEXT("Item.Wieldable.Weapon");
    (*this).Tier2.Default.Loadout.ShowNoThrowableBool = 0;
    (*TBaseStructure<FGameplayTag>::Get()->FindPropertyByName("TagName")->ContainerPtrToValuePtr<FName>(&(*this).Tier2.Default.Specialization, 0)) = TEXT("AI.Specialization.Default");
    (*this).Tier2.Heavy.Stats.HP.Overload = 0.000000000e+00f;
    (*this).Tier2.Heavy.Stats.HP.Value = 0.000000000e+00f;
    (*this).Tier2.Heavy.Stats.HP.Multiplier = 1.000000000e+00f;
    (*this).Tier2.Heavy.Stats.HP.bOverloadValue = false;
    (*this).Tier2.Heavy.Stats.Shield.Overload = 0.000000000e+00f;
    (*this).Tier2.Heavy.Stats.Shield.Value = 0.000000000e+00f;
    (*this).Tier2.Heavy.Stats.Shield.Multiplier = 1.000000000e+00f;
    (*this).Tier2.Heavy.Stats.Shield.bOverloadValue = false;
    (*this).Tier2.Heavy.Stats.WeaponDamage.Overload = 0.000000000e+00f;
    (*this).Tier2.Heavy.Stats.WeaponDamage.Value = 0.000000000e+00f;
    (*this).Tier2.Heavy.Stats.WeaponDamage.Multiplier = 1.000000000e+00f;
    (*this).Tier2.Heavy.Stats.WeaponDamage.bOverloadValue = false;
    (*this).Tier2.Heavy.Stats.MeleeDamage.Overload = 0.000000000e+00f;
    (*this).Tier2.Heavy.Stats.MeleeDamage.Value = 0.000000000e+00f;
    (*this).Tier2.Heavy.Stats.MeleeDamage.Multiplier = 1.000000000e+00f;
    (*this).Tier2.Heavy.Stats.MeleeDamage.bOverloadValue = false;
    (*this).Tier2.Heavy.Stats.WeaponDispersion.Overload = 0.000000000e+00f;
    (*this).Tier2.Heavy.Stats.WeaponDispersion.Value = 0.000000000e+00f;
    (*this).Tier2.Heavy.Stats.WeaponDispersion.Multiplier = 1.000000000e+00f;
    (*this).Tier2.Heavy.Stats.WeaponDispersion.bOverloadValue = false;
    (*this).Tier2.Heavy.Stats.MovementSpeed.Overload = 0.000000000e+00f;
    (*this).Tier2.Heavy.Stats.MovementSpeed.Value = 0.000000000e+00f;
    (*this).Tier2.Heavy.Stats.MovementSpeed.Multiplier = 1.000000000e+00f;
    (*this).Tier2.Heavy.Stats.MovementSpeed.bOverloadValue = false;
    (*this).Tier2.Heavy.Stats.CoverStickiness.Overload = 0.000000000e+00f;
    (*this).Tier2.Heavy.Stats.CoverStickiness.Value = 0.000000000e+00f;
    (*this).Tier2.Heavy.Stats.CoverStickiness.Multiplier = 1.000000000e+00f;
    (*this).Tier2.Heavy.Stats.CoverStickiness.bOverloadValue = false;
    (*this).Tier2.Heavy.Stats.ReactionIntensity.Overload = 0.000000000e+00f;
    (*this).Tier2.Heavy.Stats.ReactionIntensity.Value = 0.000000000e+00f;
    (*this).Tier2.Heavy.Stats.ReactionIntensity.Multiplier = 1.000000000e+00f;
    (*this).Tier2.Heavy.Stats.ReactionIntensity.bOverloadValue = false;
    (*this).Tier2.Heavy.Enabled = true;
    (*this).Tier2.Heavy.Character.Controller = nullptr;
    (*this).Tier2.Heavy.Character.Pawns.Empty();
    (*this).Tier2.Heavy.Loadout.WeaponPool.PrimaryWeapons.Empty();
    (*this).Tier2.Heavy.Loadout.WeaponPool.SecondaryWeapons.Empty();
    (*this).Tier2.Heavy.Loadout.WeaponPool.MeleeWeapons.Empty();
    (*this).Tier2.Heavy.Loadout.WeaponProbability.Empty();
    (*this).Tier2.Heavy.Loadout.NoThrowableChance = 0;
    (*this).Tier2.Heavy.Loadout.ThrowablePool.Empty();
    (*TBaseStructure<FGameplayTag>::Get()->FindPropertyByName("TagName")->ContainerPtrToValuePtr<FName>(&(*this).Tier2.Heavy.Loadout.EmptyWeaponTag, 0)) = TEXT("Item.Wieldable.Weapon");
    (*this).Tier2.Heavy.Loadout.ShowNoThrowableBool = 0;
    (*TBaseStructure<FGameplayTag>::Get()->FindPropertyByName("TagName")->ContainerPtrToValuePtr<FName>(&(*this).Tier2.Heavy.Specialization, 0)) = TEXT("AI.Specialization.Special.Heavy");
    (*this).Tier3.Default.Stats.HP.Overload = 0.000000000e+00f;
    (*this).Tier3.Default.Stats.HP.Value = 0.000000000e+00f;
    (*this).Tier3.Default.Stats.HP.Multiplier = 1.000000000e+00f;
    (*this).Tier3.Default.Stats.HP.bOverloadValue = false;
    (*this).Tier3.Default.Stats.Shield.Overload = 0.000000000e+00f;
    (*this).Tier3.Default.Stats.Shield.Value = 0.000000000e+00f;
    (*this).Tier3.Default.Stats.Shield.Multiplier = 1.000000000e+00f;
    (*this).Tier3.Default.Stats.Shield.bOverloadValue = false;
    (*this).Tier3.Default.Stats.WeaponDamage.Overload = 0.000000000e+00f;
    (*this).Tier3.Default.Stats.WeaponDamage.Value = 0.000000000e+00f;
    (*this).Tier3.Default.Stats.WeaponDamage.Multiplier = 1.000000000e+00f;
    (*this).Tier3.Default.Stats.WeaponDamage.bOverloadValue = false;
    (*this).Tier3.Default.Stats.MeleeDamage.Overload = 0.000000000e+00f;
    (*this).Tier3.Default.Stats.MeleeDamage.Value = 0.000000000e+00f;
    (*this).Tier3.Default.Stats.MeleeDamage.Multiplier = 1.000000000e+00f;
    (*this).Tier3.Default.Stats.MeleeDamage.bOverloadValue = false;
    (*this).Tier3.Default.Stats.WeaponDispersion.Overload = 0.000000000e+00f;
    (*this).Tier3.Default.Stats.WeaponDispersion.Value = 0.000000000e+00f;
    (*this).Tier3.Default.Stats.WeaponDispersion.Multiplier = 1.000000000e+00f;
    (*this).Tier3.Default.Stats.WeaponDispersion.bOverloadValue = false;
    (*this).Tier3.Default.Stats.MovementSpeed.Overload = 0.000000000e+00f;
    (*this).Tier3.Default.Stats.MovementSpeed.Value = 0.000000000e+00f;
    (*this).Tier3.Default.Stats.MovementSpeed.Multiplier = 1.000000000e+00f;
    (*this).Tier3.Default.Stats.MovementSpeed.bOverloadValue = false;
    (*this).Tier3.Default.Stats.CoverStickiness.Overload = 0.000000000e+00f;
    (*this).Tier3.Default.Stats.CoverStickiness.Value = 0.000000000e+00f;
    (*this).Tier3.Default.Stats.CoverStickiness.Multiplier = 1.000000000e+00f;
    (*this).Tier3.Default.Stats.CoverStickiness.bOverloadValue = false;
    (*this).Tier3.Default.Stats.ReactionIntensity.Overload = 0.000000000e+00f;
    (*this).Tier3.Default.Stats.ReactionIntensity.Value = 0.000000000e+00f;
    (*this).Tier3.Default.Stats.ReactionIntensity.Multiplier = 1.000000000e+00f;
    (*this).Tier3.Default.Stats.ReactionIntensity.bOverloadValue = false;
    (*this).Tier3.Default.Enabled = true;
    (*this).Tier3.Default.Character.Controller = nullptr;
    (*this).Tier3.Default.Character.Pawns.Empty();
    (*this).Tier3.Default.Loadout.WeaponPool.PrimaryWeapons.Empty();
    (*this).Tier3.Default.Loadout.WeaponPool.SecondaryWeapons.Empty();
    (*this).Tier3.Default.Loadout.WeaponPool.MeleeWeapons.Empty();
    (*this).Tier3.Default.Loadout.WeaponProbability.Empty();
    (*this).Tier3.Default.Loadout.NoThrowableChance = 0;
    (*this).Tier3.Default.Loadout.ThrowablePool.Empty();
    (*TBaseStructure<FGameplayTag>::Get()->FindPropertyByName("TagName")->ContainerPtrToValuePtr<FName>(&(*this).Tier3.Default.Loadout.EmptyWeaponTag, 0)) = TEXT("Item.Wieldable.Weapon");
    (*this).Tier3.Default.Loadout.ShowNoThrowableBool = 0;
    (*TBaseStructure<FGameplayTag>::Get()->FindPropertyByName("TagName")->ContainerPtrToValuePtr<FName>(&(*this).Tier3.Default.Specialization, 0)) = TEXT("AI.Specialization.Default");
    (*this).Tier3.Heavy.Stats.HP.Overload = 0.000000000e+00f;
    (*this).Tier3.Heavy.Stats.HP.Value = 0.000000000e+00f;
    (*this).Tier3.Heavy.Stats.HP.Multiplier = 1.000000000e+00f;
    (*this).Tier3.Heavy.Stats.HP.bOverloadValue = false;
    (*this).Tier3.Heavy.Stats.Shield.Overload = 0.000000000e+00f;
    (*this).Tier3.Heavy.Stats.Shield.Value = 0.000000000e+00f;
    (*this).Tier3.Heavy.Stats.Shield.Multiplier = 1.000000000e+00f;
    (*this).Tier3.Heavy.Stats.Shield.bOverloadValue = false;
    (*this).Tier3.Heavy.Stats.WeaponDamage.Overload = 0.000000000e+00f;
    (*this).Tier3.Heavy.Stats.WeaponDamage.Value = 0.000000000e+00f;
    (*this).Tier3.Heavy.Stats.WeaponDamage.Multiplier = 1.000000000e+00f;
    (*this).Tier3.Heavy.Stats.WeaponDamage.bOverloadValue = false;
    (*this).Tier3.Heavy.Stats.MeleeDamage.Overload = 0.000000000e+00f;
    (*this).Tier3.Heavy.Stats.MeleeDamage.Value = 0.000000000e+00f;
    (*this).Tier3.Heavy.Stats.MeleeDamage.Multiplier = 1.000000000e+00f;
    (*this).Tier3.Heavy.Stats.MeleeDamage.bOverloadValue = false;
    (*this).Tier3.Heavy.Stats.WeaponDispersion.Overload = 0.000000000e+00f;
    (*this).Tier3.Heavy.Stats.WeaponDispersion.Value = 0.000000000e+00f;
    (*this).Tier3.Heavy.Stats.WeaponDispersion.Multiplier = 1.000000000e+00f;
    (*this).Tier3.Heavy.Stats.WeaponDispersion.bOverloadValue = false;
    (*this).Tier3.Heavy.Stats.MovementSpeed.Overload = 0.000000000e+00f;
    (*this).Tier3.Heavy.Stats.MovementSpeed.Value = 0.000000000e+00f;
    (*this).Tier3.Heavy.Stats.MovementSpeed.Multiplier = 1.000000000e+00f;
    (*this).Tier3.Heavy.Stats.MovementSpeed.bOverloadValue = false;
    (*this).Tier3.Heavy.Stats.CoverStickiness.Overload = 0.000000000e+00f;
    (*this).Tier3.Heavy.Stats.CoverStickiness.Value = 0.000000000e+00f;
    (*this).Tier3.Heavy.Stats.CoverStickiness.Multiplier = 1.000000000e+00f;
    (*this).Tier3.Heavy.Stats.CoverStickiness.bOverloadValue = false;
    (*this).Tier3.Heavy.Stats.ReactionIntensity.Overload = 0.000000000e+00f;
    (*this).Tier3.Heavy.Stats.ReactionIntensity.Value = 0.000000000e+00f;
    (*this).Tier3.Heavy.Stats.ReactionIntensity.Multiplier = 1.000000000e+00f;
    (*this).Tier3.Heavy.Stats.ReactionIntensity.bOverloadValue = false;
    (*this).Tier3.Heavy.Enabled = true;
    (*this).Tier3.Heavy.Character.Controller = nullptr;
    (*this).Tier3.Heavy.Character.Pawns.Empty();
    (*this).Tier3.Heavy.Loadout.WeaponPool.PrimaryWeapons.Empty();
    (*this).Tier3.Heavy.Loadout.WeaponPool.SecondaryWeapons.Empty();
    (*this).Tier3.Heavy.Loadout.WeaponPool.MeleeWeapons.Empty();
    (*this).Tier3.Heavy.Loadout.WeaponProbability.Empty();
    (*this).Tier3.Heavy.Loadout.NoThrowableChance = 0;
    (*this).Tier3.Heavy.Loadout.ThrowablePool.Empty();
    (*TBaseStructure<FGameplayTag>::Get()->FindPropertyByName("TagName")->ContainerPtrToValuePtr<FName>(&(*this).Tier3.Heavy.Loadout.EmptyWeaponTag, 0)) = TEXT("Item.Wieldable.Weapon");
    (*this).Tier3.Heavy.Loadout.ShowNoThrowableBool = 0;
    (*TBaseStructure<FGameplayTag>::Get()->FindPropertyByName("TagName")->ContainerPtrToValuePtr<FName>(&(*this).Tier3.Heavy.Specialization, 0)) = TEXT("AI.Specialization.Special.Heavy");
    (*this).Special.Default.Stats.HP.Overload = 0.000000000e+00f;
    (*this).Special.Default.Stats.HP.Value = 0.000000000e+00f;
    (*this).Special.Default.Stats.HP.Multiplier = 1.000000000e+00f;
    (*this).Special.Default.Stats.HP.bOverloadValue = false;
    (*this).Special.Default.Stats.Shield.Overload = 0.000000000e+00f;
    (*this).Special.Default.Stats.Shield.Value = 0.000000000e+00f;
    (*this).Special.Default.Stats.Shield.Multiplier = 1.000000000e+00f;
    (*this).Special.Default.Stats.Shield.bOverloadValue = false;
    (*this).Special.Default.Stats.WeaponDamage.Overload = 0.000000000e+00f;
    (*this).Special.Default.Stats.WeaponDamage.Value = 0.000000000e+00f;
    (*this).Special.Default.Stats.WeaponDamage.Multiplier = 1.000000000e+00f;
    (*this).Special.Default.Stats.WeaponDamage.bOverloadValue = false;
    (*this).Special.Default.Stats.MeleeDamage.Overload = 0.000000000e+00f;
    (*this).Special.Default.Stats.MeleeDamage.Value = 0.000000000e+00f;
    (*this).Special.Default.Stats.MeleeDamage.Multiplier = 1.000000000e+00f;
    (*this).Special.Default.Stats.MeleeDamage.bOverloadValue = false;
    (*this).Special.Default.Stats.WeaponDispersion.Overload = 0.000000000e+00f;
    (*this).Special.Default.Stats.WeaponDispersion.Value = 0.000000000e+00f;
    (*this).Special.Default.Stats.WeaponDispersion.Multiplier = 1.000000000e+00f;
    (*this).Special.Default.Stats.WeaponDispersion.bOverloadValue = false;
    (*this).Special.Default.Stats.MovementSpeed.Overload = 0.000000000e+00f;
    (*this).Special.Default.Stats.MovementSpeed.Value = 0.000000000e+00f;
    (*this).Special.Default.Stats.MovementSpeed.Multiplier = 1.000000000e+00f;
    (*this).Special.Default.Stats.MovementSpeed.bOverloadValue = false;
    (*this).Special.Default.Stats.CoverStickiness.Overload = 0.000000000e+00f;
    (*this).Special.Default.Stats.CoverStickiness.Value = 0.000000000e+00f;
    (*this).Special.Default.Stats.CoverStickiness.Multiplier = 1.000000000e+00f;
    (*this).Special.Default.Stats.CoverStickiness.bOverloadValue = false;
    (*this).Special.Default.Stats.ReactionIntensity.Overload = 0.000000000e+00f;
    (*this).Special.Default.Stats.ReactionIntensity.Value = 0.000000000e+00f;
    (*this).Special.Default.Stats.ReactionIntensity.Multiplier = 1.000000000e+00f;
    (*this).Special.Default.Stats.ReactionIntensity.bOverloadValue = false;
    (*this).Special.Default.Enabled = true;
    (*this).Special.Default.Character.Controller = nullptr;
    (*this).Special.Default.Character.Pawns.Empty();
    (*this).Special.Default.Loadout.WeaponPool.PrimaryWeapons.Empty();
    (*this).Special.Default.Loadout.WeaponPool.SecondaryWeapons.Empty();
    (*this).Special.Default.Loadout.WeaponPool.MeleeWeapons.Empty();
    (*this).Special.Default.Loadout.WeaponProbability.Empty();
    (*this).Special.Default.Loadout.NoThrowableChance = 0;
    (*this).Special.Default.Loadout.ThrowablePool.Empty();
    (*TBaseStructure<FGameplayTag>::Get()->FindPropertyByName("TagName")->ContainerPtrToValuePtr<FName>(&(*this).Special.Default.Loadout.EmptyWeaponTag, 0)) = TEXT("Item.Wieldable.Weapon");
    (*this).Special.Default.Loadout.ShowNoThrowableBool = 0;
    (*TBaseStructure<FGameplayTag>::Get()->FindPropertyByName("TagName")->ContainerPtrToValuePtr<FName>(&(*this).Special.Default.Specialization, 0)) = TEXT("AI.Specialization.Default");
    (*this).Special.Heavy.Stats.HP.Overload = 0.000000000e+00f;
    (*this).Special.Heavy.Stats.HP.Value = 0.000000000e+00f;
    (*this).Special.Heavy.Stats.HP.Multiplier = 1.000000000e+00f;
    (*this).Special.Heavy.Stats.HP.bOverloadValue = false;
    (*this).Special.Heavy.Stats.Shield.Overload = 0.000000000e+00f;
    (*this).Special.Heavy.Stats.Shield.Value = 0.000000000e+00f;
    (*this).Special.Heavy.Stats.Shield.Multiplier = 1.000000000e+00f;
    (*this).Special.Heavy.Stats.Shield.bOverloadValue = false;
    (*this).Special.Heavy.Stats.WeaponDamage.Overload = 0.000000000e+00f;
    (*this).Special.Heavy.Stats.WeaponDamage.Value = 0.000000000e+00f;
    (*this).Special.Heavy.Stats.WeaponDamage.Multiplier = 1.000000000e+00f;
    (*this).Special.Heavy.Stats.WeaponDamage.bOverloadValue = false;
    (*this).Special.Heavy.Stats.MeleeDamage.Overload = 0.000000000e+00f;
    (*this).Special.Heavy.Stats.MeleeDamage.Value = 0.000000000e+00f;
    (*this).Special.Heavy.Stats.MeleeDamage.Multiplier = 1.000000000e+00f;
    (*this).Special.Heavy.Stats.MeleeDamage.bOverloadValue = false;
    (*this).Special.Heavy.Stats.WeaponDispersion.Overload = 0.000000000e+00f;
    (*this).Special.Heavy.Stats.WeaponDispersion.Value = 0.000000000e+00f;
    (*this).Special.Heavy.Stats.WeaponDispersion.Multiplier = 1.000000000e+00f;
    (*this).Special.Heavy.Stats.WeaponDispersion.bOverloadValue = false;
    (*this).Special.Heavy.Stats.MovementSpeed.Overload = 0.000000000e+00f;
    (*this).Special.Heavy.Stats.MovementSpeed.Value = 0.000000000e+00f;
    (*this).Special.Heavy.Stats.MovementSpeed.Multiplier = 1.000000000e+00f;
    (*this).Special.Heavy.Stats.MovementSpeed.bOverloadValue = false;
    (*this).Special.Heavy.Stats.CoverStickiness.Overload = 0.000000000e+00f;
    (*this).Special.Heavy.Stats.CoverStickiness.Value = 0.000000000e+00f;
    (*this).Special.Heavy.Stats.CoverStickiness.Multiplier = 1.000000000e+00f;
    (*this).Special.Heavy.Stats.CoverStickiness.bOverloadValue = false;
    (*this).Special.Heavy.Stats.ReactionIntensity.Overload = 0.000000000e+00f;
    (*this).Special.Heavy.Stats.ReactionIntensity.Value = 0.000000000e+00f;
    (*this).Special.Heavy.Stats.ReactionIntensity.Multiplier = 1.000000000e+00f;
    (*this).Special.Heavy.Stats.ReactionIntensity.bOverloadValue = false;
    (*this).Special.Heavy.Enabled = true;
    (*this).Special.Heavy.Character.Controller = nullptr;
    (*this).Special.Heavy.Character.Pawns.Empty();
    (*this).Special.Heavy.Loadout.WeaponPool.PrimaryWeapons.Empty();
    (*this).Special.Heavy.Loadout.WeaponPool.SecondaryWeapons.Empty();
    (*this).Special.Heavy.Loadout.WeaponPool.MeleeWeapons.Empty();
    (*this).Special.Heavy.Loadout.WeaponProbability.Empty();
    (*this).Special.Heavy.Loadout.NoThrowableChance = 0;
    (*this).Special.Heavy.Loadout.ThrowablePool.Empty();
    (*TBaseStructure<FGameplayTag>::Get()->FindPropertyByName("TagName")->ContainerPtrToValuePtr<FName>(&(*this).Special.Heavy.Loadout.EmptyWeaponTag, 0)) = TEXT("Item.Wieldable.Weapon");
    (*this).Special.Heavy.Loadout.ShowNoThrowableBool = 0;
    (*TBaseStructure<FGameplayTag>::Get()->FindPropertyByName("TagName")->ContainerPtrToValuePtr<FName>(&(*this).Special.Heavy.Specialization, 0)) = TEXT("AI.Specialization.Special.Heavy");
}

