#include "IGS_AISwatTeamDef.h"
#include "GameplayTagContainer.h"
#include "EIGS_CoverPreset.h"
#include "EIGS_TeamSideEnum.h"
#include "EIGS_WeaponVisibilityType.h"

FIGS_AISwatTeamDef::FIGS_AISwatTeamDef() {
    (*this).Tiers.Tier1.Default.Stats.HP.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier1.Default.Stats.HP.Value = 2.800000000e+02f;
    (*this).Tiers.Tier1.Default.Stats.HP.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier1.Default.Stats.HP.bOverloadValue = false;
    (*this).Tiers.Tier1.Default.Stats.Shield.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier1.Default.Stats.Shield.Value = 0.000000000e+00f;
    (*this).Tiers.Tier1.Default.Stats.Shield.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier1.Default.Stats.Shield.bOverloadValue = false;
    (*this).Tiers.Tier1.Default.Stats.WeaponDamage.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier1.Default.Stats.WeaponDamage.Value = 1.000000000e+00f;
    (*this).Tiers.Tier1.Default.Stats.WeaponDamage.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier1.Default.Stats.WeaponDamage.bOverloadValue = false;
    (*this).Tiers.Tier1.Default.Stats.MeleeDamage.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier1.Default.Stats.MeleeDamage.Value = 1.000000000e+00f;
    (*this).Tiers.Tier1.Default.Stats.MeleeDamage.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier1.Default.Stats.MeleeDamage.bOverloadValue = false;
    (*this).Tiers.Tier1.Default.Stats.WeaponDispersion.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier1.Default.Stats.WeaponDispersion.Value = 1.000000000e+00f;
    (*this).Tiers.Tier1.Default.Stats.WeaponDispersion.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier1.Default.Stats.WeaponDispersion.bOverloadValue = false;
    (*this).Tiers.Tier1.Default.Stats.MovementSpeed.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier1.Default.Stats.MovementSpeed.Value = 1.000000000e+00f;
    (*this).Tiers.Tier1.Default.Stats.MovementSpeed.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier1.Default.Stats.MovementSpeed.bOverloadValue = false;
    (*this).Tiers.Tier1.Default.Stats.CoverStickiness.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier1.Default.Stats.CoverStickiness.Value = 5.000000000e-01f;
    (*this).Tiers.Tier1.Default.Stats.CoverStickiness.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier1.Default.Stats.CoverStickiness.bOverloadValue = false;
    (*this).Tiers.Tier1.Default.Stats.ReactionIntensity.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier1.Default.Stats.ReactionIntensity.Value = 5.000000000e-01f;
    (*this).Tiers.Tier1.Default.Stats.ReactionIntensity.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier1.Default.Stats.ReactionIntensity.bOverloadValue = false;
    (*this).Tiers.Tier1.Default.Enabled = true;
    (*this).Tiers.Tier1.Default.Character.Controller = nullptr;
    (*this).Tiers.Tier1.Default.Character.Pawns.Empty();
    (*this).Tiers.Tier1.Default.Loadout.WeaponPool.PrimaryWeapons.Empty();
    (*this).Tiers.Tier1.Default.Loadout.WeaponPool.SecondaryWeapons.Empty();
    (*this).Tiers.Tier1.Default.Loadout.WeaponPool.MeleeWeapons.Empty();
    (*this).Tiers.Tier1.Default.Loadout.WeaponProbability.Empty();
    (*this).Tiers.Tier1.Default.Loadout.NoThrowableChance = 0;
    (*this).Tiers.Tier1.Default.Loadout.ThrowablePool.Empty();
    (*TBaseStructure<FGameplayTag>::Get()->FindPropertyByName("TagName")->ContainerPtrToValuePtr<FName>(&(*this).Tiers.Tier1.Default.Loadout.EmptyWeaponTag, 0)) = TEXT("Item.Wieldable.Weapon");
    (*this).Tiers.Tier1.Default.Loadout.ShowNoThrowableBool = 0;
    (*TBaseStructure<FGameplayTag>::Get()->FindPropertyByName("TagName")->ContainerPtrToValuePtr<FName>(&(*this).Tiers.Tier1.Default.Specialization, 0)) = TEXT("AI.Specialization.Default");
    (*this).Tiers.Tier1.Sniper.SpecStats.HitChance = 8.000000119e-01f;
    (*this).Tiers.Tier1.Sniper.SpecStats.HiddenTimeInterval.Min = 3.000000000e+00f;
    (*this).Tiers.Tier1.Sniper.SpecStats.HiddenTimeInterval.Max = 5.000000000e+00f;
    (*this).Tiers.Tier1.Sniper.SpecStats.CompromisedRange = 5.000000000e+02f;
    (*this).Tiers.Tier1.Sniper.SpecStats.WeaponVisibilityType = EIGS_WeaponVisibilityType::VT_Laser;
    (*this).Tiers.Tier1.Sniper.Stats.HP.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier1.Sniper.Stats.HP.Value = 2.800000000e+02f;
    (*this).Tiers.Tier1.Sniper.Stats.HP.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier1.Sniper.Stats.HP.bOverloadValue = false;
    (*this).Tiers.Tier1.Sniper.Stats.Shield.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier1.Sniper.Stats.Shield.Value = 0.000000000e+00f;
    (*this).Tiers.Tier1.Sniper.Stats.Shield.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier1.Sniper.Stats.Shield.bOverloadValue = false;
    (*this).Tiers.Tier1.Sniper.Stats.WeaponDamage.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier1.Sniper.Stats.WeaponDamage.Value = 1.000000000e+00f;
    (*this).Tiers.Tier1.Sniper.Stats.WeaponDamage.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier1.Sniper.Stats.WeaponDamage.bOverloadValue = false;
    (*this).Tiers.Tier1.Sniper.Stats.MeleeDamage.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier1.Sniper.Stats.MeleeDamage.Value = 1.000000000e+00f;
    (*this).Tiers.Tier1.Sniper.Stats.MeleeDamage.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier1.Sniper.Stats.MeleeDamage.bOverloadValue = false;
    (*this).Tiers.Tier1.Sniper.Stats.WeaponDispersion.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier1.Sniper.Stats.WeaponDispersion.Value = 1.000000000e+00f;
    (*this).Tiers.Tier1.Sniper.Stats.WeaponDispersion.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier1.Sniper.Stats.WeaponDispersion.bOverloadValue = false;
    (*this).Tiers.Tier1.Sniper.Stats.MovementSpeed.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier1.Sniper.Stats.MovementSpeed.Value = 1.000000000e+00f;
    (*this).Tiers.Tier1.Sniper.Stats.MovementSpeed.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier1.Sniper.Stats.MovementSpeed.bOverloadValue = false;
    (*this).Tiers.Tier1.Sniper.Stats.CoverStickiness.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier1.Sniper.Stats.CoverStickiness.Value = 5.000000000e-01f;
    (*this).Tiers.Tier1.Sniper.Stats.CoverStickiness.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier1.Sniper.Stats.CoverStickiness.bOverloadValue = false;
    (*this).Tiers.Tier1.Sniper.Stats.ReactionIntensity.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier1.Sniper.Stats.ReactionIntensity.Value = 5.000000000e-01f;
    (*this).Tiers.Tier1.Sniper.Stats.ReactionIntensity.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier1.Sniper.Stats.ReactionIntensity.bOverloadValue = false;
    (*this).Tiers.Tier1.Sniper.Enabled = true;
    (*this).Tiers.Tier1.Sniper.Character.Controller = nullptr;
    (*this).Tiers.Tier1.Sniper.Character.Pawns.Empty();
    (*this).Tiers.Tier1.Sniper.Loadout.WeaponPool.PrimaryWeapons.Empty();
    (*this).Tiers.Tier1.Sniper.Loadout.WeaponPool.SecondaryWeapons.Empty();
    (*this).Tiers.Tier1.Sniper.Loadout.WeaponPool.MeleeWeapons.Empty();
    (*this).Tiers.Tier1.Sniper.Loadout.WeaponProbability.Empty();
    (*this).Tiers.Tier1.Sniper.Loadout.NoThrowableChance = 0;
    (*this).Tiers.Tier1.Sniper.Loadout.ThrowablePool.Empty();
    (*TBaseStructure<FGameplayTag>::Get()->FindPropertyByName("TagName")->ContainerPtrToValuePtr<FName>(&(*this).Tiers.Tier1.Sniper.Loadout.EmptyWeaponTag, 0)) = TEXT("Item.Wieldable.Weapon");
    (*this).Tiers.Tier1.Sniper.Loadout.ShowNoThrowableBool = 0;
    (*TBaseStructure<FGameplayTag>::Get()->FindPropertyByName("TagName")->ContainerPtrToValuePtr<FName>(&(*this).Tiers.Tier1.Sniper.Specialization, 0)) = TEXT("AI.Specialization.Sniper");
    (*this).Tiers.Tier1.Shield.SpecStats.ShieldGlassHP = 3.000000000e+02f;
    (*this).Tiers.Tier1.Shield.Stats.HP.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier1.Shield.Stats.HP.Value = 2.800000000e+02f;
    (*this).Tiers.Tier1.Shield.Stats.HP.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier1.Shield.Stats.HP.bOverloadValue = false;
    (*this).Tiers.Tier1.Shield.Stats.Shield.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier1.Shield.Stats.Shield.Value = 0.000000000e+00f;
    (*this).Tiers.Tier1.Shield.Stats.Shield.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier1.Shield.Stats.Shield.bOverloadValue = false;
    (*this).Tiers.Tier1.Shield.Stats.WeaponDamage.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier1.Shield.Stats.WeaponDamage.Value = 1.000000000e+00f;
    (*this).Tiers.Tier1.Shield.Stats.WeaponDamage.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier1.Shield.Stats.WeaponDamage.bOverloadValue = false;
    (*this).Tiers.Tier1.Shield.Stats.MeleeDamage.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier1.Shield.Stats.MeleeDamage.Value = 1.000000000e+00f;
    (*this).Tiers.Tier1.Shield.Stats.MeleeDamage.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier1.Shield.Stats.MeleeDamage.bOverloadValue = false;
    (*this).Tiers.Tier1.Shield.Stats.WeaponDispersion.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier1.Shield.Stats.WeaponDispersion.Value = 1.000000000e+00f;
    (*this).Tiers.Tier1.Shield.Stats.WeaponDispersion.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier1.Shield.Stats.WeaponDispersion.bOverloadValue = false;
    (*this).Tiers.Tier1.Shield.Stats.MovementSpeed.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier1.Shield.Stats.MovementSpeed.Value = 1.000000000e+00f;
    (*this).Tiers.Tier1.Shield.Stats.MovementSpeed.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier1.Shield.Stats.MovementSpeed.bOverloadValue = false;
    (*this).Tiers.Tier1.Shield.Stats.CoverStickiness.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier1.Shield.Stats.CoverStickiness.Value = 5.000000000e-01f;
    (*this).Tiers.Tier1.Shield.Stats.CoverStickiness.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier1.Shield.Stats.CoverStickiness.bOverloadValue = false;
    (*this).Tiers.Tier1.Shield.Stats.ReactionIntensity.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier1.Shield.Stats.ReactionIntensity.Value = 5.000000000e-01f;
    (*this).Tiers.Tier1.Shield.Stats.ReactionIntensity.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier1.Shield.Stats.ReactionIntensity.bOverloadValue = false;
    (*this).Tiers.Tier1.Shield.Enabled = true;
    (*this).Tiers.Tier1.Shield.Character.Controller = nullptr;
    (*this).Tiers.Tier1.Shield.Character.Pawns.Empty();
    (*this).Tiers.Tier1.Shield.Loadout.WeaponPool.PrimaryWeapons.Empty();
    (*this).Tiers.Tier1.Shield.Loadout.WeaponPool.SecondaryWeapons.Empty();
    (*this).Tiers.Tier1.Shield.Loadout.WeaponPool.MeleeWeapons.Empty();
    (*this).Tiers.Tier1.Shield.Loadout.WeaponProbability.Empty();
    (*this).Tiers.Tier1.Shield.Loadout.NoThrowableChance = 0;
    (*this).Tiers.Tier1.Shield.Loadout.ThrowablePool.Empty();
    (*TBaseStructure<FGameplayTag>::Get()->FindPropertyByName("TagName")->ContainerPtrToValuePtr<FName>(&(*this).Tiers.Tier1.Shield.Loadout.EmptyWeaponTag, 0)) = TEXT("Item.Wieldable.Weapon");
    (*this).Tiers.Tier1.Shield.Loadout.ShowNoThrowableBool = 0;
    (*TBaseStructure<FGameplayTag>::Get()->FindPropertyByName("TagName")->ContainerPtrToValuePtr<FName>(&(*this).Tiers.Tier1.Shield.Specialization, 0)) = TEXT("AI.Specialization.Special.Shield");
    (*this).Tiers.Tier1.Heavy.SpecStats.Shock.ActivationDistance = 3.000000000e+02f;
    (*this).Tiers.Tier1.Heavy.SpecStats.Shock.Cooldown = 1.000000000e+01f;
    (*this).Tiers.Tier1.Heavy.SpecStats.Shock.Radius = 3.500000000e+02f;
    (*this).Tiers.Tier1.Heavy.SpecStats.Shock.Angle = 1.800000000e+02f;
    (*this).Tiers.Tier1.Heavy.SpecStats.Shock.ChargeTime = 2.000000000e+00f;
    (*this).Tiers.Tier1.Heavy.SpecStats.Shock.Damage = 1.000000000e+01f;
    (*this).Tiers.Tier1.Heavy.SpecStats.Shock.Count = 4;
    (*this).Tiers.Tier1.Heavy.SpecStats.Shock.Duration.Min = 3.750000000e+00f;
    (*this).Tiers.Tier1.Heavy.SpecStats.Shock.Duration.Max = 4.250000000e+00f;
    (*this).Tiers.Tier1.Heavy.SpecStats.WeakSpot.WeakSpotHealth = 1.000000000e+02f;
    (*this).Tiers.Tier1.Heavy.SpecStats.WeakSpot.DoomTimer.Min = 5.000000000e+00f;
    (*this).Tiers.Tier1.Heavy.SpecStats.WeakSpot.DoomTimer.Max = 1.000000000e+01f;
    (*this).Tiers.Tier1.Heavy.SpecStats.Injured.HealthToInjured = 2.500000000e+03f;
    (*this).Tiers.Tier1.Heavy.SpecStats.Injured.InjuredTime.Min = 6.000000000e+00f;
    (*this).Tiers.Tier1.Heavy.SpecStats.Injured.InjuredTime.Max = 7.500000000e+00f;
    (*this).Tiers.Tier1.Heavy.Stats.HP.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier1.Heavy.Stats.HP.Value = 2.800000000e+02f;
    (*this).Tiers.Tier1.Heavy.Stats.HP.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier1.Heavy.Stats.HP.bOverloadValue = false;
    (*this).Tiers.Tier1.Heavy.Stats.Shield.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier1.Heavy.Stats.Shield.Value = 0.000000000e+00f;
    (*this).Tiers.Tier1.Heavy.Stats.Shield.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier1.Heavy.Stats.Shield.bOverloadValue = false;
    (*this).Tiers.Tier1.Heavy.Stats.WeaponDamage.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier1.Heavy.Stats.WeaponDamage.Value = 1.000000000e+00f;
    (*this).Tiers.Tier1.Heavy.Stats.WeaponDamage.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier1.Heavy.Stats.WeaponDamage.bOverloadValue = false;
    (*this).Tiers.Tier1.Heavy.Stats.MeleeDamage.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier1.Heavy.Stats.MeleeDamage.Value = 1.000000000e+00f;
    (*this).Tiers.Tier1.Heavy.Stats.MeleeDamage.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier1.Heavy.Stats.MeleeDamage.bOverloadValue = false;
    (*this).Tiers.Tier1.Heavy.Stats.WeaponDispersion.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier1.Heavy.Stats.WeaponDispersion.Value = 1.000000000e+00f;
    (*this).Tiers.Tier1.Heavy.Stats.WeaponDispersion.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier1.Heavy.Stats.WeaponDispersion.bOverloadValue = false;
    (*this).Tiers.Tier1.Heavy.Stats.MovementSpeed.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier1.Heavy.Stats.MovementSpeed.Value = 1.000000000e+00f;
    (*this).Tiers.Tier1.Heavy.Stats.MovementSpeed.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier1.Heavy.Stats.MovementSpeed.bOverloadValue = false;
    (*this).Tiers.Tier1.Heavy.Stats.CoverStickiness.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier1.Heavy.Stats.CoverStickiness.Value = 5.000000000e-01f;
    (*this).Tiers.Tier1.Heavy.Stats.CoverStickiness.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier1.Heavy.Stats.CoverStickiness.bOverloadValue = false;
    (*this).Tiers.Tier1.Heavy.Stats.ReactionIntensity.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier1.Heavy.Stats.ReactionIntensity.Value = 5.000000000e-01f;
    (*this).Tiers.Tier1.Heavy.Stats.ReactionIntensity.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier1.Heavy.Stats.ReactionIntensity.bOverloadValue = false;
    (*this).Tiers.Tier1.Heavy.Enabled = true;
    (*this).Tiers.Tier1.Heavy.Character.Controller = nullptr;
    (*this).Tiers.Tier1.Heavy.Character.Pawns.Empty();
    (*this).Tiers.Tier1.Heavy.Loadout.WeaponPool.PrimaryWeapons.Empty();
    (*this).Tiers.Tier1.Heavy.Loadout.WeaponPool.SecondaryWeapons.Empty();
    (*this).Tiers.Tier1.Heavy.Loadout.WeaponPool.MeleeWeapons.Empty();
    (*this).Tiers.Tier1.Heavy.Loadout.WeaponProbability.Empty();
    (*this).Tiers.Tier1.Heavy.Loadout.NoThrowableChance = 0;
    (*this).Tiers.Tier1.Heavy.Loadout.ThrowablePool.Empty();
    (*TBaseStructure<FGameplayTag>::Get()->FindPropertyByName("TagName")->ContainerPtrToValuePtr<FName>(&(*this).Tiers.Tier1.Heavy.Loadout.EmptyWeaponTag, 0)) = TEXT("Item.Wieldable.Weapon");
    (*this).Tiers.Tier1.Heavy.Loadout.ShowNoThrowableBool = 0;
    (*TBaseStructure<FGameplayTag>::Get()->FindPropertyByName("TagName")->ContainerPtrToValuePtr<FName>(&(*this).Tiers.Tier1.Heavy.Specialization, 0)) = TEXT("AI.Specialization.Special.Heavy");
    (*this).Tiers.Tier1.HeavyScout.Stats.HP.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier1.HeavyScout.Stats.HP.Value = 2.800000000e+02f;
    (*this).Tiers.Tier1.HeavyScout.Stats.HP.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier1.HeavyScout.Stats.HP.bOverloadValue = false;
    (*this).Tiers.Tier1.HeavyScout.Stats.Shield.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier1.HeavyScout.Stats.Shield.Value = 0.000000000e+00f;
    (*this).Tiers.Tier1.HeavyScout.Stats.Shield.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier1.HeavyScout.Stats.Shield.bOverloadValue = false;
    (*this).Tiers.Tier1.HeavyScout.Stats.WeaponDamage.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier1.HeavyScout.Stats.WeaponDamage.Value = 1.000000000e+00f;
    (*this).Tiers.Tier1.HeavyScout.Stats.WeaponDamage.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier1.HeavyScout.Stats.WeaponDamage.bOverloadValue = false;
    (*this).Tiers.Tier1.HeavyScout.Stats.MeleeDamage.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier1.HeavyScout.Stats.MeleeDamage.Value = 1.000000000e+00f;
    (*this).Tiers.Tier1.HeavyScout.Stats.MeleeDamage.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier1.HeavyScout.Stats.MeleeDamage.bOverloadValue = false;
    (*this).Tiers.Tier1.HeavyScout.Stats.WeaponDispersion.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier1.HeavyScout.Stats.WeaponDispersion.Value = 1.000000000e+00f;
    (*this).Tiers.Tier1.HeavyScout.Stats.WeaponDispersion.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier1.HeavyScout.Stats.WeaponDispersion.bOverloadValue = false;
    (*this).Tiers.Tier1.HeavyScout.Stats.MovementSpeed.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier1.HeavyScout.Stats.MovementSpeed.Value = 1.000000000e+00f;
    (*this).Tiers.Tier1.HeavyScout.Stats.MovementSpeed.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier1.HeavyScout.Stats.MovementSpeed.bOverloadValue = false;
    (*this).Tiers.Tier1.HeavyScout.Stats.CoverStickiness.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier1.HeavyScout.Stats.CoverStickiness.Value = 5.000000000e-01f;
    (*this).Tiers.Tier1.HeavyScout.Stats.CoverStickiness.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier1.HeavyScout.Stats.CoverStickiness.bOverloadValue = false;
    (*this).Tiers.Tier1.HeavyScout.Stats.ReactionIntensity.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier1.HeavyScout.Stats.ReactionIntensity.Value = 5.000000000e-01f;
    (*this).Tiers.Tier1.HeavyScout.Stats.ReactionIntensity.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier1.HeavyScout.Stats.ReactionIntensity.bOverloadValue = false;
    (*this).Tiers.Tier1.HeavyScout.Enabled = true;
    (*this).Tiers.Tier1.HeavyScout.Character.Controller = nullptr;
    (*this).Tiers.Tier1.HeavyScout.Character.Pawns.Empty();
    (*this).Tiers.Tier1.HeavyScout.Loadout.WeaponPool.PrimaryWeapons.Empty();
    (*this).Tiers.Tier1.HeavyScout.Loadout.WeaponPool.SecondaryWeapons.Empty();
    (*this).Tiers.Tier1.HeavyScout.Loadout.WeaponPool.MeleeWeapons.Empty();
    (*this).Tiers.Tier1.HeavyScout.Loadout.WeaponProbability.Empty();
    (*this).Tiers.Tier1.HeavyScout.Loadout.NoThrowableChance = 0;
    (*this).Tiers.Tier1.HeavyScout.Loadout.ThrowablePool.Empty();
    (*TBaseStructure<FGameplayTag>::Get()->FindPropertyByName("TagName")->ContainerPtrToValuePtr<FName>(&(*this).Tiers.Tier1.HeavyScout.Loadout.EmptyWeaponTag, 0)) = TEXT("Item.Wieldable.Weapon");
    (*this).Tiers.Tier1.HeavyScout.Loadout.ShowNoThrowableBool = 0;
    (*TBaseStructure<FGameplayTag>::Get()->FindPropertyByName("TagName")->ContainerPtrToValuePtr<FName>(&(*this).Tiers.Tier1.HeavyScout.Specialization, 0)) = TEXT("AI.Specialization.Special.Scout.Heavy");
    (*this).Tiers.Tier2.Default.Stats.HP.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier2.Default.Stats.HP.Value = 2.800000000e+02f;
    (*this).Tiers.Tier2.Default.Stats.HP.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier2.Default.Stats.HP.bOverloadValue = false;
    (*this).Tiers.Tier2.Default.Stats.Shield.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier2.Default.Stats.Shield.Value = 0.000000000e+00f;
    (*this).Tiers.Tier2.Default.Stats.Shield.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier2.Default.Stats.Shield.bOverloadValue = false;
    (*this).Tiers.Tier2.Default.Stats.WeaponDamage.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier2.Default.Stats.WeaponDamage.Value = 1.000000000e+00f;
    (*this).Tiers.Tier2.Default.Stats.WeaponDamage.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier2.Default.Stats.WeaponDamage.bOverloadValue = false;
    (*this).Tiers.Tier2.Default.Stats.MeleeDamage.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier2.Default.Stats.MeleeDamage.Value = 1.000000000e+00f;
    (*this).Tiers.Tier2.Default.Stats.MeleeDamage.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier2.Default.Stats.MeleeDamage.bOverloadValue = false;
    (*this).Tiers.Tier2.Default.Stats.WeaponDispersion.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier2.Default.Stats.WeaponDispersion.Value = 1.000000000e+00f;
    (*this).Tiers.Tier2.Default.Stats.WeaponDispersion.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier2.Default.Stats.WeaponDispersion.bOverloadValue = false;
    (*this).Tiers.Tier2.Default.Stats.MovementSpeed.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier2.Default.Stats.MovementSpeed.Value = 1.000000000e+00f;
    (*this).Tiers.Tier2.Default.Stats.MovementSpeed.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier2.Default.Stats.MovementSpeed.bOverloadValue = false;
    (*this).Tiers.Tier2.Default.Stats.CoverStickiness.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier2.Default.Stats.CoverStickiness.Value = 5.000000000e-01f;
    (*this).Tiers.Tier2.Default.Stats.CoverStickiness.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier2.Default.Stats.CoverStickiness.bOverloadValue = false;
    (*this).Tiers.Tier2.Default.Stats.ReactionIntensity.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier2.Default.Stats.ReactionIntensity.Value = 5.000000000e-01f;
    (*this).Tiers.Tier2.Default.Stats.ReactionIntensity.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier2.Default.Stats.ReactionIntensity.bOverloadValue = false;
    (*this).Tiers.Tier2.Default.Enabled = true;
    (*this).Tiers.Tier2.Default.Character.Controller = nullptr;
    (*this).Tiers.Tier2.Default.Character.Pawns.Empty();
    (*this).Tiers.Tier2.Default.Loadout.WeaponPool.PrimaryWeapons.Empty();
    (*this).Tiers.Tier2.Default.Loadout.WeaponPool.SecondaryWeapons.Empty();
    (*this).Tiers.Tier2.Default.Loadout.WeaponPool.MeleeWeapons.Empty();
    (*this).Tiers.Tier2.Default.Loadout.WeaponProbability.Empty();
    (*this).Tiers.Tier2.Default.Loadout.NoThrowableChance = 0;
    (*this).Tiers.Tier2.Default.Loadout.ThrowablePool.Empty();
    (*TBaseStructure<FGameplayTag>::Get()->FindPropertyByName("TagName")->ContainerPtrToValuePtr<FName>(&(*this).Tiers.Tier2.Default.Loadout.EmptyWeaponTag, 0)) = TEXT("Item.Wieldable.Weapon");
    (*this).Tiers.Tier2.Default.Loadout.ShowNoThrowableBool = 0;
    (*TBaseStructure<FGameplayTag>::Get()->FindPropertyByName("TagName")->ContainerPtrToValuePtr<FName>(&(*this).Tiers.Tier2.Default.Specialization, 0)) = TEXT("AI.Specialization.Default");
    (*this).Tiers.Tier2.Sniper.SpecStats.HitChance = 8.000000119e-01f;
    (*this).Tiers.Tier2.Sniper.SpecStats.HiddenTimeInterval.Min = 3.000000000e+00f;
    (*this).Tiers.Tier2.Sniper.SpecStats.HiddenTimeInterval.Max = 5.000000000e+00f;
    (*this).Tiers.Tier2.Sniper.SpecStats.CompromisedRange = 5.000000000e+02f;
    (*this).Tiers.Tier2.Sniper.SpecStats.WeaponVisibilityType = EIGS_WeaponVisibilityType::VT_Laser;
    (*this).Tiers.Tier2.Sniper.Stats.HP.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier2.Sniper.Stats.HP.Value = 2.800000000e+02f;
    (*this).Tiers.Tier2.Sniper.Stats.HP.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier2.Sniper.Stats.HP.bOverloadValue = false;
    (*this).Tiers.Tier2.Sniper.Stats.Shield.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier2.Sniper.Stats.Shield.Value = 0.000000000e+00f;
    (*this).Tiers.Tier2.Sniper.Stats.Shield.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier2.Sniper.Stats.Shield.bOverloadValue = false;
    (*this).Tiers.Tier2.Sniper.Stats.WeaponDamage.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier2.Sniper.Stats.WeaponDamage.Value = 1.000000000e+00f;
    (*this).Tiers.Tier2.Sniper.Stats.WeaponDamage.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier2.Sniper.Stats.WeaponDamage.bOverloadValue = false;
    (*this).Tiers.Tier2.Sniper.Stats.MeleeDamage.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier2.Sniper.Stats.MeleeDamage.Value = 1.000000000e+00f;
    (*this).Tiers.Tier2.Sniper.Stats.MeleeDamage.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier2.Sniper.Stats.MeleeDamage.bOverloadValue = false;
    (*this).Tiers.Tier2.Sniper.Stats.WeaponDispersion.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier2.Sniper.Stats.WeaponDispersion.Value = 1.000000000e+00f;
    (*this).Tiers.Tier2.Sniper.Stats.WeaponDispersion.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier2.Sniper.Stats.WeaponDispersion.bOverloadValue = false;
    (*this).Tiers.Tier2.Sniper.Stats.MovementSpeed.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier2.Sniper.Stats.MovementSpeed.Value = 1.000000000e+00f;
    (*this).Tiers.Tier2.Sniper.Stats.MovementSpeed.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier2.Sniper.Stats.MovementSpeed.bOverloadValue = false;
    (*this).Tiers.Tier2.Sniper.Stats.CoverStickiness.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier2.Sniper.Stats.CoverStickiness.Value = 5.000000000e-01f;
    (*this).Tiers.Tier2.Sniper.Stats.CoverStickiness.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier2.Sniper.Stats.CoverStickiness.bOverloadValue = false;
    (*this).Tiers.Tier2.Sniper.Stats.ReactionIntensity.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier2.Sniper.Stats.ReactionIntensity.Value = 5.000000000e-01f;
    (*this).Tiers.Tier2.Sniper.Stats.ReactionIntensity.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier2.Sniper.Stats.ReactionIntensity.bOverloadValue = false;
    (*this).Tiers.Tier2.Sniper.Enabled = true;
    (*this).Tiers.Tier2.Sniper.Character.Controller = nullptr;
    (*this).Tiers.Tier2.Sniper.Character.Pawns.Empty();
    (*this).Tiers.Tier2.Sniper.Loadout.WeaponPool.PrimaryWeapons.Empty();
    (*this).Tiers.Tier2.Sniper.Loadout.WeaponPool.SecondaryWeapons.Empty();
    (*this).Tiers.Tier2.Sniper.Loadout.WeaponPool.MeleeWeapons.Empty();
    (*this).Tiers.Tier2.Sniper.Loadout.WeaponProbability.Empty();
    (*this).Tiers.Tier2.Sniper.Loadout.NoThrowableChance = 0;
    (*this).Tiers.Tier2.Sniper.Loadout.ThrowablePool.Empty();
    (*TBaseStructure<FGameplayTag>::Get()->FindPropertyByName("TagName")->ContainerPtrToValuePtr<FName>(&(*this).Tiers.Tier2.Sniper.Loadout.EmptyWeaponTag, 0)) = TEXT("Item.Wieldable.Weapon");
    (*this).Tiers.Tier2.Sniper.Loadout.ShowNoThrowableBool = 0;
    (*TBaseStructure<FGameplayTag>::Get()->FindPropertyByName("TagName")->ContainerPtrToValuePtr<FName>(&(*this).Tiers.Tier2.Sniper.Specialization, 0)) = TEXT("AI.Specialization.Sniper");
    (*this).Tiers.Tier2.Shield.SpecStats.ShieldGlassHP = 3.000000000e+02f;
    (*this).Tiers.Tier2.Shield.Stats.HP.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier2.Shield.Stats.HP.Value = 2.800000000e+02f;
    (*this).Tiers.Tier2.Shield.Stats.HP.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier2.Shield.Stats.HP.bOverloadValue = false;
    (*this).Tiers.Tier2.Shield.Stats.Shield.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier2.Shield.Stats.Shield.Value = 0.000000000e+00f;
    (*this).Tiers.Tier2.Shield.Stats.Shield.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier2.Shield.Stats.Shield.bOverloadValue = false;
    (*this).Tiers.Tier2.Shield.Stats.WeaponDamage.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier2.Shield.Stats.WeaponDamage.Value = 1.000000000e+00f;
    (*this).Tiers.Tier2.Shield.Stats.WeaponDamage.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier2.Shield.Stats.WeaponDamage.bOverloadValue = false;
    (*this).Tiers.Tier2.Shield.Stats.MeleeDamage.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier2.Shield.Stats.MeleeDamage.Value = 1.000000000e+00f;
    (*this).Tiers.Tier2.Shield.Stats.MeleeDamage.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier2.Shield.Stats.MeleeDamage.bOverloadValue = false;
    (*this).Tiers.Tier2.Shield.Stats.WeaponDispersion.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier2.Shield.Stats.WeaponDispersion.Value = 1.000000000e+00f;
    (*this).Tiers.Tier2.Shield.Stats.WeaponDispersion.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier2.Shield.Stats.WeaponDispersion.bOverloadValue = false;
    (*this).Tiers.Tier2.Shield.Stats.MovementSpeed.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier2.Shield.Stats.MovementSpeed.Value = 1.000000000e+00f;
    (*this).Tiers.Tier2.Shield.Stats.MovementSpeed.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier2.Shield.Stats.MovementSpeed.bOverloadValue = false;
    (*this).Tiers.Tier2.Shield.Stats.CoverStickiness.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier2.Shield.Stats.CoverStickiness.Value = 5.000000000e-01f;
    (*this).Tiers.Tier2.Shield.Stats.CoverStickiness.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier2.Shield.Stats.CoverStickiness.bOverloadValue = false;
    (*this).Tiers.Tier2.Shield.Stats.ReactionIntensity.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier2.Shield.Stats.ReactionIntensity.Value = 5.000000000e-01f;
    (*this).Tiers.Tier2.Shield.Stats.ReactionIntensity.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier2.Shield.Stats.ReactionIntensity.bOverloadValue = false;
    (*this).Tiers.Tier2.Shield.Enabled = true;
    (*this).Tiers.Tier2.Shield.Character.Controller = nullptr;
    (*this).Tiers.Tier2.Shield.Character.Pawns.Empty();
    (*this).Tiers.Tier2.Shield.Loadout.WeaponPool.PrimaryWeapons.Empty();
    (*this).Tiers.Tier2.Shield.Loadout.WeaponPool.SecondaryWeapons.Empty();
    (*this).Tiers.Tier2.Shield.Loadout.WeaponPool.MeleeWeapons.Empty();
    (*this).Tiers.Tier2.Shield.Loadout.WeaponProbability.Empty();
    (*this).Tiers.Tier2.Shield.Loadout.NoThrowableChance = 0;
    (*this).Tiers.Tier2.Shield.Loadout.ThrowablePool.Empty();
    (*TBaseStructure<FGameplayTag>::Get()->FindPropertyByName("TagName")->ContainerPtrToValuePtr<FName>(&(*this).Tiers.Tier2.Shield.Loadout.EmptyWeaponTag, 0)) = TEXT("Item.Wieldable.Weapon");
    (*this).Tiers.Tier2.Shield.Loadout.ShowNoThrowableBool = 0;
    (*TBaseStructure<FGameplayTag>::Get()->FindPropertyByName("TagName")->ContainerPtrToValuePtr<FName>(&(*this).Tiers.Tier2.Shield.Specialization, 0)) = TEXT("AI.Specialization.Special.Shield");
    (*this).Tiers.Tier2.Heavy.SpecStats.Shock.ActivationDistance = 3.000000000e+02f;
    (*this).Tiers.Tier2.Heavy.SpecStats.Shock.Cooldown = 1.000000000e+01f;
    (*this).Tiers.Tier2.Heavy.SpecStats.Shock.Radius = 3.500000000e+02f;
    (*this).Tiers.Tier2.Heavy.SpecStats.Shock.Angle = 1.800000000e+02f;
    (*this).Tiers.Tier2.Heavy.SpecStats.Shock.ChargeTime = 2.000000000e+00f;
    (*this).Tiers.Tier2.Heavy.SpecStats.Shock.Damage = 1.000000000e+01f;
    (*this).Tiers.Tier2.Heavy.SpecStats.Shock.Count = 4;
    (*this).Tiers.Tier2.Heavy.SpecStats.Shock.Duration.Min = 3.750000000e+00f;
    (*this).Tiers.Tier2.Heavy.SpecStats.Shock.Duration.Max = 4.250000000e+00f;
    (*this).Tiers.Tier2.Heavy.SpecStats.WeakSpot.WeakSpotHealth = 1.000000000e+02f;
    (*this).Tiers.Tier2.Heavy.SpecStats.WeakSpot.DoomTimer.Min = 5.000000000e+00f;
    (*this).Tiers.Tier2.Heavy.SpecStats.WeakSpot.DoomTimer.Max = 1.000000000e+01f;
    (*this).Tiers.Tier2.Heavy.SpecStats.Injured.HealthToInjured = 2.500000000e+03f;
    (*this).Tiers.Tier2.Heavy.SpecStats.Injured.InjuredTime.Min = 6.000000000e+00f;
    (*this).Tiers.Tier2.Heavy.SpecStats.Injured.InjuredTime.Max = 7.500000000e+00f;
    (*this).Tiers.Tier2.Heavy.Stats.HP.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier2.Heavy.Stats.HP.Value = 2.800000000e+02f;
    (*this).Tiers.Tier2.Heavy.Stats.HP.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier2.Heavy.Stats.HP.bOverloadValue = false;
    (*this).Tiers.Tier2.Heavy.Stats.Shield.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier2.Heavy.Stats.Shield.Value = 0.000000000e+00f;
    (*this).Tiers.Tier2.Heavy.Stats.Shield.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier2.Heavy.Stats.Shield.bOverloadValue = false;
    (*this).Tiers.Tier2.Heavy.Stats.WeaponDamage.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier2.Heavy.Stats.WeaponDamage.Value = 1.000000000e+00f;
    (*this).Tiers.Tier2.Heavy.Stats.WeaponDamage.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier2.Heavy.Stats.WeaponDamage.bOverloadValue = false;
    (*this).Tiers.Tier2.Heavy.Stats.MeleeDamage.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier2.Heavy.Stats.MeleeDamage.Value = 1.000000000e+00f;
    (*this).Tiers.Tier2.Heavy.Stats.MeleeDamage.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier2.Heavy.Stats.MeleeDamage.bOverloadValue = false;
    (*this).Tiers.Tier2.Heavy.Stats.WeaponDispersion.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier2.Heavy.Stats.WeaponDispersion.Value = 1.000000000e+00f;
    (*this).Tiers.Tier2.Heavy.Stats.WeaponDispersion.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier2.Heavy.Stats.WeaponDispersion.bOverloadValue = false;
    (*this).Tiers.Tier2.Heavy.Stats.MovementSpeed.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier2.Heavy.Stats.MovementSpeed.Value = 1.000000000e+00f;
    (*this).Tiers.Tier2.Heavy.Stats.MovementSpeed.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier2.Heavy.Stats.MovementSpeed.bOverloadValue = false;
    (*this).Tiers.Tier2.Heavy.Stats.CoverStickiness.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier2.Heavy.Stats.CoverStickiness.Value = 5.000000000e-01f;
    (*this).Tiers.Tier2.Heavy.Stats.CoverStickiness.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier2.Heavy.Stats.CoverStickiness.bOverloadValue = false;
    (*this).Tiers.Tier2.Heavy.Stats.ReactionIntensity.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier2.Heavy.Stats.ReactionIntensity.Value = 5.000000000e-01f;
    (*this).Tiers.Tier2.Heavy.Stats.ReactionIntensity.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier2.Heavy.Stats.ReactionIntensity.bOverloadValue = false;
    (*this).Tiers.Tier2.Heavy.Enabled = true;
    (*this).Tiers.Tier2.Heavy.Character.Controller = nullptr;
    (*this).Tiers.Tier2.Heavy.Character.Pawns.Empty();
    (*this).Tiers.Tier2.Heavy.Loadout.WeaponPool.PrimaryWeapons.Empty();
    (*this).Tiers.Tier2.Heavy.Loadout.WeaponPool.SecondaryWeapons.Empty();
    (*this).Tiers.Tier2.Heavy.Loadout.WeaponPool.MeleeWeapons.Empty();
    (*this).Tiers.Tier2.Heavy.Loadout.WeaponProbability.Empty();
    (*this).Tiers.Tier2.Heavy.Loadout.NoThrowableChance = 0;
    (*this).Tiers.Tier2.Heavy.Loadout.ThrowablePool.Empty();
    (*TBaseStructure<FGameplayTag>::Get()->FindPropertyByName("TagName")->ContainerPtrToValuePtr<FName>(&(*this).Tiers.Tier2.Heavy.Loadout.EmptyWeaponTag, 0)) = TEXT("Item.Wieldable.Weapon");
    (*this).Tiers.Tier2.Heavy.Loadout.ShowNoThrowableBool = 0;
    (*TBaseStructure<FGameplayTag>::Get()->FindPropertyByName("TagName")->ContainerPtrToValuePtr<FName>(&(*this).Tiers.Tier2.Heavy.Specialization, 0)) = TEXT("AI.Specialization.Special.Heavy");
    (*this).Tiers.Tier2.HeavyScout.Stats.HP.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier2.HeavyScout.Stats.HP.Value = 2.800000000e+02f;
    (*this).Tiers.Tier2.HeavyScout.Stats.HP.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier2.HeavyScout.Stats.HP.bOverloadValue = false;
    (*this).Tiers.Tier2.HeavyScout.Stats.Shield.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier2.HeavyScout.Stats.Shield.Value = 0.000000000e+00f;
    (*this).Tiers.Tier2.HeavyScout.Stats.Shield.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier2.HeavyScout.Stats.Shield.bOverloadValue = false;
    (*this).Tiers.Tier2.HeavyScout.Stats.WeaponDamage.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier2.HeavyScout.Stats.WeaponDamage.Value = 1.000000000e+00f;
    (*this).Tiers.Tier2.HeavyScout.Stats.WeaponDamage.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier2.HeavyScout.Stats.WeaponDamage.bOverloadValue = false;
    (*this).Tiers.Tier2.HeavyScout.Stats.MeleeDamage.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier2.HeavyScout.Stats.MeleeDamage.Value = 1.000000000e+00f;
    (*this).Tiers.Tier2.HeavyScout.Stats.MeleeDamage.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier2.HeavyScout.Stats.MeleeDamage.bOverloadValue = false;
    (*this).Tiers.Tier2.HeavyScout.Stats.WeaponDispersion.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier2.HeavyScout.Stats.WeaponDispersion.Value = 1.000000000e+00f;
    (*this).Tiers.Tier2.HeavyScout.Stats.WeaponDispersion.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier2.HeavyScout.Stats.WeaponDispersion.bOverloadValue = false;
    (*this).Tiers.Tier2.HeavyScout.Stats.MovementSpeed.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier2.HeavyScout.Stats.MovementSpeed.Value = 1.000000000e+00f;
    (*this).Tiers.Tier2.HeavyScout.Stats.MovementSpeed.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier2.HeavyScout.Stats.MovementSpeed.bOverloadValue = false;
    (*this).Tiers.Tier2.HeavyScout.Stats.CoverStickiness.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier2.HeavyScout.Stats.CoverStickiness.Value = 5.000000000e-01f;
    (*this).Tiers.Tier2.HeavyScout.Stats.CoverStickiness.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier2.HeavyScout.Stats.CoverStickiness.bOverloadValue = false;
    (*this).Tiers.Tier2.HeavyScout.Stats.ReactionIntensity.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier2.HeavyScout.Stats.ReactionIntensity.Value = 5.000000000e-01f;
    (*this).Tiers.Tier2.HeavyScout.Stats.ReactionIntensity.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier2.HeavyScout.Stats.ReactionIntensity.bOverloadValue = false;
    (*this).Tiers.Tier2.HeavyScout.Enabled = true;
    (*this).Tiers.Tier2.HeavyScout.Character.Controller = nullptr;
    (*this).Tiers.Tier2.HeavyScout.Character.Pawns.Empty();
    (*this).Tiers.Tier2.HeavyScout.Loadout.WeaponPool.PrimaryWeapons.Empty();
    (*this).Tiers.Tier2.HeavyScout.Loadout.WeaponPool.SecondaryWeapons.Empty();
    (*this).Tiers.Tier2.HeavyScout.Loadout.WeaponPool.MeleeWeapons.Empty();
    (*this).Tiers.Tier2.HeavyScout.Loadout.WeaponProbability.Empty();
    (*this).Tiers.Tier2.HeavyScout.Loadout.NoThrowableChance = 0;
    (*this).Tiers.Tier2.HeavyScout.Loadout.ThrowablePool.Empty();
    (*TBaseStructure<FGameplayTag>::Get()->FindPropertyByName("TagName")->ContainerPtrToValuePtr<FName>(&(*this).Tiers.Tier2.HeavyScout.Loadout.EmptyWeaponTag, 0)) = TEXT("Item.Wieldable.Weapon");
    (*this).Tiers.Tier2.HeavyScout.Loadout.ShowNoThrowableBool = 0;
    (*TBaseStructure<FGameplayTag>::Get()->FindPropertyByName("TagName")->ContainerPtrToValuePtr<FName>(&(*this).Tiers.Tier2.HeavyScout.Specialization, 0)) = TEXT("AI.Specialization.Special.Scout.Heavy");
    (*this).Tiers.Tier3.Default.Stats.HP.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier3.Default.Stats.HP.Value = 2.800000000e+02f;
    (*this).Tiers.Tier3.Default.Stats.HP.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier3.Default.Stats.HP.bOverloadValue = false;
    (*this).Tiers.Tier3.Default.Stats.Shield.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier3.Default.Stats.Shield.Value = 0.000000000e+00f;
    (*this).Tiers.Tier3.Default.Stats.Shield.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier3.Default.Stats.Shield.bOverloadValue = false;
    (*this).Tiers.Tier3.Default.Stats.WeaponDamage.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier3.Default.Stats.WeaponDamage.Value = 1.000000000e+00f;
    (*this).Tiers.Tier3.Default.Stats.WeaponDamage.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier3.Default.Stats.WeaponDamage.bOverloadValue = false;
    (*this).Tiers.Tier3.Default.Stats.MeleeDamage.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier3.Default.Stats.MeleeDamage.Value = 1.000000000e+00f;
    (*this).Tiers.Tier3.Default.Stats.MeleeDamage.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier3.Default.Stats.MeleeDamage.bOverloadValue = false;
    (*this).Tiers.Tier3.Default.Stats.WeaponDispersion.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier3.Default.Stats.WeaponDispersion.Value = 1.000000000e+00f;
    (*this).Tiers.Tier3.Default.Stats.WeaponDispersion.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier3.Default.Stats.WeaponDispersion.bOverloadValue = false;
    (*this).Tiers.Tier3.Default.Stats.MovementSpeed.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier3.Default.Stats.MovementSpeed.Value = 1.000000000e+00f;
    (*this).Tiers.Tier3.Default.Stats.MovementSpeed.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier3.Default.Stats.MovementSpeed.bOverloadValue = false;
    (*this).Tiers.Tier3.Default.Stats.CoverStickiness.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier3.Default.Stats.CoverStickiness.Value = 5.000000000e-01f;
    (*this).Tiers.Tier3.Default.Stats.CoverStickiness.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier3.Default.Stats.CoverStickiness.bOverloadValue = false;
    (*this).Tiers.Tier3.Default.Stats.ReactionIntensity.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier3.Default.Stats.ReactionIntensity.Value = 5.000000000e-01f;
    (*this).Tiers.Tier3.Default.Stats.ReactionIntensity.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier3.Default.Stats.ReactionIntensity.bOverloadValue = false;
    (*this).Tiers.Tier3.Default.Enabled = true;
    (*this).Tiers.Tier3.Default.Character.Controller = nullptr;
    (*this).Tiers.Tier3.Default.Character.Pawns.Empty();
    (*this).Tiers.Tier3.Default.Loadout.WeaponPool.PrimaryWeapons.Empty();
    (*this).Tiers.Tier3.Default.Loadout.WeaponPool.SecondaryWeapons.Empty();
    (*this).Tiers.Tier3.Default.Loadout.WeaponPool.MeleeWeapons.Empty();
    (*this).Tiers.Tier3.Default.Loadout.WeaponProbability.Empty();
    (*this).Tiers.Tier3.Default.Loadout.NoThrowableChance = 0;
    (*this).Tiers.Tier3.Default.Loadout.ThrowablePool.Empty();
    (*TBaseStructure<FGameplayTag>::Get()->FindPropertyByName("TagName")->ContainerPtrToValuePtr<FName>(&(*this).Tiers.Tier3.Default.Loadout.EmptyWeaponTag, 0)) = TEXT("Item.Wieldable.Weapon");
    (*this).Tiers.Tier3.Default.Loadout.ShowNoThrowableBool = 0;
    (*TBaseStructure<FGameplayTag>::Get()->FindPropertyByName("TagName")->ContainerPtrToValuePtr<FName>(&(*this).Tiers.Tier3.Default.Specialization, 0)) = TEXT("AI.Specialization.Default");
    (*this).Tiers.Tier3.Sniper.SpecStats.HitChance = 8.000000119e-01f;
    (*this).Tiers.Tier3.Sniper.SpecStats.HiddenTimeInterval.Min = 3.000000000e+00f;
    (*this).Tiers.Tier3.Sniper.SpecStats.HiddenTimeInterval.Max = 5.000000000e+00f;
    (*this).Tiers.Tier3.Sniper.SpecStats.CompromisedRange = 5.000000000e+02f;
    (*this).Tiers.Tier3.Sniper.SpecStats.WeaponVisibilityType = EIGS_WeaponVisibilityType::VT_Laser;
    (*this).Tiers.Tier3.Sniper.Stats.HP.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier3.Sniper.Stats.HP.Value = 2.800000000e+02f;
    (*this).Tiers.Tier3.Sniper.Stats.HP.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier3.Sniper.Stats.HP.bOverloadValue = false;
    (*this).Tiers.Tier3.Sniper.Stats.Shield.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier3.Sniper.Stats.Shield.Value = 0.000000000e+00f;
    (*this).Tiers.Tier3.Sniper.Stats.Shield.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier3.Sniper.Stats.Shield.bOverloadValue = false;
    (*this).Tiers.Tier3.Sniper.Stats.WeaponDamage.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier3.Sniper.Stats.WeaponDamage.Value = 1.000000000e+00f;
    (*this).Tiers.Tier3.Sniper.Stats.WeaponDamage.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier3.Sniper.Stats.WeaponDamage.bOverloadValue = false;
    (*this).Tiers.Tier3.Sniper.Stats.MeleeDamage.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier3.Sniper.Stats.MeleeDamage.Value = 1.000000000e+00f;
    (*this).Tiers.Tier3.Sniper.Stats.MeleeDamage.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier3.Sniper.Stats.MeleeDamage.bOverloadValue = false;
    (*this).Tiers.Tier3.Sniper.Stats.WeaponDispersion.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier3.Sniper.Stats.WeaponDispersion.Value = 1.000000000e+00f;
    (*this).Tiers.Tier3.Sniper.Stats.WeaponDispersion.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier3.Sniper.Stats.WeaponDispersion.bOverloadValue = false;
    (*this).Tiers.Tier3.Sniper.Stats.MovementSpeed.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier3.Sniper.Stats.MovementSpeed.Value = 1.000000000e+00f;
    (*this).Tiers.Tier3.Sniper.Stats.MovementSpeed.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier3.Sniper.Stats.MovementSpeed.bOverloadValue = false;
    (*this).Tiers.Tier3.Sniper.Stats.CoverStickiness.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier3.Sniper.Stats.CoverStickiness.Value = 5.000000000e-01f;
    (*this).Tiers.Tier3.Sniper.Stats.CoverStickiness.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier3.Sniper.Stats.CoverStickiness.bOverloadValue = false;
    (*this).Tiers.Tier3.Sniper.Stats.ReactionIntensity.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier3.Sniper.Stats.ReactionIntensity.Value = 5.000000000e-01f;
    (*this).Tiers.Tier3.Sniper.Stats.ReactionIntensity.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier3.Sniper.Stats.ReactionIntensity.bOverloadValue = false;
    (*this).Tiers.Tier3.Sniper.Enabled = true;
    (*this).Tiers.Tier3.Sniper.Character.Controller = nullptr;
    (*this).Tiers.Tier3.Sniper.Character.Pawns.Empty();
    (*this).Tiers.Tier3.Sniper.Loadout.WeaponPool.PrimaryWeapons.Empty();
    (*this).Tiers.Tier3.Sniper.Loadout.WeaponPool.SecondaryWeapons.Empty();
    (*this).Tiers.Tier3.Sniper.Loadout.WeaponPool.MeleeWeapons.Empty();
    (*this).Tiers.Tier3.Sniper.Loadout.WeaponProbability.Empty();
    (*this).Tiers.Tier3.Sniper.Loadout.NoThrowableChance = 0;
    (*this).Tiers.Tier3.Sniper.Loadout.ThrowablePool.Empty();
    (*TBaseStructure<FGameplayTag>::Get()->FindPropertyByName("TagName")->ContainerPtrToValuePtr<FName>(&(*this).Tiers.Tier3.Sniper.Loadout.EmptyWeaponTag, 0)) = TEXT("Item.Wieldable.Weapon");
    (*this).Tiers.Tier3.Sniper.Loadout.ShowNoThrowableBool = 0;
    (*TBaseStructure<FGameplayTag>::Get()->FindPropertyByName("TagName")->ContainerPtrToValuePtr<FName>(&(*this).Tiers.Tier3.Sniper.Specialization, 0)) = TEXT("AI.Specialization.Sniper");
    (*this).Tiers.Tier3.Shield.SpecStats.ShieldGlassHP = 3.000000000e+02f;
    (*this).Tiers.Tier3.Shield.Stats.HP.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier3.Shield.Stats.HP.Value = 2.800000000e+02f;
    (*this).Tiers.Tier3.Shield.Stats.HP.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier3.Shield.Stats.HP.bOverloadValue = false;
    (*this).Tiers.Tier3.Shield.Stats.Shield.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier3.Shield.Stats.Shield.Value = 0.000000000e+00f;
    (*this).Tiers.Tier3.Shield.Stats.Shield.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier3.Shield.Stats.Shield.bOverloadValue = false;
    (*this).Tiers.Tier3.Shield.Stats.WeaponDamage.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier3.Shield.Stats.WeaponDamage.Value = 1.000000000e+00f;
    (*this).Tiers.Tier3.Shield.Stats.WeaponDamage.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier3.Shield.Stats.WeaponDamage.bOverloadValue = false;
    (*this).Tiers.Tier3.Shield.Stats.MeleeDamage.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier3.Shield.Stats.MeleeDamage.Value = 1.000000000e+00f;
    (*this).Tiers.Tier3.Shield.Stats.MeleeDamage.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier3.Shield.Stats.MeleeDamage.bOverloadValue = false;
    (*this).Tiers.Tier3.Shield.Stats.WeaponDispersion.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier3.Shield.Stats.WeaponDispersion.Value = 1.000000000e+00f;
    (*this).Tiers.Tier3.Shield.Stats.WeaponDispersion.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier3.Shield.Stats.WeaponDispersion.bOverloadValue = false;
    (*this).Tiers.Tier3.Shield.Stats.MovementSpeed.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier3.Shield.Stats.MovementSpeed.Value = 1.000000000e+00f;
    (*this).Tiers.Tier3.Shield.Stats.MovementSpeed.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier3.Shield.Stats.MovementSpeed.bOverloadValue = false;
    (*this).Tiers.Tier3.Shield.Stats.CoverStickiness.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier3.Shield.Stats.CoverStickiness.Value = 5.000000000e-01f;
    (*this).Tiers.Tier3.Shield.Stats.CoverStickiness.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier3.Shield.Stats.CoverStickiness.bOverloadValue = false;
    (*this).Tiers.Tier3.Shield.Stats.ReactionIntensity.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier3.Shield.Stats.ReactionIntensity.Value = 5.000000000e-01f;
    (*this).Tiers.Tier3.Shield.Stats.ReactionIntensity.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier3.Shield.Stats.ReactionIntensity.bOverloadValue = false;
    (*this).Tiers.Tier3.Shield.Enabled = true;
    (*this).Tiers.Tier3.Shield.Character.Controller = nullptr;
    (*this).Tiers.Tier3.Shield.Character.Pawns.Empty();
    (*this).Tiers.Tier3.Shield.Loadout.WeaponPool.PrimaryWeapons.Empty();
    (*this).Tiers.Tier3.Shield.Loadout.WeaponPool.SecondaryWeapons.Empty();
    (*this).Tiers.Tier3.Shield.Loadout.WeaponPool.MeleeWeapons.Empty();
    (*this).Tiers.Tier3.Shield.Loadout.WeaponProbability.Empty();
    (*this).Tiers.Tier3.Shield.Loadout.NoThrowableChance = 0;
    (*this).Tiers.Tier3.Shield.Loadout.ThrowablePool.Empty();
    (*TBaseStructure<FGameplayTag>::Get()->FindPropertyByName("TagName")->ContainerPtrToValuePtr<FName>(&(*this).Tiers.Tier3.Shield.Loadout.EmptyWeaponTag, 0)) = TEXT("Item.Wieldable.Weapon");
    (*this).Tiers.Tier3.Shield.Loadout.ShowNoThrowableBool = 0;
    (*TBaseStructure<FGameplayTag>::Get()->FindPropertyByName("TagName")->ContainerPtrToValuePtr<FName>(&(*this).Tiers.Tier3.Shield.Specialization, 0)) = TEXT("AI.Specialization.Special.Shield");
    (*this).Tiers.Tier3.Heavy.SpecStats.Shock.ActivationDistance = 3.000000000e+02f;
    (*this).Tiers.Tier3.Heavy.SpecStats.Shock.Cooldown = 1.000000000e+01f;
    (*this).Tiers.Tier3.Heavy.SpecStats.Shock.Radius = 3.500000000e+02f;
    (*this).Tiers.Tier3.Heavy.SpecStats.Shock.Angle = 1.800000000e+02f;
    (*this).Tiers.Tier3.Heavy.SpecStats.Shock.ChargeTime = 2.000000000e+00f;
    (*this).Tiers.Tier3.Heavy.SpecStats.Shock.Damage = 1.000000000e+01f;
    (*this).Tiers.Tier3.Heavy.SpecStats.Shock.Count = 4;
    (*this).Tiers.Tier3.Heavy.SpecStats.Shock.Duration.Min = 3.750000000e+00f;
    (*this).Tiers.Tier3.Heavy.SpecStats.Shock.Duration.Max = 4.250000000e+00f;
    (*this).Tiers.Tier3.Heavy.SpecStats.WeakSpot.WeakSpotHealth = 1.000000000e+02f;
    (*this).Tiers.Tier3.Heavy.SpecStats.WeakSpot.DoomTimer.Min = 5.000000000e+00f;
    (*this).Tiers.Tier3.Heavy.SpecStats.WeakSpot.DoomTimer.Max = 1.000000000e+01f;
    (*this).Tiers.Tier3.Heavy.SpecStats.Injured.HealthToInjured = 2.500000000e+03f;
    (*this).Tiers.Tier3.Heavy.SpecStats.Injured.InjuredTime.Min = 6.000000000e+00f;
    (*this).Tiers.Tier3.Heavy.SpecStats.Injured.InjuredTime.Max = 7.500000000e+00f;
    (*this).Tiers.Tier3.Heavy.Stats.HP.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier3.Heavy.Stats.HP.Value = 2.800000000e+02f;
    (*this).Tiers.Tier3.Heavy.Stats.HP.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier3.Heavy.Stats.HP.bOverloadValue = false;
    (*this).Tiers.Tier3.Heavy.Stats.Shield.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier3.Heavy.Stats.Shield.Value = 0.000000000e+00f;
    (*this).Tiers.Tier3.Heavy.Stats.Shield.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier3.Heavy.Stats.Shield.bOverloadValue = false;
    (*this).Tiers.Tier3.Heavy.Stats.WeaponDamage.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier3.Heavy.Stats.WeaponDamage.Value = 1.000000000e+00f;
    (*this).Tiers.Tier3.Heavy.Stats.WeaponDamage.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier3.Heavy.Stats.WeaponDamage.bOverloadValue = false;
    (*this).Tiers.Tier3.Heavy.Stats.MeleeDamage.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier3.Heavy.Stats.MeleeDamage.Value = 1.000000000e+00f;
    (*this).Tiers.Tier3.Heavy.Stats.MeleeDamage.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier3.Heavy.Stats.MeleeDamage.bOverloadValue = false;
    (*this).Tiers.Tier3.Heavy.Stats.WeaponDispersion.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier3.Heavy.Stats.WeaponDispersion.Value = 1.000000000e+00f;
    (*this).Tiers.Tier3.Heavy.Stats.WeaponDispersion.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier3.Heavy.Stats.WeaponDispersion.bOverloadValue = false;
    (*this).Tiers.Tier3.Heavy.Stats.MovementSpeed.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier3.Heavy.Stats.MovementSpeed.Value = 1.000000000e+00f;
    (*this).Tiers.Tier3.Heavy.Stats.MovementSpeed.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier3.Heavy.Stats.MovementSpeed.bOverloadValue = false;
    (*this).Tiers.Tier3.Heavy.Stats.CoverStickiness.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier3.Heavy.Stats.CoverStickiness.Value = 5.000000000e-01f;
    (*this).Tiers.Tier3.Heavy.Stats.CoverStickiness.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier3.Heavy.Stats.CoverStickiness.bOverloadValue = false;
    (*this).Tiers.Tier3.Heavy.Stats.ReactionIntensity.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier3.Heavy.Stats.ReactionIntensity.Value = 5.000000000e-01f;
    (*this).Tiers.Tier3.Heavy.Stats.ReactionIntensity.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier3.Heavy.Stats.ReactionIntensity.bOverloadValue = false;
    (*this).Tiers.Tier3.Heavy.Enabled = true;
    (*this).Tiers.Tier3.Heavy.Character.Controller = nullptr;
    (*this).Tiers.Tier3.Heavy.Character.Pawns.Empty();
    (*this).Tiers.Tier3.Heavy.Loadout.WeaponPool.PrimaryWeapons.Empty();
    (*this).Tiers.Tier3.Heavy.Loadout.WeaponPool.SecondaryWeapons.Empty();
    (*this).Tiers.Tier3.Heavy.Loadout.WeaponPool.MeleeWeapons.Empty();
    (*this).Tiers.Tier3.Heavy.Loadout.WeaponProbability.Empty();
    (*this).Tiers.Tier3.Heavy.Loadout.NoThrowableChance = 0;
    (*this).Tiers.Tier3.Heavy.Loadout.ThrowablePool.Empty();
    (*TBaseStructure<FGameplayTag>::Get()->FindPropertyByName("TagName")->ContainerPtrToValuePtr<FName>(&(*this).Tiers.Tier3.Heavy.Loadout.EmptyWeaponTag, 0)) = TEXT("Item.Wieldable.Weapon");
    (*this).Tiers.Tier3.Heavy.Loadout.ShowNoThrowableBool = 0;
    (*TBaseStructure<FGameplayTag>::Get()->FindPropertyByName("TagName")->ContainerPtrToValuePtr<FName>(&(*this).Tiers.Tier3.Heavy.Specialization, 0)) = TEXT("AI.Specialization.Special.Heavy");
    (*this).Tiers.Tier3.HeavyScout.Stats.HP.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier3.HeavyScout.Stats.HP.Value = 2.800000000e+02f;
    (*this).Tiers.Tier3.HeavyScout.Stats.HP.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier3.HeavyScout.Stats.HP.bOverloadValue = false;
    (*this).Tiers.Tier3.HeavyScout.Stats.Shield.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier3.HeavyScout.Stats.Shield.Value = 0.000000000e+00f;
    (*this).Tiers.Tier3.HeavyScout.Stats.Shield.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier3.HeavyScout.Stats.Shield.bOverloadValue = false;
    (*this).Tiers.Tier3.HeavyScout.Stats.WeaponDamage.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier3.HeavyScout.Stats.WeaponDamage.Value = 1.000000000e+00f;
    (*this).Tiers.Tier3.HeavyScout.Stats.WeaponDamage.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier3.HeavyScout.Stats.WeaponDamage.bOverloadValue = false;
    (*this).Tiers.Tier3.HeavyScout.Stats.MeleeDamage.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier3.HeavyScout.Stats.MeleeDamage.Value = 1.000000000e+00f;
    (*this).Tiers.Tier3.HeavyScout.Stats.MeleeDamage.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier3.HeavyScout.Stats.MeleeDamage.bOverloadValue = false;
    (*this).Tiers.Tier3.HeavyScout.Stats.WeaponDispersion.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier3.HeavyScout.Stats.WeaponDispersion.Value = 1.000000000e+00f;
    (*this).Tiers.Tier3.HeavyScout.Stats.WeaponDispersion.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier3.HeavyScout.Stats.WeaponDispersion.bOverloadValue = false;
    (*this).Tiers.Tier3.HeavyScout.Stats.MovementSpeed.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier3.HeavyScout.Stats.MovementSpeed.Value = 1.000000000e+00f;
    (*this).Tiers.Tier3.HeavyScout.Stats.MovementSpeed.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier3.HeavyScout.Stats.MovementSpeed.bOverloadValue = false;
    (*this).Tiers.Tier3.HeavyScout.Stats.CoverStickiness.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier3.HeavyScout.Stats.CoverStickiness.Value = 5.000000000e-01f;
    (*this).Tiers.Tier3.HeavyScout.Stats.CoverStickiness.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier3.HeavyScout.Stats.CoverStickiness.bOverloadValue = false;
    (*this).Tiers.Tier3.HeavyScout.Stats.ReactionIntensity.Overload = 0.000000000e+00f;
    (*this).Tiers.Tier3.HeavyScout.Stats.ReactionIntensity.Value = 5.000000000e-01f;
    (*this).Tiers.Tier3.HeavyScout.Stats.ReactionIntensity.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Tier3.HeavyScout.Stats.ReactionIntensity.bOverloadValue = false;
    (*this).Tiers.Tier3.HeavyScout.Enabled = true;
    (*this).Tiers.Tier3.HeavyScout.Character.Controller = nullptr;
    (*this).Tiers.Tier3.HeavyScout.Character.Pawns.Empty();
    (*this).Tiers.Tier3.HeavyScout.Loadout.WeaponPool.PrimaryWeapons.Empty();
    (*this).Tiers.Tier3.HeavyScout.Loadout.WeaponPool.SecondaryWeapons.Empty();
    (*this).Tiers.Tier3.HeavyScout.Loadout.WeaponPool.MeleeWeapons.Empty();
    (*this).Tiers.Tier3.HeavyScout.Loadout.WeaponProbability.Empty();
    (*this).Tiers.Tier3.HeavyScout.Loadout.NoThrowableChance = 0;
    (*this).Tiers.Tier3.HeavyScout.Loadout.ThrowablePool.Empty();
    (*TBaseStructure<FGameplayTag>::Get()->FindPropertyByName("TagName")->ContainerPtrToValuePtr<FName>(&(*this).Tiers.Tier3.HeavyScout.Loadout.EmptyWeaponTag, 0)) = TEXT("Item.Wieldable.Weapon");
    (*this).Tiers.Tier3.HeavyScout.Loadout.ShowNoThrowableBool = 0;
    (*TBaseStructure<FGameplayTag>::Get()->FindPropertyByName("TagName")->ContainerPtrToValuePtr<FName>(&(*this).Tiers.Tier3.HeavyScout.Specialization, 0)) = TEXT("AI.Specialization.Special.Scout.Heavy");
    (*this).Tiers.Special.Default.Stats.HP.Overload = 0.000000000e+00f;
    (*this).Tiers.Special.Default.Stats.HP.Value = 2.800000000e+02f;
    (*this).Tiers.Special.Default.Stats.HP.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Special.Default.Stats.HP.bOverloadValue = false;
    (*this).Tiers.Special.Default.Stats.Shield.Overload = 0.000000000e+00f;
    (*this).Tiers.Special.Default.Stats.Shield.Value = 0.000000000e+00f;
    (*this).Tiers.Special.Default.Stats.Shield.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Special.Default.Stats.Shield.bOverloadValue = false;
    (*this).Tiers.Special.Default.Stats.WeaponDamage.Overload = 0.000000000e+00f;
    (*this).Tiers.Special.Default.Stats.WeaponDamage.Value = 1.000000000e+00f;
    (*this).Tiers.Special.Default.Stats.WeaponDamage.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Special.Default.Stats.WeaponDamage.bOverloadValue = false;
    (*this).Tiers.Special.Default.Stats.MeleeDamage.Overload = 0.000000000e+00f;
    (*this).Tiers.Special.Default.Stats.MeleeDamage.Value = 1.000000000e+00f;
    (*this).Tiers.Special.Default.Stats.MeleeDamage.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Special.Default.Stats.MeleeDamage.bOverloadValue = false;
    (*this).Tiers.Special.Default.Stats.WeaponDispersion.Overload = 0.000000000e+00f;
    (*this).Tiers.Special.Default.Stats.WeaponDispersion.Value = 1.000000000e+00f;
    (*this).Tiers.Special.Default.Stats.WeaponDispersion.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Special.Default.Stats.WeaponDispersion.bOverloadValue = false;
    (*this).Tiers.Special.Default.Stats.MovementSpeed.Overload = 0.000000000e+00f;
    (*this).Tiers.Special.Default.Stats.MovementSpeed.Value = 1.000000000e+00f;
    (*this).Tiers.Special.Default.Stats.MovementSpeed.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Special.Default.Stats.MovementSpeed.bOverloadValue = false;
    (*this).Tiers.Special.Default.Stats.CoverStickiness.Overload = 0.000000000e+00f;
    (*this).Tiers.Special.Default.Stats.CoverStickiness.Value = 5.000000000e-01f;
    (*this).Tiers.Special.Default.Stats.CoverStickiness.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Special.Default.Stats.CoverStickiness.bOverloadValue = false;
    (*this).Tiers.Special.Default.Stats.ReactionIntensity.Overload = 0.000000000e+00f;
    (*this).Tiers.Special.Default.Stats.ReactionIntensity.Value = 5.000000000e-01f;
    (*this).Tiers.Special.Default.Stats.ReactionIntensity.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Special.Default.Stats.ReactionIntensity.bOverloadValue = false;
    (*this).Tiers.Special.Default.Enabled = true;
    (*this).Tiers.Special.Default.Character.Controller = nullptr;
    (*this).Tiers.Special.Default.Character.Pawns.Empty();
    (*this).Tiers.Special.Default.Loadout.WeaponPool.PrimaryWeapons.Empty();
    (*this).Tiers.Special.Default.Loadout.WeaponPool.SecondaryWeapons.Empty();
    (*this).Tiers.Special.Default.Loadout.WeaponPool.MeleeWeapons.Empty();
    (*this).Tiers.Special.Default.Loadout.WeaponProbability.Empty();
    (*this).Tiers.Special.Default.Loadout.NoThrowableChance = 0;
    (*this).Tiers.Special.Default.Loadout.ThrowablePool.Empty();
    (*TBaseStructure<FGameplayTag>::Get()->FindPropertyByName("TagName")->ContainerPtrToValuePtr<FName>(&(*this).Tiers.Special.Default.Loadout.EmptyWeaponTag, 0)) = TEXT("Item.Wieldable.Weapon");
    (*this).Tiers.Special.Default.Loadout.ShowNoThrowableBool = 0;
    (*TBaseStructure<FGameplayTag>::Get()->FindPropertyByName("TagName")->ContainerPtrToValuePtr<FName>(&(*this).Tiers.Special.Default.Specialization, 0)) = TEXT("AI.Specialization.Default");
    (*this).Tiers.Special.Sniper.SpecStats.HitChance = 8.000000119e-01f;
    (*this).Tiers.Special.Sniper.SpecStats.HiddenTimeInterval.Min = 3.000000000e+00f;
    (*this).Tiers.Special.Sniper.SpecStats.HiddenTimeInterval.Max = 5.000000000e+00f;
    (*this).Tiers.Special.Sniper.SpecStats.CompromisedRange = 5.000000000e+02f;
    (*this).Tiers.Special.Sniper.SpecStats.WeaponVisibilityType = EIGS_WeaponVisibilityType::VT_Laser;
    (*this).Tiers.Special.Sniper.Stats.HP.Overload = 0.000000000e+00f;
    (*this).Tiers.Special.Sniper.Stats.HP.Value = 2.800000000e+02f;
    (*this).Tiers.Special.Sniper.Stats.HP.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Special.Sniper.Stats.HP.bOverloadValue = false;
    (*this).Tiers.Special.Sniper.Stats.Shield.Overload = 0.000000000e+00f;
    (*this).Tiers.Special.Sniper.Stats.Shield.Value = 0.000000000e+00f;
    (*this).Tiers.Special.Sniper.Stats.Shield.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Special.Sniper.Stats.Shield.bOverloadValue = false;
    (*this).Tiers.Special.Sniper.Stats.WeaponDamage.Overload = 0.000000000e+00f;
    (*this).Tiers.Special.Sniper.Stats.WeaponDamage.Value = 1.000000000e+00f;
    (*this).Tiers.Special.Sniper.Stats.WeaponDamage.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Special.Sniper.Stats.WeaponDamage.bOverloadValue = false;
    (*this).Tiers.Special.Sniper.Stats.MeleeDamage.Overload = 0.000000000e+00f;
    (*this).Tiers.Special.Sniper.Stats.MeleeDamage.Value = 1.000000000e+00f;
    (*this).Tiers.Special.Sniper.Stats.MeleeDamage.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Special.Sniper.Stats.MeleeDamage.bOverloadValue = false;
    (*this).Tiers.Special.Sniper.Stats.WeaponDispersion.Overload = 0.000000000e+00f;
    (*this).Tiers.Special.Sniper.Stats.WeaponDispersion.Value = 1.000000000e+00f;
    (*this).Tiers.Special.Sniper.Stats.WeaponDispersion.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Special.Sniper.Stats.WeaponDispersion.bOverloadValue = false;
    (*this).Tiers.Special.Sniper.Stats.MovementSpeed.Overload = 0.000000000e+00f;
    (*this).Tiers.Special.Sniper.Stats.MovementSpeed.Value = 1.000000000e+00f;
    (*this).Tiers.Special.Sniper.Stats.MovementSpeed.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Special.Sniper.Stats.MovementSpeed.bOverloadValue = false;
    (*this).Tiers.Special.Sniper.Stats.CoverStickiness.Overload = 0.000000000e+00f;
    (*this).Tiers.Special.Sniper.Stats.CoverStickiness.Value = 5.000000000e-01f;
    (*this).Tiers.Special.Sniper.Stats.CoverStickiness.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Special.Sniper.Stats.CoverStickiness.bOverloadValue = false;
    (*this).Tiers.Special.Sniper.Stats.ReactionIntensity.Overload = 0.000000000e+00f;
    (*this).Tiers.Special.Sniper.Stats.ReactionIntensity.Value = 5.000000000e-01f;
    (*this).Tiers.Special.Sniper.Stats.ReactionIntensity.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Special.Sniper.Stats.ReactionIntensity.bOverloadValue = false;
    (*this).Tiers.Special.Sniper.Enabled = true;
    (*this).Tiers.Special.Sniper.Character.Controller = nullptr;
    (*this).Tiers.Special.Sniper.Character.Pawns.Empty();
    (*this).Tiers.Special.Sniper.Loadout.WeaponPool.PrimaryWeapons.Empty();
    (*this).Tiers.Special.Sniper.Loadout.WeaponPool.SecondaryWeapons.Empty();
    (*this).Tiers.Special.Sniper.Loadout.WeaponPool.MeleeWeapons.Empty();
    (*this).Tiers.Special.Sniper.Loadout.WeaponProbability.Empty();
    (*this).Tiers.Special.Sniper.Loadout.NoThrowableChance = 0;
    (*this).Tiers.Special.Sniper.Loadout.ThrowablePool.Empty();
    (*TBaseStructure<FGameplayTag>::Get()->FindPropertyByName("TagName")->ContainerPtrToValuePtr<FName>(&(*this).Tiers.Special.Sniper.Loadout.EmptyWeaponTag, 0)) = TEXT("Item.Wieldable.Weapon");
    (*this).Tiers.Special.Sniper.Loadout.ShowNoThrowableBool = 0;
    (*TBaseStructure<FGameplayTag>::Get()->FindPropertyByName("TagName")->ContainerPtrToValuePtr<FName>(&(*this).Tiers.Special.Sniper.Specialization, 0)) = TEXT("AI.Specialization.Sniper");
    (*this).Tiers.Special.Shield.SpecStats.ShieldGlassHP = 3.000000000e+02f;
    (*this).Tiers.Special.Shield.Stats.HP.Overload = 0.000000000e+00f;
    (*this).Tiers.Special.Shield.Stats.HP.Value = 2.800000000e+02f;
    (*this).Tiers.Special.Shield.Stats.HP.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Special.Shield.Stats.HP.bOverloadValue = false;
    (*this).Tiers.Special.Shield.Stats.Shield.Overload = 0.000000000e+00f;
    (*this).Tiers.Special.Shield.Stats.Shield.Value = 0.000000000e+00f;
    (*this).Tiers.Special.Shield.Stats.Shield.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Special.Shield.Stats.Shield.bOverloadValue = false;
    (*this).Tiers.Special.Shield.Stats.WeaponDamage.Overload = 0.000000000e+00f;
    (*this).Tiers.Special.Shield.Stats.WeaponDamage.Value = 1.000000000e+00f;
    (*this).Tiers.Special.Shield.Stats.WeaponDamage.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Special.Shield.Stats.WeaponDamage.bOverloadValue = false;
    (*this).Tiers.Special.Shield.Stats.MeleeDamage.Overload = 0.000000000e+00f;
    (*this).Tiers.Special.Shield.Stats.MeleeDamage.Value = 1.000000000e+00f;
    (*this).Tiers.Special.Shield.Stats.MeleeDamage.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Special.Shield.Stats.MeleeDamage.bOverloadValue = false;
    (*this).Tiers.Special.Shield.Stats.WeaponDispersion.Overload = 0.000000000e+00f;
    (*this).Tiers.Special.Shield.Stats.WeaponDispersion.Value = 1.000000000e+00f;
    (*this).Tiers.Special.Shield.Stats.WeaponDispersion.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Special.Shield.Stats.WeaponDispersion.bOverloadValue = false;
    (*this).Tiers.Special.Shield.Stats.MovementSpeed.Overload = 0.000000000e+00f;
    (*this).Tiers.Special.Shield.Stats.MovementSpeed.Value = 1.000000000e+00f;
    (*this).Tiers.Special.Shield.Stats.MovementSpeed.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Special.Shield.Stats.MovementSpeed.bOverloadValue = false;
    (*this).Tiers.Special.Shield.Stats.CoverStickiness.Overload = 0.000000000e+00f;
    (*this).Tiers.Special.Shield.Stats.CoverStickiness.Value = 5.000000000e-01f;
    (*this).Tiers.Special.Shield.Stats.CoverStickiness.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Special.Shield.Stats.CoverStickiness.bOverloadValue = false;
    (*this).Tiers.Special.Shield.Stats.ReactionIntensity.Overload = 0.000000000e+00f;
    (*this).Tiers.Special.Shield.Stats.ReactionIntensity.Value = 5.000000000e-01f;
    (*this).Tiers.Special.Shield.Stats.ReactionIntensity.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Special.Shield.Stats.ReactionIntensity.bOverloadValue = false;
    (*this).Tiers.Special.Shield.Enabled = true;
    (*this).Tiers.Special.Shield.Character.Controller = nullptr;
    (*this).Tiers.Special.Shield.Character.Pawns.Empty();
    (*this).Tiers.Special.Shield.Loadout.WeaponPool.PrimaryWeapons.Empty();
    (*this).Tiers.Special.Shield.Loadout.WeaponPool.SecondaryWeapons.Empty();
    (*this).Tiers.Special.Shield.Loadout.WeaponPool.MeleeWeapons.Empty();
    (*this).Tiers.Special.Shield.Loadout.WeaponProbability.Empty();
    (*this).Tiers.Special.Shield.Loadout.NoThrowableChance = 0;
    (*this).Tiers.Special.Shield.Loadout.ThrowablePool.Empty();
    (*TBaseStructure<FGameplayTag>::Get()->FindPropertyByName("TagName")->ContainerPtrToValuePtr<FName>(&(*this).Tiers.Special.Shield.Loadout.EmptyWeaponTag, 0)) = TEXT("Item.Wieldable.Weapon");
    (*this).Tiers.Special.Shield.Loadout.ShowNoThrowableBool = 0;
    (*TBaseStructure<FGameplayTag>::Get()->FindPropertyByName("TagName")->ContainerPtrToValuePtr<FName>(&(*this).Tiers.Special.Shield.Specialization, 0)) = TEXT("AI.Specialization.Special.Shield");
    (*this).Tiers.Special.Heavy.SpecStats.Shock.ActivationDistance = 3.000000000e+02f;
    (*this).Tiers.Special.Heavy.SpecStats.Shock.Cooldown = 1.000000000e+01f;
    (*this).Tiers.Special.Heavy.SpecStats.Shock.Radius = 3.500000000e+02f;
    (*this).Tiers.Special.Heavy.SpecStats.Shock.Angle = 1.800000000e+02f;
    (*this).Tiers.Special.Heavy.SpecStats.Shock.ChargeTime = 2.000000000e+00f;
    (*this).Tiers.Special.Heavy.SpecStats.Shock.Damage = 1.000000000e+01f;
    (*this).Tiers.Special.Heavy.SpecStats.Shock.Count = 4;
    (*this).Tiers.Special.Heavy.SpecStats.Shock.Duration.Min = 3.750000000e+00f;
    (*this).Tiers.Special.Heavy.SpecStats.Shock.Duration.Max = 4.250000000e+00f;
    (*this).Tiers.Special.Heavy.SpecStats.WeakSpot.WeakSpotHealth = 1.000000000e+02f;
    (*this).Tiers.Special.Heavy.SpecStats.WeakSpot.DoomTimer.Min = 5.000000000e+00f;
    (*this).Tiers.Special.Heavy.SpecStats.WeakSpot.DoomTimer.Max = 1.000000000e+01f;
    (*this).Tiers.Special.Heavy.SpecStats.Injured.HealthToInjured = 2.500000000e+03f;
    (*this).Tiers.Special.Heavy.SpecStats.Injured.InjuredTime.Min = 6.000000000e+00f;
    (*this).Tiers.Special.Heavy.SpecStats.Injured.InjuredTime.Max = 7.500000000e+00f;
    (*this).Tiers.Special.Heavy.Stats.HP.Overload = 0.000000000e+00f;
    (*this).Tiers.Special.Heavy.Stats.HP.Value = 2.800000000e+02f;
    (*this).Tiers.Special.Heavy.Stats.HP.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Special.Heavy.Stats.HP.bOverloadValue = false;
    (*this).Tiers.Special.Heavy.Stats.Shield.Overload = 0.000000000e+00f;
    (*this).Tiers.Special.Heavy.Stats.Shield.Value = 0.000000000e+00f;
    (*this).Tiers.Special.Heavy.Stats.Shield.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Special.Heavy.Stats.Shield.bOverloadValue = false;
    (*this).Tiers.Special.Heavy.Stats.WeaponDamage.Overload = 0.000000000e+00f;
    (*this).Tiers.Special.Heavy.Stats.WeaponDamage.Value = 1.000000000e+00f;
    (*this).Tiers.Special.Heavy.Stats.WeaponDamage.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Special.Heavy.Stats.WeaponDamage.bOverloadValue = false;
    (*this).Tiers.Special.Heavy.Stats.MeleeDamage.Overload = 0.000000000e+00f;
    (*this).Tiers.Special.Heavy.Stats.MeleeDamage.Value = 1.000000000e+00f;
    (*this).Tiers.Special.Heavy.Stats.MeleeDamage.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Special.Heavy.Stats.MeleeDamage.bOverloadValue = false;
    (*this).Tiers.Special.Heavy.Stats.WeaponDispersion.Overload = 0.000000000e+00f;
    (*this).Tiers.Special.Heavy.Stats.WeaponDispersion.Value = 1.000000000e+00f;
    (*this).Tiers.Special.Heavy.Stats.WeaponDispersion.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Special.Heavy.Stats.WeaponDispersion.bOverloadValue = false;
    (*this).Tiers.Special.Heavy.Stats.MovementSpeed.Overload = 0.000000000e+00f;
    (*this).Tiers.Special.Heavy.Stats.MovementSpeed.Value = 1.000000000e+00f;
    (*this).Tiers.Special.Heavy.Stats.MovementSpeed.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Special.Heavy.Stats.MovementSpeed.bOverloadValue = false;
    (*this).Tiers.Special.Heavy.Stats.CoverStickiness.Overload = 0.000000000e+00f;
    (*this).Tiers.Special.Heavy.Stats.CoverStickiness.Value = 5.000000000e-01f;
    (*this).Tiers.Special.Heavy.Stats.CoverStickiness.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Special.Heavy.Stats.CoverStickiness.bOverloadValue = false;
    (*this).Tiers.Special.Heavy.Stats.ReactionIntensity.Overload = 0.000000000e+00f;
    (*this).Tiers.Special.Heavy.Stats.ReactionIntensity.Value = 5.000000000e-01f;
    (*this).Tiers.Special.Heavy.Stats.ReactionIntensity.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Special.Heavy.Stats.ReactionIntensity.bOverloadValue = false;
    (*this).Tiers.Special.Heavy.Enabled = true;
    (*this).Tiers.Special.Heavy.Character.Controller = nullptr;
    (*this).Tiers.Special.Heavy.Character.Pawns.Empty();
    (*this).Tiers.Special.Heavy.Loadout.WeaponPool.PrimaryWeapons.Empty();
    (*this).Tiers.Special.Heavy.Loadout.WeaponPool.SecondaryWeapons.Empty();
    (*this).Tiers.Special.Heavy.Loadout.WeaponPool.MeleeWeapons.Empty();
    (*this).Tiers.Special.Heavy.Loadout.WeaponProbability.Empty();
    (*this).Tiers.Special.Heavy.Loadout.NoThrowableChance = 0;
    (*this).Tiers.Special.Heavy.Loadout.ThrowablePool.Empty();
    (*TBaseStructure<FGameplayTag>::Get()->FindPropertyByName("TagName")->ContainerPtrToValuePtr<FName>(&(*this).Tiers.Special.Heavy.Loadout.EmptyWeaponTag, 0)) = TEXT("Item.Wieldable.Weapon");
    (*this).Tiers.Special.Heavy.Loadout.ShowNoThrowableBool = 0;
    (*TBaseStructure<FGameplayTag>::Get()->FindPropertyByName("TagName")->ContainerPtrToValuePtr<FName>(&(*this).Tiers.Special.Heavy.Specialization, 0)) = TEXT("AI.Specialization.Special.Heavy");
    (*this).Tiers.Special.HeavyScout.Stats.HP.Overload = 0.000000000e+00f;
    (*this).Tiers.Special.HeavyScout.Stats.HP.Value = 2.800000000e+02f;
    (*this).Tiers.Special.HeavyScout.Stats.HP.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Special.HeavyScout.Stats.HP.bOverloadValue = false;
    (*this).Tiers.Special.HeavyScout.Stats.Shield.Overload = 0.000000000e+00f;
    (*this).Tiers.Special.HeavyScout.Stats.Shield.Value = 0.000000000e+00f;
    (*this).Tiers.Special.HeavyScout.Stats.Shield.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Special.HeavyScout.Stats.Shield.bOverloadValue = false;
    (*this).Tiers.Special.HeavyScout.Stats.WeaponDamage.Overload = 0.000000000e+00f;
    (*this).Tiers.Special.HeavyScout.Stats.WeaponDamage.Value = 1.000000000e+00f;
    (*this).Tiers.Special.HeavyScout.Stats.WeaponDamage.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Special.HeavyScout.Stats.WeaponDamage.bOverloadValue = false;
    (*this).Tiers.Special.HeavyScout.Stats.MeleeDamage.Overload = 0.000000000e+00f;
    (*this).Tiers.Special.HeavyScout.Stats.MeleeDamage.Value = 1.000000000e+00f;
    (*this).Tiers.Special.HeavyScout.Stats.MeleeDamage.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Special.HeavyScout.Stats.MeleeDamage.bOverloadValue = false;
    (*this).Tiers.Special.HeavyScout.Stats.WeaponDispersion.Overload = 0.000000000e+00f;
    (*this).Tiers.Special.HeavyScout.Stats.WeaponDispersion.Value = 1.000000000e+00f;
    (*this).Tiers.Special.HeavyScout.Stats.WeaponDispersion.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Special.HeavyScout.Stats.WeaponDispersion.bOverloadValue = false;
    (*this).Tiers.Special.HeavyScout.Stats.MovementSpeed.Overload = 0.000000000e+00f;
    (*this).Tiers.Special.HeavyScout.Stats.MovementSpeed.Value = 1.000000000e+00f;
    (*this).Tiers.Special.HeavyScout.Stats.MovementSpeed.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Special.HeavyScout.Stats.MovementSpeed.bOverloadValue = false;
    (*this).Tiers.Special.HeavyScout.Stats.CoverStickiness.Overload = 0.000000000e+00f;
    (*this).Tiers.Special.HeavyScout.Stats.CoverStickiness.Value = 5.000000000e-01f;
    (*this).Tiers.Special.HeavyScout.Stats.CoverStickiness.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Special.HeavyScout.Stats.CoverStickiness.bOverloadValue = false;
    (*this).Tiers.Special.HeavyScout.Stats.ReactionIntensity.Overload = 0.000000000e+00f;
    (*this).Tiers.Special.HeavyScout.Stats.ReactionIntensity.Value = 5.000000000e-01f;
    (*this).Tiers.Special.HeavyScout.Stats.ReactionIntensity.Multiplier = 1.000000000e+00f;
    (*this).Tiers.Special.HeavyScout.Stats.ReactionIntensity.bOverloadValue = false;
    (*this).Tiers.Special.HeavyScout.Enabled = true;
    (*this).Tiers.Special.HeavyScout.Character.Controller = nullptr;
    (*this).Tiers.Special.HeavyScout.Character.Pawns.Empty();
    (*this).Tiers.Special.HeavyScout.Loadout.WeaponPool.PrimaryWeapons.Empty();
    (*this).Tiers.Special.HeavyScout.Loadout.WeaponPool.SecondaryWeapons.Empty();
    (*this).Tiers.Special.HeavyScout.Loadout.WeaponPool.MeleeWeapons.Empty();
    (*this).Tiers.Special.HeavyScout.Loadout.WeaponProbability.Empty();
    (*this).Tiers.Special.HeavyScout.Loadout.NoThrowableChance = 0;
    (*this).Tiers.Special.HeavyScout.Loadout.ThrowablePool.Empty();
    (*TBaseStructure<FGameplayTag>::Get()->FindPropertyByName("TagName")->ContainerPtrToValuePtr<FName>(&(*this).Tiers.Special.HeavyScout.Loadout.EmptyWeaponTag, 0)) = TEXT("Item.Wieldable.Weapon");
    (*this).Tiers.Special.HeavyScout.Loadout.ShowNoThrowableBool = 0;
    (*TBaseStructure<FGameplayTag>::Get()->FindPropertyByName("TagName")->ContainerPtrToValuePtr<FName>(&(*this).Tiers.Special.HeavyScout.Specialization, 0)) = TEXT("AI.Specialization.Special.Scout.Heavy");
    (*this).Tiers.TierSelection = 0;
    (*this).DefaultStats.HP = 2.800000000e+02f;
    (*this).DefaultStats.Shield = 0.000000000e+00f;
    (*this).DefaultStats.WeaponDamage = 1.000000000e+00f;
    (*this).DefaultStats.MeleeDamage = 1.000000000e+00f;
    (*this).DefaultStats.WeaponDispersion = 1.000000000e+00f;
    (*this).DefaultStats.MovementSpeed = 1.000000000e+00f;
    (*this).DefaultStats.CoverPreset = EIGS_CoverPreset::AICS_None;
    (*this).DefaultStats.CoverStickiness = 5.000000000e-01f;
    (*this).DefaultStats.ReactionIntensity = 5.000000000e-01f;
    (*this).TeamSide = EIGS_TeamSideEnum::TS_SWAT;
}

