#pragma once
#include "CoreMinimal.h"
#include "EIGS_MetaDialogueCharacter.generated.h"

UENUM(BlueprintType)
enum class EIGS_MetaDialogueCharacter : uint8 {
    None,
    GenericHeister = 29,
    Cracker,
    Chase,
    Ropes,
    Mozart,
    Tuna,
    Forehand,
    Smoke,
    Lector,
    MrX,
    Wiz,
    Tulip,
    Ranger,
    Stinger,
    Runaway,
    Jupiter,
    Vamp,
    Peak,
    Silver,
    Clutch,
    Volk,
    MotherTheresa,
    TravisBakerHeister,
    Hitman1 = 100,
    Informer1,
    Thief2,
    Thief1,
    GenericNeutralM1,
    GenericNeutralM2,
    GenericNeutralF1,
    GenericLatinxM1,
    GenericLatinxM2,
    GenericLatinxF1,
    GenericBlackM1,
    GenericBlackM2,
    GenericBlackF1,
    GenericVendor = 179,
    VendorIce,
    VendorLarry,
    VendorKhan,
    VendorDollar,
    VendorCagnali,
    TravisBaker = 200,
    TheHand,
    TheCaptain,
    TheAgent,
    Casey,
    DollarDragon,
    Ice,
    Sheriff,
    Carlos,
    Rina,
    Smith,
    Khan,
    KhansGangster,
    Cagnali,
    BillyBenton,
    Luna,
    BakersThug,
    Tourist1,
    Tourist2,
    Bartender,
    CraneWorker,
    Girl1,
    Girl2,
    Cop1,
    Cop2,
    Eduardo,
    Witch,
    Ronin,
    BarGirl,
    Servo,
    Empty = 254,
    Custom,
};

