#include "IGS_SaveData_Account.h"
#include "GameFramework/OnlineReplStructs.h"
#include "EIGS_GangsterVariationType.h"
#include "EIGS_TeamSideEnum.h"
#include "EMETA_CharacterState.h"
#include "EMETA_RespectLvl.h"

FIGS_SaveData_Account::FIGS_SaveData_Account() {
    (*this).AccountName = FText::FromString(TEXT("Default Account Name"));
    (*this).bDebug = false;
    (*this).bReadEULA = false;
    (*this).bReadSaveWarning = false;
    (*this).bFirstCrimeTime = true;
    (*this).bCheckedVeteranPlayer = false;
    (*this).bIsVeteranPlayer = false;
    (*this).bSeenProgressionReset = false;
    (*this).bWantedProgressionResetCompensation = false;
    auto& gen2116 = (*this).UnlockedCharactersAccWide;
    gen2116.Empty();
    (*this).TimePlayed = 0.000000000e+00f;
    (*TBaseStructure<FGameplayTag>::Get()->FindPropertyByName("TagName")->ContainerPtrToValuePtr<FName>(&(*this).QuickPlayPreferences.PlayerHeisterData.TagID, 0)) = NAME_None;
    (*this).QuickPlayPreferences.PlayerHeisterData.CharacterID = EIGS_CharacterID::Char_Unknown;
    (*this).QuickPlayPreferences.PlayerHeisterData.UniqGenericId = -1;
    (*this).QuickPlayPreferences.PlayerHeisterData.GenericVariantID = -1;
    (*this).QuickPlayPreferences.PlayerHeisterData.CharacterName = FText::FromString(TEXT(""));
    (*this).QuickPlayPreferences.PlayerHeisterData.bIsMaxLeveled = false;
    (*this).QuickPlayPreferences.PlayerHeisterData.HeisterNumber = -1;
    (*this).QuickPlayPreferences.PlayerHeisterData.PlayerId = -1;
    (*this).QuickPlayPreferences.PlayerHeisterData.ProgressionLevel = 1;
    auto& gen2117 = (*TBaseStructure<FUniqueNetIdRepl>::Get()->FindPropertyByName("ReplicationBytes")->ContainerPtrToValuePtr<TArray<uint8>>(&(*this).QuickPlayPreferences.PlayerHeisterData.UniquePlayerId, 0));
    gen2117.Empty();
    (*this).QuickPlayPreferences.PlayerHeisterData.Loadout.PrimaryWeapon = nullptr;
    (*TBaseStructure<FGameplayTag>::Get()->FindPropertyByName("TagName")->ContainerPtrToValuePtr<FName>(&(*this).QuickPlayPreferences.PlayerHeisterData.Loadout.PrimaryWeaponSkin, 0)) = NAME_None;
    (*this).QuickPlayPreferences.PlayerHeisterData.Loadout.SecondaryWeapon = nullptr;
    (*TBaseStructure<FGameplayTag>::Get()->FindPropertyByName("TagName")->ContainerPtrToValuePtr<FName>(&(*this).QuickPlayPreferences.PlayerHeisterData.Loadout.SecondaryWeaponSkin, 0)) = NAME_None;
    auto& gen2118 = (*this).QuickPlayPreferences.PlayerHeisterData.Loadout.Equipment;
    gen2118.Empty();
    auto& gen2119 = (*this).QuickPlayPreferences.PlayerHeisterData.Loadout.Perks;
    gen2119.Empty();
    (*this).QuickPlayPreferences.PlayerHeisterData.Loadout.Ability1ChargesLeft = -1;
    (*TBaseStructure<FGameplayTag>::Get()->FindPropertyByName("TagName")->ContainerPtrToValuePtr<FName>(&(*this).QuickPlayPreferences.PlayerHeisterData.Loadout.CharacterSkinID, 0)) = NAME_None;
    (*this).QuickPlayPreferences.PlayerHeisterData.Experience = 0;
    (*this).QuickPlayPreferences.PlayerHeisterData.Injuries = 0;
    (*this).QuickPlayPreferences.PlayerHeisterData.CharacterState = EMETA_CharacterState::None;
    (*this).QuickPlayPreferences.PlayerHeisterData.IsBot = false;
    (*this).QuickPlayPreferences.PlayerHeisterData.bUseCustomLoadout = false;
    (*this).QuickPlayPreferences.PlayerHeisterData.bComesFromMeta = false;
    (*this).QuickPlayPreferences.PlayerHeisterData.MissionStats.Kills = -1;
    (*this).QuickPlayPreferences.PlayerHeisterData.MissionStats.Accuracy = -1.000000000e+00f;
    (*this).QuickPlayPreferences.PlayerHeisterData.MissionStats.RevivesLeft = -1.000000000e+00f;
    (*this).QuickPlayPreferences.PlayerHeisterData.MissionStats.CollectedMoney = 0.000000000e+00f;
    (*this).QuickPlayPreferences.PlayerHeisterData.KilledByTeamSide = EIGS_TeamSideEnum::TS_Unknown;
    (*this).QuickPlayPreferences.PlayerHeisterData.KilledByGangsterVariation = EIGS_GangsterVariationType::US_None;
    (*this).QuickPlayPreferences.PlayerHeisterData.PlayerRespect = EMETA_RespectLvl::Low;
    (*this).QuickPlayPreferences.PlayerHeisterData.MutableVariationIndex = -1;
    (*this).QuickPlayPreferences.PlayerHeisterData.MissionCutPercentWithModifiers = 0;
    (*this).QuickPlayPreferences.PlayerHeisterData.CachedPlayerName = FText::FromString(TEXT(""));
    (*this).QuickPlayPreferences.bKeepCustomizedLoadout = false;
    auto& gen2120 = (*this).PendingUnlockRewards;
    gen2120.Empty();
    (*this).BossLevelData.CurrentBossLevel = 0;
    (*this).BossLevelData.MaxBossPointsToNextLevel = 0;
    (*this).BossLevelData.AccumulatedBossPointsToNextLevel = 0.000000000e+00f;
    auto& gen2121 = (*this).BossLevelData.PreparedBonuses;
    gen2121.Empty();
    (*this).BossLevelData.RemainingLvlUps = 0;
    (*this).BossLevelData.LastSeenLvlUpScreen = 1;
    (*this).CityMapData.LastPlayerTileGroupIndex = 0;
    auto& gen2122 = (*this).CityMapData.LastPlayerInitialTileGroup;
    gen2122.Empty();
    auto& gen2123 = (*TBaseStructure<FGameplayTagContainer>::Get()->FindPropertyByName("GameplayTags")->ContainerPtrToValuePtr<TArray<FGameplayTag>>(&(*this).MetaPersistentAssetData, 0));
    gen2123.Empty();
    auto& gen2124 = (*TBaseStructure<FGameplayTagContainer>::Get()->FindPropertyByName("ParentTags")->ContainerPtrToValuePtr<TArray<FGameplayTag>>(&(*this).MetaPersistentAssetData, 0));
    gen2124.Empty();
    auto& gen2125 = (*TBaseStructure<FGameplayTagContainer>::Get()->FindPropertyByName("GameplayTags")->ContainerPtrToValuePtr<TArray<FGameplayTag>>(&(*this).MetaMenuActiveTags, 0));
    gen2125.Empty();
    auto& gen2126 = (*TBaseStructure<FGameplayTagContainer>::Get()->FindPropertyByName("ParentTags")->ContainerPtrToValuePtr<TArray<FGameplayTag>>(&(*this).MetaMenuActiveTags, 0));
    gen2126.Empty();
    (*this).CurrentChainMissionID = nullptr;
    auto& gen2127 = (*this).Achievements;
    gen2127.Empty();
    (*this).PreviousSession.SessionId = TEXT("");
    (*this).PreviousSession.MissionID.A = 0;
    (*this).PreviousSession.MissionID.B = 0;
    (*this).PreviousSession.MissionID.C = 0;
    (*this).PreviousSession.MissionID.D = 0;
    auto& gen2128 = (*TBaseStructure<FGameplayTagContainer>::Get()->FindPropertyByName("GameplayTags")->ContainerPtrToValuePtr<TArray<FGameplayTag>>(&(*this).CompletedTutorialTags, 0));
    gen2128.Empty();
    auto& gen2129 = (*TBaseStructure<FGameplayTagContainer>::Get()->FindPropertyByName("ParentTags")->ContainerPtrToValuePtr<TArray<FGameplayTag>>(&(*this).CompletedTutorialTags, 0));
    gen2129.Empty();
    (*this).UserAnalyticsID = TEXT("");
    (*this).UserCountry = TEXT("");
    (*this).UserRegion = TEXT("");
    (*this).UserCity = TEXT("");
    (*this).SaveDataVersion.JsonVersion = 0;
    (*this).SaveDataVersion.RevisionCreated = TEXT("");
    (*this).SaveDataVersion.RevisionSaved = TEXT("");
    (*this).SaveDataVersion.SnapshotRevision = TEXT("");
    (*this).MetaPersistentId = TEXT("0");
    (*this).bUserShouldAdvertise = true;
    (*TBaseStructure<FGameplayTag>::Get()->FindPropertyByName("TagName")->ContainerPtrToValuePtr<FName>(&(*this).ActiveCampaign.CampaignMode, 0)) = NAME_None;
    (*this).ActiveCampaign.Difficulty = EIGS_UserDifficulty::UD_Unknown;
    (*this).Progression.ProgressLevel = 0;
    (*this).Progression.ProgressToNextLevel = 0.000000000e+00f;
    (*this).Progression.PendingUnlockedLevelUps = 0;
    auto& gen2130 = (*this).Progression.PendingUnlockedItems;
    gen2130.Empty();
    auto& gen2131 = (*this).Progression.UnlockedRewardsHistory;
    gen2131.Empty();
}

