#include "IGS_SaveData_Quickplay.h"
#include "GameplayTagContainer.h"
#include "GameplayTagContainer.h"
#include "EIGS_ChainType.h"
#include "EMETA_ItemQuality.h"

FIGS_SaveData_Quickplay::FIGS_SaveData_Quickplay() {
    (*this).SaveSlot = TEXT("");
    (*this).bIsFilled = false;
    (*this).BlackmarketManagerData.bInited = false;
    auto& gen2286 = (*this).BlackmarketManagerData.Heisters;
    gen2286.Empty();
    auto& gen2287 = (*this).BlackmarketManagerData.Weapons;
    gen2287.Empty();
    auto& gen2288 = (*this).BlackmarketManagerData.WeaponSkins;
    gen2288.Empty();
    auto& gen2289 = (*this).BlackmarketManagerData.Equipment;
    gen2289.Empty();
    auto& gen2290 = (*this).BlackmarketManagerData.Perks;
    gen2290.Empty();
    auto& gen2291 = (*this).BlackmarketManagerData.BossCharacterSkins;
    gen2291.Empty();
    auto& gen2292 = (*this).BlackmarketManagerData.UnseenUnlockedCharacterTagIDs;
    gen2292.Empty();
    auto& gen2293 = (*this).BlackmarketManagerData.UnseenUnlockedWeaponTagIDs;
    gen2293.Empty();
    auto& gen2294 = (*this).BlackmarketManagerData.UnseenUnlockedEquipmentTagIDs;
    gen2294.Empty();
    (*this).CrewManagerData.bInited = false;
    auto& gen2295 = (*this).CrewManagerData.Heisters;
    gen2295.Empty();
    (*this).CrewManagerData.BossCharacter.Loadout.PrimaryWeapon = nullptr;
    (*this).CrewManagerData.BossCharacter.Loadout.PrimaryWeaponSaveData.Amount = 0;
    (*this).CrewManagerData.BossCharacter.Loadout.PrimaryWeaponSaveData.AdditionalPercentageOfWeaponPrice = 0;
    (*this).CrewManagerData.BossCharacter.Loadout.PrimaryWeaponSaveData.SuccessfulMissions = 0;
    (*this).CrewManagerData.BossCharacter.Loadout.PrimaryWeaponSaveData.DaysInShop = 0;
    (*TBaseStructure<FGameplayTag>::Get()->FindPropertyByName("TagName")->ContainerPtrToValuePtr<FName>(&(*this).CrewManagerData.BossCharacter.Loadout.PrimaryWeaponSaveData.WeaponSkin, 0)) = NAME_None;
    auto& gen2296 = (*this).CrewManagerData.BossCharacter.Loadout.PrimaryWeaponSaveData.TargetWeaponsForUpgrade;
    gen2296.Empty();
    (*this).CrewManagerData.BossCharacter.Loadout.PrimaryWeaponSaveData.TargetQualityToUpdateWeapon = EMETA_ItemQuality::None;
    (*TBaseStructure<FGameplayTag>::Get()->FindPropertyByName("TagName")->ContainerPtrToValuePtr<FName>(&(*this).CrewManagerData.BossCharacter.Loadout.PrimaryWeaponSaveData.itemTag, 0)) = NAME_None;
    (*this).CrewManagerData.BossCharacter.Loadout.PrimaryWeaponSaveData.Price = 0;
    (*this).CrewManagerData.BossCharacter.Loadout.PrimaryWeaponSaveData.IsUnseenInShop = false;
    auto& gen2297 = (*this).CrewManagerData.BossCharacter.Loadout.PrimaryPersonalWeapons;
    gen2297.Empty();
    (*this).CrewManagerData.BossCharacter.Loadout.SecondaryWeapon = nullptr;
    (*this).CrewManagerData.BossCharacter.Loadout.SecondaryWeaponSaveData.Amount = 0;
    (*this).CrewManagerData.BossCharacter.Loadout.SecondaryWeaponSaveData.AdditionalPercentageOfWeaponPrice = 0;
    (*this).CrewManagerData.BossCharacter.Loadout.SecondaryWeaponSaveData.SuccessfulMissions = 0;
    (*this).CrewManagerData.BossCharacter.Loadout.SecondaryWeaponSaveData.DaysInShop = 0;
    (*TBaseStructure<FGameplayTag>::Get()->FindPropertyByName("TagName")->ContainerPtrToValuePtr<FName>(&(*this).CrewManagerData.BossCharacter.Loadout.SecondaryWeaponSaveData.WeaponSkin, 0)) = NAME_None;
    auto& gen2298 = (*this).CrewManagerData.BossCharacter.Loadout.SecondaryWeaponSaveData.TargetWeaponsForUpgrade;
    gen2298.Empty();
    (*this).CrewManagerData.BossCharacter.Loadout.SecondaryWeaponSaveData.TargetQualityToUpdateWeapon = EMETA_ItemQuality::None;
    (*TBaseStructure<FGameplayTag>::Get()->FindPropertyByName("TagName")->ContainerPtrToValuePtr<FName>(&(*this).CrewManagerData.BossCharacter.Loadout.SecondaryWeaponSaveData.itemTag, 0)) = NAME_None;
    (*this).CrewManagerData.BossCharacter.Loadout.SecondaryWeaponSaveData.Price = 0;
    (*this).CrewManagerData.BossCharacter.Loadout.SecondaryWeaponSaveData.IsUnseenInShop = false;
    auto& gen2299 = (*this).CrewManagerData.BossCharacter.Loadout.SecondaryPersonalWeapons;
    gen2299.Empty();
    auto& gen2300 = (*this).CrewManagerData.BossCharacter.Loadout.Equipment;
    gen2300.Empty();
    (*this).CrewManagerData.BossCharacter.Loadout.SelectedEquipment.EquipmentID = nullptr;
    (*TBaseStructure<FGameplayTag>::Get()->FindPropertyByName("TagName")->ContainerPtrToValuePtr<FName>(&(*this).CrewManagerData.BossCharacter.Loadout.SelectedEquipment.itemTag, 0)) = NAME_None;
    (*this).CrewManagerData.BossCharacter.Loadout.SelectedEquipment.Price = 0;
    (*this).CrewManagerData.BossCharacter.Loadout.SelectedEquipment.IsUnseenInShop = false;
    (*TBaseStructure<FGameplayTag>::Get()->FindPropertyByName("TagName")->ContainerPtrToValuePtr<FName>(&(*this).CrewManagerData.BossCharacter.Loadout.CharacterSkin, 0)) = NAME_None;
    auto& gen2301 = (*this).CrewManagerData.BossCharacter.Perks;
    gen2301.Empty();
    (*this).StashManagerData.bInited = false;
    auto& gen2302 = (*this).StashManagerData.PrimaryWeapons;
    gen2302.Empty();
    auto& gen2303 = (*this).StashManagerData.SecondaryWeapons;
    gen2303.Empty();
    auto& gen2304 = (*this).StashManagerData.WeaponSkins;
    gen2304.Empty();
    auto& gen2305 = (*this).StashManagerData.Equipment;
    gen2305.Empty();
    auto& gen2306 = (*this).StashManagerData.Perks;
    gen2306.Empty();
    auto& gen2307 = (*this).StashManagerData.BossCharacterSkins;
    gen2307.Empty();
    (*this).CityMapManagerData.LastDayOfTilesIncomeRefresh = 0;
    (*this).FinanceManagerData.bInited = false;
    (*this).FinanceManagerData.Balance = 0;
    auto& gen2308 = (*this).ContractManagerData.AvailableContracts;
    gen2308.Empty();
    auto& gen2309 = (*this).ContractManagerData.ActiveContractMissions.MoneyMakingMissions;
    gen2309.Empty();
    auto& gen2310 = (*this).ContractManagerData.ActiveContractMissions.AmbushMissions;
    gen2310.Empty();
    auto& gen2311 = (*this).ContractManagerData.ActiveContractMissions.StoryMissions;
    gen2311.Empty();
    auto& gen2312 = (*this).ContractManagerData.ActiveContractMissions.TradeMissions;
    gen2312.Empty();
    auto& gen2313 = (*this).ContractManagerData.ActiveContractMissions.TradeDealSellMissions;
    gen2313.Empty();
    auto& gen2314 = (*this).ContractManagerData.ActiveContractMissions.CinematicMissions;
    gen2314.Empty();
    auto& gen2315 = (*this).ContractManagerData.ActiveContractMissions.TurfWarMissions;
    gen2315.Empty();
    auto& gen2316 = (*this).ContractManagerData.ActiveContractMissions.OtherMissions;
    gen2316.Empty();
    auto& gen2317 = (*this).ChainContractManagerData.ActiveChainsData;
    gen2317.Empty();
    (*this).ChainContractManagerData.ActiveChainType = EIGS_ChainType::UrbanLegend;
    (*this).ChainContractManagerData.LastUsedGenericID = 0;
    (*this).ChainContractManagerData.WasPlayingChainMission = false;
    (*this).JobManagerData.CurrentJob = nullptr;
    auto& gen2318 = (*this).JobManagerData.Opportunities.MoneyMakingMissions;
    gen2318.Empty();
    auto& gen2319 = (*this).JobManagerData.Opportunities.AmbushMissions;
    gen2319.Empty();
    auto& gen2320 = (*this).JobManagerData.Opportunities.StoryMissions;
    gen2320.Empty();
    auto& gen2321 = (*this).JobManagerData.Opportunities.TradeMissions;
    gen2321.Empty();
    auto& gen2322 = (*this).JobManagerData.Opportunities.TradeDealSellMissions;
    gen2322.Empty();
    auto& gen2323 = (*this).JobManagerData.Opportunities.CinematicMissions;
    gen2323.Empty();
    auto& gen2324 = (*this).JobManagerData.Opportunities.TurfWarMissions;
    gen2324.Empty();
    auto& gen2325 = (*this).JobManagerData.Opportunities.OtherMissions;
    gen2325.Empty();
    auto& gen2326 = (*this).JobManagerData.LastPlayedMission.MoneyMakingMissions;
    gen2326.Empty();
    auto& gen2327 = (*this).JobManagerData.LastPlayedMission.AmbushMissions;
    gen2327.Empty();
    auto& gen2328 = (*this).JobManagerData.LastPlayedMission.StoryMissions;
    gen2328.Empty();
    auto& gen2329 = (*this).JobManagerData.LastPlayedMission.TradeMissions;
    gen2329.Empty();
    auto& gen2330 = (*this).JobManagerData.LastPlayedMission.TradeDealSellMissions;
    gen2330.Empty();
    auto& gen2331 = (*this).JobManagerData.LastPlayedMission.CinematicMissions;
    gen2331.Empty();
    auto& gen2332 = (*this).JobManagerData.LastPlayedMission.TurfWarMissions;
    gen2332.Empty();
    auto& gen2333 = (*this).JobManagerData.LastPlayedMission.OtherMissions;
    gen2333.Empty();
    auto& gen2334 = (*this).JobManagerData.FinishedMissionsIDs;
    gen2334.Empty();
    (*this).JobManagerData.bLastPlayedWasChain = false;
    (*this).PlayerManagerData.RespectPoints = 0;
    (*this).PlayerManagerData.TotalScorePoints = 0;
    auto& gen2335 = (*TBaseStructure<FGameplayTagContainer>::Get()->FindPropertyByName("GameplayTags")->ContainerPtrToValuePtr<TArray<FGameplayTag>>(&(*this).EntitlementItemsData.IDs, 0));
    gen2335.Empty();
    auto& gen2336 = (*TBaseStructure<FGameplayTagContainer>::Get()->FindPropertyByName("ParentTags")->ContainerPtrToValuePtr<TArray<FGameplayTag>>(&(*this).EntitlementItemsData.IDs, 0));
    gen2336.Empty();
    (*this).SaveDataVersion.JsonVersion = 0;
    (*this).SaveDataVersion.RevisionCreated = TEXT("");
    (*this).SaveDataVersion.RevisionSaved = TEXT("");
    (*this).SaveDataVersion.SnapshotRevision = TEXT("");
    (*this).MetaPersistentId = TEXT("0");
    (*this).WantsToGoOffline = false;
}

