#include "META_GenericCharacterSave.h"

FMETA_GenericCharacterSave::FMETA_GenericCharacterSave() {
    (*TBaseStructure<FGameplayTag>::Get()->FindPropertyByName("TagName")->ContainerPtrToValuePtr<FName>(&(*this).TagID, 0)) = NAME_None;
    (*this).ItemPrice = 0;
    (*this).ArrayIndex = 0;
    (*this).ID = EIGS_CharacterID::Char_Unknown;
    (*this).GenericUniqId = -1;
    (*this).GenericVariantID = -1;
    (*this).MutableVariationIndex = -1;
    (*this).Name = FText::FromString(TEXT(""));
    (*this).Surname = FText::FromString(TEXT(""));
    (*this).Quality = EMETA_ItemQuality::None;
    (*this).Level = 1;
    (*this).CanLevelUp = true;
    (*this).UpkeepCost = 0;
    (*this).MissionCutPercent = 0;
    (*this).HireCost = 0;
    (*this).WeaponsCostCoefficient = 1.000000000e+00f;
    (*this).CarryCapacity = 0;
    (*this).Injuries = 0;
    (*this).TimesHealed = 0;
    (*this).JobsCanBeCompletedPerDay = 1;
    (*this).State = EMETA_CharacterState::None;
    (*this).Mood = EMETA_CharacterMood::Neutral;
    auto& gen2239 = (*TBaseStructure<FGameplayTagContainer>::Get()->FindPropertyByName("GameplayTags")->ContainerPtrToValuePtr<TArray<FGameplayTag>>(&(*this).Traits, 0));
    gen2239.Empty();
    auto& gen2240 = (*TBaseStructure<FGameplayTagContainer>::Get()->FindPropertyByName("ParentTags")->ContainerPtrToValuePtr<TArray<FGameplayTag>>(&(*this).Traits, 0));
    gen2240.Empty();
    auto& gen2241 = (*this).Perks;
    gen2241.Empty();
    auto& gen2242 = (*this).ChangedHeisterAttributes;
    gen2242.Empty();
    (*this).InjureChanceInPercentage = 0;
    (*this).Loadout.PrimaryWeapon = nullptr;
    (*this).Loadout.PrimaryWeaponSaveData.Amount = 0;
    (*this).Loadout.PrimaryWeaponSaveData.AdditionalPercentageOfWeaponPrice = 0;
    (*this).Loadout.PrimaryWeaponSaveData.SuccessfulMissions = 0;
    (*this).Loadout.PrimaryWeaponSaveData.DaysInShop = 0;
    (*TBaseStructure<FGameplayTag>::Get()->FindPropertyByName("TagName")->ContainerPtrToValuePtr<FName>(&(*this).Loadout.PrimaryWeaponSaveData.WeaponSkin, 0)) = NAME_None;
    auto& gen2243 = (*this).Loadout.PrimaryWeaponSaveData.TargetWeaponsForUpgrade;
    gen2243.Empty();
    (*this).Loadout.PrimaryWeaponSaveData.TargetQualityToUpdateWeapon = EMETA_ItemQuality::None;
    (*TBaseStructure<FGameplayTag>::Get()->FindPropertyByName("TagName")->ContainerPtrToValuePtr<FName>(&(*this).Loadout.PrimaryWeaponSaveData.itemTag, 0)) = NAME_None;
    (*this).Loadout.PrimaryWeaponSaveData.Price = 0;
    (*this).Loadout.PrimaryWeaponSaveData.IsUnseenInShop = false;
    auto& gen2244 = (*this).Loadout.PrimaryPersonalWeapons;
    gen2244.Empty();
    (*this).Loadout.SecondaryWeapon = nullptr;
    (*this).Loadout.SecondaryWeaponSaveData.Amount = 0;
    (*this).Loadout.SecondaryWeaponSaveData.AdditionalPercentageOfWeaponPrice = 0;
    (*this).Loadout.SecondaryWeaponSaveData.SuccessfulMissions = 0;
    (*this).Loadout.SecondaryWeaponSaveData.DaysInShop = 0;
    (*TBaseStructure<FGameplayTag>::Get()->FindPropertyByName("TagName")->ContainerPtrToValuePtr<FName>(&(*this).Loadout.SecondaryWeaponSaveData.WeaponSkin, 0)) = NAME_None;
    auto& gen2245 = (*this).Loadout.SecondaryWeaponSaveData.TargetWeaponsForUpgrade;
    gen2245.Empty();
    (*this).Loadout.SecondaryWeaponSaveData.TargetQualityToUpdateWeapon = EMETA_ItemQuality::None;
    (*TBaseStructure<FGameplayTag>::Get()->FindPropertyByName("TagName")->ContainerPtrToValuePtr<FName>(&(*this).Loadout.SecondaryWeaponSaveData.itemTag, 0)) = NAME_None;
    (*this).Loadout.SecondaryWeaponSaveData.Price = 0;
    (*this).Loadout.SecondaryWeaponSaveData.IsUnseenInShop = false;
    auto& gen2246 = (*this).Loadout.SecondaryPersonalWeapons;
    gen2246.Empty();
    auto& gen2247 = (*this).Loadout.Equipment;
    gen2247.Empty();
    (*this).Loadout.SelectedEquipment.EquipmentID = nullptr;
    (*TBaseStructure<FGameplayTag>::Get()->FindPropertyByName("TagName")->ContainerPtrToValuePtr<FName>(&(*this).Loadout.SelectedEquipment.itemTag, 0)) = NAME_None;
    (*this).Loadout.SelectedEquipment.Price = 0;
    (*this).Loadout.SelectedEquipment.IsUnseenInShop = false;
    (*TBaseStructure<FGameplayTag>::Get()->FindPropertyByName("TagName")->ContainerPtrToValuePtr<FName>(&(*this).Loadout.CharacterSkin, 0)) = NAME_None;
    (*this).MissionsWasPlayed = 0;
    (*this).bTemporary = false;
    auto& gen2248 = (*this).SerializedMutableProfile;
    gen2248.Empty();
    (*this).BaseLevelUpMultiplier = 0.000000000e+00f;
}

